[package]
name = "canonrs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CanonRS — Leptos-based UI framework for canonical web applications"

[dependencies]
canonrs-core = { version = "0.1.0",  path = "../canonrs-core" }
canonrs-server = { version = "0.1.0",  path = "../canonrs-server", default-features = false, optional = true }
canonrs-client = { version = "0.1.0",  path = "../canonrs-client", optional = true }
canonrs-interactions = { version = "0.1.0",  path = "../canonrs-interactions", optional = true }

[features]
default = []
examples = ["dep:canonrs-server", "canonrs-server/examples"]
ssr = ["dep:canonrs-server", "canonrs-server/ssr", "canonrs-core/ssr"]
hydrate = ["dep:canonrs-server", "canonrs-server/hydrate", "dep:canonrs-client", "canonrs-client/hydrate", "canonrs-core/hydrate", "dep:canonrs-interactions"]
