// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COLUMNS_API: ComponentApi = ComponentApi {
    id: "columns",
    props: &[
        PropDef { name: "count", kind: PropType::String, required: false, default: Some("2"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "columns", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

