// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LINKGROUP_API: ComponentApi = ComponentApi {
    id: "link-group",
    description: "Wrapper that organizes multiple NavItems into a labeled navigation group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "label", kind: PropType::String, required: false, default: None, description: "Accessible label text" },
        PropDef { name: "direction", kind: PropType::String, required: false, default: Some("vertical"), description: "Stack or flex direction" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

