// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const EMPTYSTATE_API: ComponentApi = ComponentApi {
    id: "empty-state",
    props: &[
        PropDef { name: "icon", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "description", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "action", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

