// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const MARKDOWNBLOCK_API: ComponentApi = ComponentApi {
    id: "markdown-block",
    props: &[
        PropDef { name: "header", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "footer", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "content", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

