// UI Components - Family A: Overlays only (for testing)

pub mod dialog;
pub mod sheet;
pub mod drawer;
pub mod popover;
pub mod form;
pub mod hero;
pub mod hover_card;
pub mod tooltip;
pub mod dropdown_menu;
pub mod context_menu;
pub mod modal;

// Temporary: needed by blocks
pub mod button;
pub mod tabs;
pub mod code_block;
pub mod badge;
pub mod input;

pub use button::Button;
pub use button::ButtonPreview;
pub use button_group::ButtonGroupShowcasePreview;
pub use icon_button::IconButtonShowcasePreview;
pub use copy_button::CopyButtonShowcasePreview;
pub use link::LinkShowcasePreview;
pub use select::SelectShowcasePreview;
pub use combobox::ComboboxShowcasePreview;
pub use radio::RadioShowcasePreview;
pub use radio_group::RadioGroupShowcasePreview;
pub use color_picker::ColorPickerShowcasePreview;
pub use slider::SliderShowcasePreview;
pub use tabs::TabsShowcasePreview;
pub use table_of_contents::TableOfContentsShowcasePreview;
pub use accordion::AccordionShowcasePreview;
pub use collapsible::CollapsibleShowcasePreview;
pub use dropdown_menu::DropdownMenuShowcasePreview;
pub use context_menu::ContextMenuShowcasePreview;
pub use menubar::MenubarShowcasePreview;
pub use menu::MenuShowcasePreview;
pub use command::CommandShowcasePreview;
pub use navigation_menu::NavigationMenuShowcasePreview;
pub use sidebar::SidebarShowcasePreview;
pub use nav_item::NavItemShowcasePreview;
pub use breadcrumb::BreadcrumbShowcasePreview;
pub use pagination::PaginationShowcasePreview;
pub use link_group::LinkGroupShowcasePreview;
pub use toast::ToastShowcasePreview;
pub use alert::AlertShowcasePreview;
pub use banner::BannerShowcasePreview;
pub use callout::CalloutShowcasePreview;
pub use inline_notice::InlineNoticeShowcasePreview;
pub use status_dot::StatusDotShowcasePreview;
pub use dialog::DialogShowcasePreview;
pub use alert_dialog::AlertDialogShowcasePreview;
pub use drawer::DrawerShowcasePreview;
pub use sheet::SheetShowcasePreview;
pub use modal::ModalShowcasePreview;
pub use confirm_dialog::ConfirmDialogShowcasePreview;
pub use tooltip::TooltipShowcasePreview;
pub use hover_card::HoverCardShowcasePreview;
pub use popover::PopoverShowcasePreview;
pub use form::FormShowcasePreview;
pub use input::InputShowcasePreview;
pub use input_group::InputGroupShowcasePreview;
pub use input_otp::InputOtpShowcasePreview;
pub use textarea::TextareaShowcasePreview;
pub use field::FieldShowcasePreview;
pub use label::LabelShowcasePreview;
pub use checkbox::CheckboxShowcasePreview;
pub use form_error_summary::FormErrorSummaryShowcasePreview;
pub use table::TableShowcasePreview;
pub use data_table::DataTableFullShowcasePreview;
pub use virtual_list::VirtualListShowcasePreview;
pub use empty_table::EmptyTableShowcasePreview;
pub use tree::TreeShowcasePreview;
pub use list_item::ListItemShowcasePreview;
pub use switch::SwitchShowcasePreview;
pub use toggle::ToggleShowcasePreview;
pub use toggle_group::ToggleGroupShowcasePreview;
pub use progress::ProgressShowcasePreview;
pub use spinner::SpinnerShowcasePreview;
pub use skeleton::SkeletonShowcasePreview;
pub use pulse::PulseShowcasePreview;
pub use loading_overlay::LoadingOverlayShowcasePreview;
pub use doc_progress::DocProgressShowcasePreview;
pub use card::CardShowcasePreview;
pub use resizable::ResizableShowcasePreview;
pub use scroll_area::ScrollAreaShowcasePreview;
pub use aspect_ratio::AspectRatioShowcasePreview;
pub use page_header::PageHeaderShowcasePreview;
pub use toolbar::ToolbarShowcasePreview;
pub use separator::SeparatorShowcasePreview;
pub use avatar::AvatarShowcasePreview;
pub use icon::IconShowcasePreview;
pub use logo::LogoShowcasePreview;
pub use code_block::CodeBlockShowcasePreview;
pub use markdown::MarkdownShowcasePreview;
pub use chart::ChartShowcasePreview;
pub use stat::StatShowcasePreview;
pub use inline_meta::InlineMetaShowcasePreview;
pub use kbd::KbdShowcasePreview;
pub use badge::BadgeShowcasePreview;
pub use carousel::CarouselShowcasePreview;
pub use empty_state::EmptyStateShowcasePreview;
pub use error_state::ErrorStateShowcasePreview;
pub use animate::AnimateShowcasePreview;
pub use badge::Badge;
pub use input::Input;
pub use tabs::{Tabs, TabsList, TabsTrigger, TabsContent};
pub mod menu;
pub mod menubar;
pub mod tree;
pub mod checkbox;
pub mod accordion;
pub mod collapsible;
pub mod combobox;
pub use combobox::{ComboboxIsland, ComboboxOption};
pub mod command;
pub mod radio_group;
pub mod radio;
pub use radio::{RadioGroupIsland, RadioOption};
pub mod kbd;
pub mod button_group;
pub mod color_picker;
pub mod form_error_summary;
pub mod field;
pub mod input_group;
pub mod input_otp;
pub mod textarea;
pub mod slider;
pub use slider::SliderIsland;
pub use button::ButtonIsland;
pub use button_group::ButtonGroupIsland;
pub mod label;
pub mod switch;
pub mod select;
pub use select::{SelectIsland, SelectOption};
pub mod toggle;
pub mod toggle_group;

// Family D - Navigation
pub mod link;
pub use link::{LinkIsland, LinkVariant};
pub mod navigation_menu;
pub mod link_group;
pub mod nav_item;
pub mod page_header;
pub mod table_of_contents;
pub mod breadcrumb;
pub mod pagination;
pub mod sidebar;
pub mod toolbar;

// Family E - Feedback
pub mod alert;
pub mod alert_dialog;
pub mod confirm_dialog;
pub mod progress;
pub mod pulse;
pub mod skeleton;
pub mod spinner;
pub mod status_dot;
pub mod toast;
pub mod banner;
pub mod callout;
pub mod empty_state;
pub mod error_state;
pub mod inline_meta;
pub mod inline_notice;
pub mod loading_overlay;
pub mod empty_table;

// Family F - Data & Media
pub mod table;
pub mod data_table;
pub mod chart;
pub mod scroll_area;
pub mod avatar;
pub mod icon;
pub mod copy_button;
pub use copy_button::CopyButtonIsland;
pub mod stat;
pub mod icon_button;
pub use icon_button::icon_button_ui::{IconButton, IconButtonVariant};
pub use icon_button::{IconButtonIsland, IconButtonSize};
pub mod list_item;
pub mod card;
pub mod markdown;

// Family G - Composite
pub mod carousel;
pub mod resizable;

// Family H - Layout
pub mod section;
pub mod separator;
pub mod aspect_ratio;
pub mod doc_progress;
pub use doc_progress::{DocProgress, DocProgressSlot};

pub mod animate;
pub mod virtual_list;
pub use card::Card;
pub use separator::Separator;

pub mod logo;
pub use logo::{Logo, LogoSize, LogoVariant};
