// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TABLE_API: ComponentApi = ComponentApi {
    id: "table",
    props: &[
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("idle"), description: "" },
        PropDef { name: "striped", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "hoverable", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLEHEADER_API: ComponentApi = ComponentApi {
    id: "table-header",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLEBODY_API: ComponentApi = ComponentApi {
    id: "table-body",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLEFOOTER_API: ComponentApi = ComponentApi {
    id: "table-footer",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLEROW_API: ComponentApi = ComponentApi {
    id: "table-row",
    props: &[
        PropDef { name: "selected", kind: PropType::String, required: false, default: Some("unselected"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLEHEAD_API: ComponentApi = ComponentApi {
    id: "table-head",
    props: &[
        PropDef { name: "sort", kind: PropType::Enum(&["none", "ascending", "descending"]), required: false, default: Some("none"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLECELL_API: ComponentApi = ComponentApi {
    id: "table-cell",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABLECAPTION_API: ComponentApi = ComponentApi {
    id: "table-caption",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

