// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FOOTER_API: ComponentApi = ComponentApi {
    id: "footer",
    props: &[
        PropDef { name: "top", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "bottom", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "left", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "center", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "right", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

