// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORMERRORSUMMARY_API: ComponentApi = ComponentApi {
    id: "form-error-summary",
    description: "Form validation error summary",
    props: &[
        PropDef { name: "errors", kind: PropType::String, required: false, default: None, description: "Prop value" },
        PropDef { name: "title", kind: PropType::String, required: false, default: Some("Please fix the following errors:"), description: "Title slot or text" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

