// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORMERRORSUMMARY_API: ComponentApi = ComponentApi {
    id: "form-error-summary",
    props: &[
        PropDef { name: ")] errors", kind: PropType::String, required: false, default: Some("vec![]"), description: "" },
        PropDef { name: "title", kind: PropType::String, required: false, default: Some("Please fix the following errors:"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

