//! Block Types — pure types for blocks, regions, props
//! No dependencies on core-services — safe to use everywhere
//! Statics generated by build.rs from @canon-* headers

use crate::meta::ComponentMeta;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PropFieldType {
    Text,
    Number,
    Select(&'static [(&'static str, &'static str)]),
    Toggle,
    Color,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PropScope {
    Structural,
    Visual,
    Typography,
    Capability,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockPropDef {
    pub key:     &'static str,
    pub label:   &'static str,
    pub field:   PropFieldType,
    pub default: Option<&'static str>,
    pub scope:   PropScope,
    pub css:     Option<&'static str>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockPreset {
    pub label: &'static str,
    pub props: &'static [(&'static str, &'static str)],
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BlockVariant { Structure, Page, Feature, Overlay, Special }

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum BlockCategory { Layout, Page, Data, Form, Content, Overlay, Slot, Component }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RegionLayout { Vertical, Horizontal, Grid { columns: u8, gap: u8 } }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AcceptRule {
    Category(BlockCategory),
    Block(&'static str),
    Any,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BlockRegion {
    pub id:           &'static str,
    pub accepts:      &'static [AcceptRule],
    pub layout:       RegionLayout,
    pub max_children: Option<usize>,
}

impl BlockRegion {
    pub fn accepts_block(&self, block_id: &str, category: BlockCategory) -> bool {
        self.accepts.iter().any(|rule| match rule {
            AcceptRule::Any           => true,
            AcceptRule::Category(c)   => *c == category,
            AcceptRule::Block(id)     => *id == block_id,
        })
    }

    pub fn accepts_block_with_count(
        &self,
        block_id: &str,
        category: BlockCategory,
        current_children: usize,
    ) -> Result<(), &'static str> {
        if let Some(max) = self.max_children {
            if current_children >= max { return Err("Region max_children exceeded"); }
        }
        if self.accepts_block(block_id, category) { Ok(()) }
        else { Err("Region does not accept this block") }
    }
}

/// Type-erased reconcile fn — core-services provides the concrete type via ReconcileFn
pub type AnyReconcileFn = fn();

#[derive(Clone, Debug)]
pub struct BlockDefinition {
    pub id:              &'static str,
    pub variant:         BlockVariant,
    pub category:        BlockCategory,
    pub is_container:    bool,
    pub regions:         &'static [BlockRegion],
    pub version:         u32,
    pub props_schema:    &'static [BlockPropDef],
    pub requires_config: bool,
    pub presets:         &'static [BlockPreset],
    pub meta:            &'static ComponentMeta,
}

impl PartialEq for BlockDefinition {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
            && self.variant == other.variant
            && self.category == other.category
            && self.is_container == other.is_container
            && self.version == other.version
            && self.requires_config == other.requires_config
    }
}

impl BlockDefinition {
    pub fn find(id: &str) -> Option<&'static BlockDefinition> {
        crate::generated::block_definitions::BLOCK_DEFINITIONS_GENERATED.iter().find(|d| d.id == id)
            .or_else(|| crate::generated::block_definitions::LAYOUT_DEFINITIONS_GENERATED.iter().find(|d| d.id == id))
    }

    pub fn by_variant(v: BlockVariant) -> impl Iterator<Item = &'static BlockDefinition> {
        crate::generated::block_definitions::BLOCK_DEFINITIONS_GENERATED.iter().filter(move |d| d.variant == v)
    }

    pub fn by_category(c: BlockCategory) -> impl Iterator<Item = &'static BlockDefinition> {
        crate::generated::block_definitions::BLOCK_DEFINITIONS_GENERATED.iter().filter(move |d| d.category == c)
    }

    pub fn find_region(&self, region_id: &str) -> Option<&'static BlockRegion> {
        self.regions.iter().find(|r| r.id == region_id)
    }

    pub fn component_meta(&self) -> &'static crate::meta::ComponentMeta {
        self.meta
    }

    pub fn final_props(&self) -> Vec<BlockPropDef> {
        use crate::meta::{derive_props_from_meta, CapabilityPropKind};
        let mut props = self.props_schema.to_vec();
        for cap in derive_props_from_meta(self.meta) {
            if !props.iter().any(|p| p.key == cap.key) {
                props.push(BlockPropDef {
                    key: cap.key,
                    label: cap.label,
                    field: match cap.kind {
                        CapabilityPropKind::Bool   => PropFieldType::Toggle,
                        CapabilityPropKind::String => PropFieldType::Text,
                        CapabilityPropKind::Enum(opts) => PropFieldType::Select(
                            opts.iter().map(|v| (*v, *v)).collect::<Vec<_>>().leak()
                        ),
                    },
                    default: cap.default,
                    scope: PropScope::Capability,
                    css: None,
                });
            }
        }
        props
    }

    pub fn can_accept_in_any_region(&self, block_id: &str, category: BlockCategory) -> bool {
        self.regions.iter().any(|r| r.accepts_block(block_id, category))
    }
}

// ── Layout Definition (generated from @canon-* headers) ──────────────────────

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LayoutSlot {
    pub id:          &'static str,
    pub description: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LayoutDefinition {
    pub id:          &'static str,
    pub label:       &'static str,
    pub description: &'static str,
    pub icon:        &'static str,
    pub slots:       &'static [LayoutSlot],
}

impl LayoutDefinition {
    pub fn find(id: &str) -> Option<&'static LayoutDefinition> {
        crate::generated::layout_definitions::LAYOUT_DEFINITIONS_STATIC.iter().find(|l| l.id == id)
    }
    pub fn slot_ids(&self) -> Vec<&'static str> {
        self.slots.iter().map(|s| s.id).collect()
    }
    pub fn all() -> &'static [LayoutDefinition] {
        crate::generated::layout_definitions::LAYOUT_DEFINITIONS_STATIC
    }
}
