//! CanonRS Meta Types — structs, enums, traits
//! Statics are generated by build.rs → src/generated/

//! @canon-level: strict
//! @canon-owner: primitives-team
//! ComponentMeta — metadata layer para AI/RAG/Decision Engine


/// Typed capability enum — substitui &["open-close"] strings hardcoded
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Capability {
    OpenClose,
    Selected,
    Active,
    Pressed,
    Disabled,
    Loading,
    Value,
    Multiple,
    Orientation,
    // Pure behaviors — sem props derivadas
    FocusTrap,
    KeyboardEsc,
    AriaModal,
    KeyboardArrows,
    Roving,
    Typeahead,
    VirtualScroll,
    DragDrop,
    Resize,
    Overflow,
    Animation,
}

impl Capability {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::OpenClose      => "open-close",
            Self::Selected       => "selected",
            Self::Active         => "active",
            Self::Pressed        => "pressed",
            Self::Disabled       => "disabled",
            Self::Loading        => "loading",
            Self::Value          => "value",
            Self::Multiple       => "multiple",
            Self::Orientation    => "orientation",
            Self::FocusTrap      => "focus-trap",
            Self::KeyboardEsc    => "keyboard-esc",
            Self::AriaModal      => "aria-modal",
            Self::KeyboardArrows => "keyboard-arrows",
            Self::Roving         => "roving",
            Self::Typeahead      => "typeahead",
            Self::VirtualScroll  => "virtual-scroll",
            Self::DragDrop       => "drag-drop",
            Self::Resize         => "resize",
            Self::Overflow       => "overflow",
            Self::Animation      => "animation",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ComponentMeta {
    pub id:   &'static str,
    pub name: &'static str,
    pub family: ComponentFamily,
    pub intent: &'static str,
    pub capabilities: &'static [Capability],
    pub composable: bool,
    pub required_parts: &'static [&'static str],
    pub optional_parts: &'static [&'static str],
}

#[derive(Debug, Clone, PartialEq)]
pub enum ComponentFamily {
    Overlay,
    Input,
    Feedback,
    Navigation,
    Layout,
    DataDisplay,
    Typography,
    Interactive,
    Utility,
}

impl ComponentFamily {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Overlay     => "overlay",
            Self::Input       => "input",
            Self::Feedback    => "feedback",
            Self::Navigation  => "navigation",
            Self::Layout      => "layout",
            Self::DataDisplay => "data-display",
            Self::Typography  => "typography",
            Self::Interactive => "interactive",
            Self::Utility     => "utility",
        }
    }
}

pub trait HasMeta {
    fn meta() -> &'static ComponentMeta;
}

// ── STATE ENUMS POR DOMÍNIO ──────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum VisibilityState {
    #[default]
    Closed,
    Open,
}
impl VisibilityState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Open => "open", Self::Closed => "closed" }
    }
}
impl From<bool> for VisibilityState {
    fn from(open: bool) -> Self {
        if open { Self::Open } else { Self::Closed }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum ActivityState {
    #[default]
    Inactive,
    Active,
}
impl ActivityState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Active => "active", Self::Inactive => "inactive" }
    }
}
impl From<bool> for ActivityState {
    fn from(active: bool) -> Self {
        if active { Self::Active } else { Self::Inactive }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum SelectionState {
    #[default]
    Unselected,
    Selected,
}
impl SelectionState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Selected => "selected", Self::Unselected => "unselected" }
    }
}
impl From<bool> for SelectionState {
    fn from(selected: bool) -> Self {
        if selected { Self::Selected } else { Self::Unselected }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum ToggleState {
    #[default]
    Off,
    On,
}
impl ToggleState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::On => "on", Self::Off => "off" }
    }
}
impl From<bool> for ToggleState {
    fn from(pressed: bool) -> Self {
        if pressed { Self::On } else { Self::Off }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum NavigationState {
    #[default]
    Inactive,
    Current,
}
impl NavigationState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Current => "current", Self::Inactive => "inactive" }
    }
}
impl From<bool> for NavigationState {
    fn from(current: bool) -> Self {
        if current { Self::Current } else { Self::Inactive }
    }
}

// ── TO DATA ATTR TRAIT ───────────────────────────────────────────────────────

/// Centraliza a saída DOM de qualquer state enum.
/// Garante que data-rs-state sempre vem de um tipo, nunca de string literal.
pub trait ToDataAttr {
    fn to_data_attr(&self) -> (&'static str, &'static str);
}

impl ToDataAttr for VisibilityState {
    fn to_data_attr(&self) -> (&'static str, &'static str) {
        ("data-rs-state", self.as_str())
    }
}
impl ToDataAttr for ActivityState {
    fn to_data_attr(&self) -> (&'static str, &'static str) {
        ("data-rs-state", self.as_str())
    }
}
impl ToDataAttr for SelectionState {
    fn to_data_attr(&self) -> (&'static str, &'static str) {
        ("data-rs-state", self.as_str())
    }
}
impl ToDataAttr for ToggleState {
    fn to_data_attr(&self) -> (&'static str, &'static str) {
        ("data-rs-state", self.as_str())
    }
}
impl ToDataAttr for NavigationState {
    fn to_data_attr(&self) -> (&'static str, &'static str) {
        ("data-rs-state", self.as_str())
    }
}

// ── STATE KIND (unificador sem ambiguidade) ───────────────────────────────────

/// Wrapper unificado para passar qualquer state enum por referência comum.
/// Resolve ambiguidade sem colapsar domínios distintos num enum flat.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum StateKind {
    Visibility(VisibilityState),
    Activity(ActivityState),
    Selection(SelectionState),
    Toggle(ToggleState),
    Navigation(NavigationState),
}

impl StateKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Visibility(s)  => s.as_str(),
            Self::Activity(s)    => s.as_str(),
            Self::Selection(s)   => s.as_str(),
            Self::Toggle(s)      => s.as_str(),
            Self::Navigation(s)  => s.as_str(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum DisabledState {
    #[default]
    Enabled,
    Disabled,
}
impl DisabledState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Enabled => "enabled", Self::Disabled => "disabled" }
    }
    pub fn as_bool(&self) -> bool { *self == Self::Disabled }
    pub fn aria(&self) -> Option<&'static str> {
        if self.as_bool() { Some("true") } else { None }
    }
}
impl From<bool> for DisabledState {
    fn from(d: bool) -> Self { if d { Self::Disabled } else { Self::Enabled } }
}

// ── CAPABILITY → PROPS MAPPING ───────────────────────────────────────────────

/// Prop types that can be derived from capabilities declared in ComponentMeta.
/// These are the minimal props implied by a capability — not visual/structural props.
#[derive(Debug, Clone, PartialEq)]
pub struct CapabilityPropDef {
    pub key:     &'static str,
    pub label:   &'static str,
    pub kind:    CapabilityPropKind,
    pub default: Option<&'static str>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CapabilityPropKind {
    Bool,
    String,
    Enum(&'static [&'static str]),
}

/// Maps a single capability string to the props it implies.
/// Pure behaviors (focus-trap, keyboard-esc, aria-modal) → no props.
/// State-carrying capabilities (open-close, selected, active) → typed props.
/// Type-safe capability → props. Match direto no enum, sem strings.
pub fn capability_to_props_enum(cap: Capability) -> &'static [CapabilityPropDef] {
    match cap {
        Capability::OpenClose => &[
            CapabilityPropDef { key: "open",         label: "Open",         kind: CapabilityPropKind::Bool, default: Some("false") },
            CapabilityPropDef { key: "default-open", label: "Default Open", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Selected => &[
            CapabilityPropDef { key: "selected", label: "Selected", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Active => &[
            CapabilityPropDef { key: "active", label: "Active", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Pressed => &[
            CapabilityPropDef { key: "pressed", label: "Pressed", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Disabled => &[
            CapabilityPropDef { key: "disabled", label: "Disabled", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Loading => &[
            CapabilityPropDef { key: "loading", label: "Loading", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Value => &[
            CapabilityPropDef { key: "value", label: "Value", kind: CapabilityPropKind::String, default: None },
        ],
        Capability::Multiple => &[
            CapabilityPropDef { key: "multiple", label: "Multiple", kind: CapabilityPropKind::Bool, default: Some("false") },
        ],
        Capability::Orientation => &[
            CapabilityPropDef { key: "orientation", label: "Orientation", kind: CapabilityPropKind::Enum(&["horizontal", "vertical"]), default: Some("horizontal") },
        ],
        // Pure behaviors — no props derived
        Capability::FocusTrap | Capability::KeyboardEsc | Capability::AriaModal |
        Capability::KeyboardArrows | Capability::Roving | Capability::Typeahead |
        Capability::VirtualScroll | Capability::DragDrop | Capability::Resize |
        Capability::Overflow | Capability::Animation => &[],
    }
}

/// Deriva props a partir de slice de Capability enums (type-safe, sem strings).
pub fn derive_props_from_capabilities(caps: &[Capability]) -> Vec<CapabilityPropDef> {
    let mut seen = std::collections::HashSet::new();
    let mut result = Vec::new();
    for cap in caps {
        for prop in capability_to_props_enum(*cap) {
            if seen.insert(prop.key) {
                result.push(prop.clone());
            }
        }
    }
    result
}

/// Derives all implied props from a ComponentMeta's capabilities.
/// Deduplicates by key — first capability wins if two imply the same prop.
pub fn derive_props_from_meta(meta: &ComponentMeta) -> Vec<CapabilityPropDef> {
    derive_props_from_capabilities(meta.capabilities)
}

#[derive(Clone, Copy, PartialEq, Default, Debug)]
pub enum LoadingState {
    #[default]
    Idle,
    Loading,
}

impl LoadingState {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Idle    => "idle",
            Self::Loading => "loading",
        }
    }
}

#[derive(Clone, Copy, PartialEq, Default, Debug)]
pub enum ChartGridState {
    #[default]
    Visible,
    Hidden,
}
impl ChartGridState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Visible => "visible", Self::Hidden => "hidden" }
    }
}
impl From<bool> for ChartGridState {
    fn from(b: bool) -> Self { if b { Self::Visible } else { Self::Hidden } }
}

#[derive(Clone, Copy, PartialEq, Default, Debug)]
pub enum ChartLegendState {
    #[default]
    Visible,
    Hidden,
}
impl ChartLegendState {
    pub fn as_str(&self) -> &'static str {
        match self { Self::Visible => "visible", Self::Hidden => "hidden" }
    }
}
impl From<bool> for ChartLegendState {
    fn from(b: bool) -> Self { if b { Self::Visible } else { Self::Hidden } }
}
