// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PAGELAYOUT_API: ComponentApi = ComponentApi {
    id: "page-layout",
    props: &[
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("single"), description: "" },
        PropDef { name: "sidebar", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "content", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "aside", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

