// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PAGELAYOUT_API: ComponentApi = ComponentApi {
    id: "page-layout",
    description: "Flexible page layout with optional sidebar, main content and aside regions",
    props: &[
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("single"), description: "Visual variant of the component" },
        PropDef { name: "sidebar", kind: PropType::Children, required: false, default: None, description: "Sidebar region slot" },
        PropDef { name: "content", kind: PropType::Children, required: false, default: None, description: "Content region slot" },
        PropDef { name: "aside", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

