// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DROPDOWNMENU_API: ComponentApi = ComponentApi {
    id: "dropdown-menu",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "trigger_label", kind: PropType::String, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUTRIGGER_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-trigger",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUCONTENT_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-content",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUGROUP_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-group",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUITEM_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-item",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUCHECKBOXITEM_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-checkbox-item",
    description: "Dropdown menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "checked", kind: PropType::String, required: false, default: Some("off"), description: "Whether the component is checked" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DROPDOWNMENUSEPARATOR_API: ComponentApi = ComponentApi {
    id: "dropdown-menu-separator",
    description: "Dropdown menu",
    props: &[
    ],
};

