[package]
name = "canonrs-interactions-init"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CanonRS interactions initializer"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
web-sys = { workspace = true, features = [
  "Window", "Document", "Element", "HtmlElement",
  "EventTarget", "MouseEvent", "KeyboardEvent",
  "DomTokenList", "CssStyleDeclaration",
  "console", "Navigator", "Clipboard",
  "NodeList", "Node", "MutationObserver",
  "MutationObserverInit", "MutationRecord",
  "Location",
  "FocusEvent",
  "EventListener",
  "HtmlInputElement",
  "DomRect",
  "ScrollBehavior",
  "ScrollToOptions",
  "PointerEvent",
  "IntersectionObserver",
  "IntersectionObserverInit",
  "IntersectionObserverEntry",
] }
js-sys = { workspace = true }
wasm-bindgen-futures = { workspace = true }

canonrs-interactions-core = { version = "0.1.0",  path = "../canonrs-interactions-core" }

[profile.release]
opt-level = "s"
lto = true
