// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LOADINGOVERLAY_API: ComponentApi = ComponentApi {
    id: "loading-overlay",
    description: "Full loading overlay",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some(""), description: "Loading or visibility state" },
        PropDef { name: "mode", kind: PropType::String, required: false, default: Some(""), description: "Operational mode of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

