// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COPYBUTTON_API: ComponentApi = ComponentApi {
    id: "copy-button",
    description: "Clipboard copy button",
    props: &[
        PropDef { name: "text", kind: PropType::String, required: false, default: None, description: "Text to copy to clipboard" },
        PropDef { name: "target", kind: PropType::String, required: false, default: None, description: "Target element selector for copy" },
        PropDef { name: "reset_delay", kind: PropType::Number, required: false, default: Some("2000u32"), description: "Delay in ms before resetting copy state" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "Element id attribute" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some("Copy to clipboard"), description: "Accessible label for screen readers" },
    ],
};

