// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COPYBUTTON_API: ComponentApi = ComponentApi {
    id: "copy-button",
    props: &[
        PropDef { name: "text", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "target", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "reset_delay", kind: PropType::Number, required: false, default: Some("2000"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some("Copy to clipboard"), description: "" },
    ],
};

