use crate::design::tokens::FamilyToken;

/// FAMILY E — Feedback & Status
/// Components: Alert, AlertDialog, Callout, Badge, Toast, Banner, InlineNotice, EmptyState, ErrorState, StatusDot, Spinner, Progress, Skeleton
/// Scope: User feedback, status indicators, loading states (excludes: state tokens, z-index)

pub const FAMILY_E_FEEDBACK: &[FamilyToken] = &[
    // Feedback foundation
    FamilyToken::new("feedback-color", "var(--color-primary)"),
    FamilyToken::new("feedback-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("feedback-radius", "var(--radius-lg)"),

    // Alert
    FamilyToken::new("alert-bg", "var(--color-background)"),
    FamilyToken::new("alert-bg-default", "var(--color-muted)"),
    FamilyToken::new("alert-bg-info", "var(--semantic-info-bg)"),
    FamilyToken::new("alert-bg-success", "var(--semantic-success-bg)"),
    FamilyToken::new("alert-bg-warning", "var(--semantic-warning-bg)"),
    FamilyToken::new("alert-bg-error", "var(--semantic-error-bg)"),
    FamilyToken::new("alert-border-color", "var(--color-border)"),
    FamilyToken::new("alert-border-width", "1px"),
    FamilyToken::new("alert-padding-x", "var(--space-md)"),
    FamilyToken::new("alert-padding-y", "var(--space-sm)"),
    FamilyToken::new("alert-radius", "var(--radius-lg)"),
    FamilyToken::new("alert-title-fg", "var(--color-foreground)"),
    FamilyToken::new("alert-title-font-size", "var(--font-size-sm)"),
    FamilyToken::new("alert-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("alert-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("alert-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("alert-description-line-height", "var(--line-height-normal)"),
    FamilyToken::new("alert-close-fg", "var(--color-foreground)"),
    FamilyToken::new("alert-close-fg-hover", "var(--color-muted-foreground)"),
    FamilyToken::new("alert-close-size", "var(--space-md)"),

    // Alert Dialog
    FamilyToken::new("alert-dialog-overlay-bg", "rgba(0, 0, 0, 0.5)"),
    FamilyToken::new("alert-dialog-overlay-opacity", "0.5"),
    FamilyToken::new("alert-dialog-overlay-blur", "4px"),
    FamilyToken::new("alert-dialog-content-bg", "var(--color-background)"),
    FamilyToken::new("alert-dialog-content-width", "var(--layout-width-dialog)"),
    FamilyToken::new("alert-dialog-content-radius", "var(--radius-lg)"),
    FamilyToken::new("alert-dialog-content-padding", "var(--space-xl)"),
    FamilyToken::new("alert-dialog-content-shadow", "var(--shadow-2xl)"),
    FamilyToken::new("alert-dialog-header-gap", "var(--space-sm)"),
    FamilyToken::new("alert-dialog-header-padding", "0 0 var(--space-md) 0"),
    FamilyToken::new("alert-dialog-title-fg", "var(--color-foreground)"),
    FamilyToken::new("alert-dialog-title-font-size", "var(--font-size-lg)"),
    FamilyToken::new("alert-dialog-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("alert-dialog-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("alert-dialog-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("alert-dialog-description-line-height", "var(--line-height-relaxed)"),
    FamilyToken::new("alert-dialog-footer-gap", "var(--space-sm)"),
    FamilyToken::new("alert-dialog-footer-padding", "var(--space-md) 0 0 0"),
    FamilyToken::new("alert-dialog-action-gap", "var(--space-sm)"),
    FamilyToken::new("alert-dialog-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("alert-dialog-transition-ease", "var(--motion-ease-standard)"),

    // Callout
    FamilyToken::new("callout-gap", "var(--space-sm)"),
    FamilyToken::new("callout-padding-x", "var(--space-md)"),
    FamilyToken::new("callout-padding-y", "var(--space-sm)"),
    FamilyToken::new("callout-radius", "var(--radius-lg)"),
    FamilyToken::new("callout-border-width", "1px"),
    FamilyToken::new("callout-icon-size", "var(--font-size-xl)"),
    FamilyToken::new("callout-bg-default", "var(--color-muted)"),
    FamilyToken::new("callout-bg-info", "var(--semantic-info-bg)"),
    FamilyToken::new("callout-bg-success", "var(--semantic-success-bg)"),
    FamilyToken::new("callout-bg-warning", "var(--semantic-warning-bg)"),
    FamilyToken::new("callout-bg-error", "var(--semantic-error-bg)"),
    FamilyToken::new("callout-border-default", "var(--color-border)"),
    FamilyToken::new("callout-border-info", "var(--semantic-info-border)"),
    FamilyToken::new("callout-border-success", "var(--semantic-success-border)"),
    FamilyToken::new("callout-border-warning", "var(--semantic-warning-border)"),
    FamilyToken::new("callout-border-error", "var(--semantic-error-border)"),
    FamilyToken::new("callout-title-fg", "var(--color-foreground)"),
    FamilyToken::new("callout-title-font-size", "var(--font-size-sm)"),
    FamilyToken::new("callout-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("callout-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("callout-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("callout-description-line-height", "var(--line-height-normal)"),

    // Badge
    FamilyToken::new("badge-padding-x", "var(--space-sm)"),
    FamilyToken::new("badge-padding-y", "var(--space-xs)"),
    FamilyToken::new("badge-radius", "var(--radius-full)"),
    FamilyToken::new("badge-font-size", "var(--font-size-xs)"),
    FamilyToken::new("badge-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("badge-line-height", "var(--line-height-tight)"),
    FamilyToken::new("badge-bg-default", "var(--semantic-feedback-default-bg)"),
    FamilyToken::new("badge-bg-primary", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("badge-bg-success", "var(--semantic-success-bg)"),
    FamilyToken::new("badge-bg-warning", "var(--semantic-warning-bg)"),
    FamilyToken::new("badge-bg-error", "var(--semantic-error-bg)"),
    FamilyToken::new("badge-fg-default", "var(--semantic-feedback-default-fg)"),
    FamilyToken::new("badge-fg-primary", "var(--semantic-action-primary-fg)"),
    FamilyToken::new("badge-fg-success", "var(--semantic-success-fg)"),
    FamilyToken::new("badge-fg-warning", "var(--semantic-warning-fg)"),
    FamilyToken::new("badge-fg-error", "var(--semantic-error-fg)"),
    FamilyToken::new("badge-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("badge-transition-ease", "var(--motion-ease-standard)"),

    // Toast (has interactive version)
    FamilyToken::new("toast-bg", "var(--color-background)"),
    FamilyToken::new("toast-padding", "var(--space-md)"),
    FamilyToken::new("toast-radius", "var(--radius-lg)"),
    FamilyToken::new("toast-shadow", "var(--shadow-lg)"),
    FamilyToken::new("toast-gap", "var(--space-sm)"),
    FamilyToken::new("toast-border-color", "var(--color-border)"),
    FamilyToken::new("toast-border-width", "1px"),
    FamilyToken::new("toast-success-bg", "var(--semantic-success-bg)"),
    FamilyToken::new("toast-success-border", "var(--color-success)"),
    FamilyToken::new("toast-warning-bg", "var(--semantic-warning-bg)"),
    FamilyToken::new("toast-warning-border", "var(--color-warning)"),
    FamilyToken::new("toast-error-bg", "var(--semantic-error-bg)"),
    FamilyToken::new("toast-error-border", "var(--color-destructive)"),
    FamilyToken::new("toast-z-index", "var(--layer-toast)"),
    FamilyToken::new("toast-viewport-padding", "var(--space-md)"),
    FamilyToken::new("toast-viewport-gap", "var(--space-sm)"),
    FamilyToken::new("toast-viewport-max-width", "var(--layout-width-lg)"),
    FamilyToken::new("toast-title-fg", "var(--color-foreground)"),
    FamilyToken::new("toast-title-font-size", "var(--font-size-sm)"),
    FamilyToken::new("toast-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("toast-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("toast-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("toast-close-fg", "var(--color-foreground)"),
    FamilyToken::new("toast-close-size", "var(--space-md)"),

    // Banner (has interactive version)
    FamilyToken::new("banner-gap", "var(--space-sm)"),
    FamilyToken::new("banner-padding-x", "var(--space-md)"),
    FamilyToken::new("banner-padding-y", "var(--space-sm)"),
    FamilyToken::new("banner-radius", "0"),
    FamilyToken::new("banner-shadow", "var(--shadow-sm)"),
    FamilyToken::new("banner-border-color", "var(--color-border)"),
    FamilyToken::new("banner-border-width", "0 0 1px 0"),
    FamilyToken::new("banner-bg-info", "var(--semantic-info-surface)"),
    FamilyToken::new("banner-bg-success", "var(--semantic-success-bg)"),
    FamilyToken::new("banner-bg-warning", "var(--semantic-warning-bg)"),
    FamilyToken::new("banner-bg-error", "var(--semantic-error-bg)"),
    FamilyToken::new("banner-fg", "var(--color-foreground)"),
    FamilyToken::new("banner-content-fg", "var(--color-foreground)"),
    FamilyToken::new("banner-content-font-size", "var(--font-size-sm)"),
    FamilyToken::new("banner-close-fg", "var(--color-foreground)"),
    FamilyToken::new("banner-close-fg-hover", "var(--color-muted-foreground)"),
    FamilyToken::new("banner-close-size", "var(--space-md)"),
    FamilyToken::new("banner-actions-gap", "var(--space-sm)"),

    // Inline Notice
    FamilyToken::new("inline-notice-gap", "var(--space-sm)"),
    FamilyToken::new("inline-notice-padding-x", "var(--space-sm)"),
    FamilyToken::new("inline-notice-padding-y", "var(--space-sm)"),
    FamilyToken::new("inline-notice-radius", "var(--radius-md)"),
    FamilyToken::new("inline-notice-border-color", "var(--color-border)"),
    FamilyToken::new("inline-notice-border-width", "1px"),
    FamilyToken::new("inline-notice-bg-default", "var(--color-muted)"),
    FamilyToken::new("inline-notice-bg-info", "var(--semantic-info-surface)"),
    FamilyToken::new("inline-notice-bg-success", "var(--semantic-success-bg)"),
    FamilyToken::new("inline-notice-bg-warning", "var(--semantic-warning-bg)"),
    FamilyToken::new("inline-notice-bg-error", "var(--semantic-error-bg)"),
    FamilyToken::new("inline-notice-fg", "var(--color-foreground)"),
    FamilyToken::new("inline-notice-font-size", "var(--font-size-sm)"),
    FamilyToken::new("inline-notice-icon-size", "var(--space-md)"),

    // Empty State
    FamilyToken::new("empty-state-padding", "var(--space-xl)"),
    FamilyToken::new("empty-state-gap", "var(--space-md)"),
    FamilyToken::new("empty-state-icon-size", "var(--size-icon-lg)"),
    FamilyToken::new("empty-state-icon-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("empty-state-title-fg", "var(--color-foreground)"),
    FamilyToken::new("empty-state-title-font-size", "var(--font-size-lg)"),
    FamilyToken::new("empty-state-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("empty-state-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("empty-state-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("empty-state-actions-gap", "var(--space-sm)"),

    // Error State
    FamilyToken::new("error-state-padding", "var(--space-xl)"),
    FamilyToken::new("error-state-gap", "var(--space-md)"),
    FamilyToken::new("error-state-icon-size", "var(--size-icon-lg)"),
    FamilyToken::new("error-state-icon-fg", "var(--color-destructive)"),
    FamilyToken::new("error-state-title-fg", "var(--color-foreground)"),
    FamilyToken::new("error-state-title-font-size", "var(--font-size-lg)"),
    FamilyToken::new("error-state-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("error-state-description-fg", "var(--color-muted-foreground)"),
    FamilyToken::new("error-state-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("error-state-actions-gap", "var(--space-sm)"),

    // Status Dot
    FamilyToken::new("status-dot-size", "var(--space-sm)"),
    FamilyToken::new("status-dot-radius", "var(--radius-full)"),
    FamilyToken::new("status-dot-bg-default", "var(--color-muted)"),
    FamilyToken::new("status-dot-bg-success", "var(--color-success)"),
    FamilyToken::new("status-dot-bg-warning", "var(--color-warning)"),
    FamilyToken::new("status-dot-bg-error", "var(--color-destructive)"),
    FamilyToken::new("status-dot-bg-info", "var(--color-info)"),

    // Spinner
    FamilyToken::new("spinner-size", "var(--space-lg)"),
    FamilyToken::new("spinner-border-width", "2px"),
    FamilyToken::new("spinner-color", "var(--color-primary)"),
    FamilyToken::new("spinner-track-color", "var(--color-muted)"),
    FamilyToken::new("spinner-duration", "var(--motion-duration-slow)"),
    FamilyToken::new("spinner-ease", "var(--motion-ease-linear)"),

    // Progress
    FamilyToken::new("progress-height", "var(--space-sm)"),
    FamilyToken::new("progress-radius", "var(--radius-full)"),
    FamilyToken::new("progress-bg", "var(--color-muted)"),
    FamilyToken::new("progress-fill-bg", "var(--color-primary)"),
    FamilyToken::new("progress-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("progress-transition-ease", "var(--motion-ease-standard)"),

    // Skeleton
    FamilyToken::new("skeleton-bg", "var(--color-muted)"),
    FamilyToken::new("skeleton-radius", "var(--radius-md)"),
    FamilyToken::new("skeleton-pulse-duration", "var(--motion-duration-slow)"),
    FamilyToken::new("skeleton-pulse-ease", "var(--motion-ease-standard)"),
    // Loading Overlay
    FamilyToken::new("loading-overlay-bg", "rgba(0, 0, 0, 0.5)"),
    FamilyToken::new("loading-overlay-spinner-size", "var(--space-2xl)"),

    // Pulse
    FamilyToken::new("pulse-bg", "var(--color-muted)"),
    FamilyToken::new("pulse-duration", "2s"),

];
