// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const INLINEMETA_API: ComponentApi = ComponentApi {
    id: "inline-meta",
    description: "Inline metadata display for stats, versions, dates and counts",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const INLINEMETALABEL_API: ComponentApi = ComponentApi {
    id: "inline-meta-label",
    description: "Inline metadata display for stats, versions, dates and counts",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const INLINEMETAVALUE_API: ComponentApi = ComponentApi {
    id: "inline-meta-value",
    description: "Inline metadata display for stats, versions, dates and counts",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

