// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const KBD_API: ComponentApi = ComponentApi {
    id: "kbd",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("md"), description: "" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const KBDGROUP_API: ComponentApi = ComponentApi {
    id: "kbd-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const KBDSEPARATOR_API: ComponentApi = ComponentApi {
    id: "kbd-separator",
    props: &[
    ],
};

