// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const KBD_API: ComponentApi = ComponentApi {
    id: "kbd",
    description: "Keyboard shortcut display",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("md"), description: "Size variant of the component" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const KBDGROUP_API: ComponentApi = ComponentApi {
    id: "kbd-group",
    description: "Keyboard shortcut display",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const KBDSEPARATOR_API: ComponentApi = ComponentApi {
    id: "kbd-separator",
    description: "Keyboard shortcut display",
    props: &[
    ],
};

