// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SKELETON_API: ComponentApi = ComponentApi {
    id: "skeleton",
    props: &[
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("rectangle"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

