// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DIALOG_API: ComponentApi = ComponentApi {
    id: "dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGTRIGGER_API: ComponentApi = ComponentApi {
    id: "dialog-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGPORTAL_API: ComponentApi = ComponentApi {
    id: "dialog-portal",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const DIALOGOVERLAY_API: ComponentApi = ComponentApi {
    id: "dialog-overlay",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGCONTENT_API: ComponentApi = ComponentApi {
    id: "dialog-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGTITLE_API: ComponentApi = ComponentApi {
    id: "dialog-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "dialog-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const DIALOGCLOSE_API: ComponentApi = ComponentApi {
    id: "dialog-close",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

