// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DIALOG_API: ComponentApi = ComponentApi {
    id: "dialog",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "uid", kind: PropType::String, required: false, default: Some(""), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGTRIGGER_API: ComponentApi = ComponentApi {
    id: "dialog-trigger",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "target", kind: PropType::String, required: false, default: Some(""), description: "Target element selector for copy" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGPORTAL_API: ComponentApi = ComponentApi {
    id: "dialog-portal",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const DIALOGCONTENT_API: ComponentApi = ComponentApi {
    id: "dialog-content",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGTITLE_API: ComponentApi = ComponentApi {
    id: "dialog-title",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "dialog-description",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGCLOSE_API: ComponentApi = ComponentApi {
    id: "dialog-close",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const DIALOGFOOTER_API: ComponentApi = ComponentApi {
    id: "dialog-footer",
    description: "Modal dialog component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

