// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const EMPTYTABLE_API: ComponentApi = ComponentApi {
    id: "empty-table",
    description: "Empty table state display",
    props: &[
        PropDef { name: "title", kind: PropType::String, required: false, default: Some("No data available"), description: "Title slot or text" },
        PropDef { name: "description", kind: PropType::String, required: false, default: Some("Add your first item to get started"), description: "Description slot or text" },
        PropDef { name: "colspan", kind: PropType::Number, required: false, default: Some("999u32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

