// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CONTEXTMENU_API: ComponentApi = ComponentApi {
    id: "context-menu",
    description: "Right-click context menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONTEXTMENUTRIGGER_API: ComponentApi = ComponentApi {
    id: "context-menu-trigger",
    description: "Right-click context menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const CONTEXTMENUITEM_API: ComponentApi = ComponentApi {
    id: "context-menu-item",
    description: "Right-click context menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

