// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const POPOVERBLOCK_API: ComponentApi = ComponentApi {
    id: "popover-block",
    props: &[
        PropDef { name: "placement", kind: PropType::String, required: false, default: Some("bottom"), description: "" },
        PropDef { name: "trigger", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "header", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "footer", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "content", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

