[package]
name = "canonrs-interactions"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CanonRS interactions — aggregator crate"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "Element", "NodeList", "Node", "MutationObserver", "MutationObserverInit", "MutationRecord"] }
canonrs-interactions-core      = { version = "0.1.0",  path = "../canonrs-interactions-core" }
canonrs-interactions-init      = { version = "0.1.0",  path = "../canonrs-interactions-init" }
canonrs-interactions-nav       = { version = "0.1.0",  path = "../canonrs-interactions-nav" }
canonrs-interactions-data      = { version = "0.1.0",  path = "../canonrs-interactions-data" }
canonrs-interactions-gesture   = { version = "0.1.0",  path = "../canonrs-interactions-gesture" }
canonrs-interactions-overlay   = { version = "0.1.0",  path = "../canonrs-interactions-overlay" }
canonrs-interactions-selection = { version = "0.1.0",  path = "../canonrs-interactions-selection" }
canonrs-interactions-content   = { version = "0.1.0",  path = "../canonrs-interactions-content" }


