[package]
name = "canonrs-interactions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = ["Window", "Document", "Element", "NodeList", "Node", "MutationObserver", "MutationObserverInit", "MutationRecord"] }
canonrs-interactions-core      = { path = "../canonrs-interactions-core" }
canonrs-interactions-init      = { path = "../canonrs-interactions-init" }
canonrs-interactions-nav       = { path = "../canonrs-interactions-nav" }
canonrs-interactions-data      = { path = "../canonrs-interactions-data" }
canonrs-interactions-gesture   = { path = "../canonrs-interactions-gesture" }
canonrs-interactions-overlay   = { path = "../canonrs-interactions-overlay" }
canonrs-interactions-selection = { path = "../canonrs-interactions-selection" }
canonrs-interactions-content   = { path = "../canonrs-interactions-content" }


