// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DRAWER_API: ComponentApi = ComponentApi {
    id: "drawer",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "open", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const DRAWEROVERLAY_API: ComponentApi = ComponentApi {
    id: "drawer-overlay",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const DRAWERCONTENT_API: ComponentApi = ComponentApi {
    id: "drawer-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_labelledby", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "aria_describedby", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

