// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DRAWER_API: ComponentApi = ComponentApi {
    id: "drawer",
    description: "Slide-out drawer component",
    props: &[
        PropDef { name: "trigger_label", kind: PropType::String, required: false, default: Some("Open"), description: "Prop value" },
        PropDef { name: "close_label", kind: PropType::String, required: false, default: Some("Close"), description: "Prop value" },
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "Title slot or text" },
        PropDef { name: "description", kind: PropType::String, required: false, default: None, description: "Description slot or text" },
        PropDef { name: "side", kind: PropType::Enum(&["right", "left", "top", "bottom"]), required: false, default: Some("right"), description: "Tooltip or popover side" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

