// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const INPUTGROUP_API: ComponentApi = ComponentApi {
    id: "input-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "merge_radius", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

