// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TREE_API: ComponentApi = ComponentApi {
    id: "tree",
    description: "Tree view component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const TREEITEM_API: ComponentApi = ComponentApi {
    id: "tree-item",
    description: "Tree view component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "has_children", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "depth", kind: PropType::String, required: false, default: Some("0u8"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const TREEGROUP_API: ComponentApi = ComponentApi {
    id: "tree-group",
    description: "Tree view component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

