// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ICON_API: ComponentApi = ComponentApi {
    id: "icon",
    props: &[
        PropDef { name: "size", kind: PropType::Enum(&["sm", "md", "lg"]), required: false, default: Some("md"), description: "" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "muted", "primary", "destructive", "success", "warning"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "spin", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

