// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const RADIO_API: ComponentApi = ComponentApi {
    id: "radio",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selected", kind: PropType::String, required: false, default: Some("unselected"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const RADIOGROUP_API: ComponentApi = ComponentApi {
    id: "radio-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const RADIOGROUPITEM_API: ComponentApi = ComponentApi {
    id: "radio-group-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selected", kind: PropType::String, required: false, default: Some("unselected"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

