// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SELECT_API: ComponentApi = ComponentApi {
    id: "select",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "node_ref", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SELECTTRIGGER_API: ComponentApi = ComponentApi {
    id: "select-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SELECTVALUE_API: ComponentApi = ComponentApi {
    id: "select-value",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "placeholder", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SELECTCONTENT_API: ComponentApi = ComponentApi {
    id: "select-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SELECTITEM_API: ComponentApi = ComponentApi {
    id: "select-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selected", kind: PropType::String, required: false, default: Some("unselected"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SELECTSEPARATOR_API: ComponentApi = ComponentApi {
    id: "select-separator",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

