// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const VIRTUALLIST_API: ComponentApi = ComponentApi {
    id: "virtual-list",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "items_count", kind: PropType::Number, required: true, default: None, description: "" },
        PropDef { name: "item_height", kind: PropType::Number, required: true, default: None, description: "" },
    ],
};

