// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const VIRTUALLIST_API: ComponentApi = ComponentApi {
    id: "virtual-list",
    description: "Virtualized list for large datasets",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "items_count", kind: PropType::Number, required: true, default: None, description: "Prop value" },
        PropDef { name: "item_height", kind: PropType::Number, required: false, default: Some("40.0f64"), description: "Prop value" },
        PropDef { name: "height", kind: PropType::Number, required: false, default: Some("400u32"), description: "Prop value" },
    ],
};

