// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PAGINATION_API: ComponentApi = ComponentApi {
    id: "pagination",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONCONTENT_API: ComponentApi = ComponentApi {
    id: "pagination-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONITEM_API: ComponentApi = ComponentApi {
    id: "pagination-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONLINK_API: ComponentApi = ComponentApi {
    id: "pagination-link",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONPREVIOUS_API: ComponentApi = ComponentApi {
    id: "pagination-previous",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONNEXT_API: ComponentApi = ComponentApi {
    id: "pagination-next",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const PAGINATIONELLIPSIS_API: ComponentApi = ComponentApi {
    id: "pagination-ellipsis",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

