// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOAST_API: ComponentApi = ComponentApi {
    id: "toast",
    description: "Toast notification message",
    props: &[
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "Title slot or text" },
        PropDef { name: "description", kind: PropType::String, required: false, default: None, description: "Description slot or text" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "duration_ms", kind: PropType::Number, required: false, default: Some("5000u32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const TOASTVIEWPORT_API: ComponentApi = ComponentApi {
    id: "toast-viewport",
    description: "Toast notification message",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

