// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{EmptyStateVariant}; 

pub const EMPTYSTATE_API: ComponentApi = ComponentApi {
    id: "empty-state",
    description: "Empty state placeholder",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const EMPTYSTATEICON_API: ComponentApi = ComponentApi {
    id: "empty-state-icon",
    description: "Empty state placeholder",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const EMPTYSTATETITLE_API: ComponentApi = ComponentApi {
    id: "empty-state-title",
    description: "Empty state placeholder",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const EMPTYSTATEDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "empty-state-description",
    description: "Empty state placeholder",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const EMPTYSTATEACTION_API: ComponentApi = ComponentApi {
    id: "empty-state-action",
    description: "Empty state placeholder",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

