// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const MARKDOWNSURFACE_API: ComponentApi = ComponentApi {
    id: "markdown-surface",
    props: &[
        PropDef { name: "rendered", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "show_toc", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "show_toolbar", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "toc_position", kind: PropType::Enum(&["top", "sidebar"]), required: false, default: Some("top"), description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

