// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COLORPICKER_API: ComponentApi = ComponentApi {
    id: "color-picker",
    description: "Color picker input",
    props: &[
        PropDef { name: "value", kind: PropType::String, required: false, default: Some("#000000"), description: "Current value" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "Form field name" },
        PropDef { name: "disabled", kind: PropType::Enum(&["enabled", "disabled"]), required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const COLORPICKERSWATCH_API: ComponentApi = ComponentApi {
    id: "color-picker-swatch",
    description: "Color picker input",
    props: &[
        PropDef { name: "color", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "selected", kind: PropType::Enum(&["unselected", "selected"]), required: false, default: Some("unselected"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const COLORPICKERDISPLAY_API: ComponentApi = ComponentApi {
    id: "color-picker-display",
    description: "Color picker input",
    props: &[
        PropDef { name: "value", kind: PropType::String, required: false, default: Some("#3b82f6"), description: "Current value" },
        PropDef { name: "format", kind: PropType::String, required: false, default: Some("hex"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const COLORPICKERSWATCHES_API: ComponentApi = ComponentApi {
    id: "color-picker-swatches",
    description: "Color picker input",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some("#3b82f6"), description: "Current value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

