// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COLORPICKER_API: ComponentApi = ComponentApi {
    id: "color-picker",
    props: &[
        PropDef { name: "value", kind: PropType::String, required: false, default: Some("#000000"), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const COLORPICKERSWATCH_API: ComponentApi = ComponentApi {
    id: "color-picker-swatch",
    props: &[
        PropDef { name: "color", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "selected", kind: PropType::String, required: false, default: Some("unselected"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

