use crate::design::tokens::FamilyToken;

/// Overlay infrastructure tokens — shared foundation for all overlay components
/// Scope: z-index, backdrop, transitions, dialog, drawer, sheet, dropdown

pub const OVERLAY_TOKENS: &[FamilyToken] = &[
    // Overlay foundation
    FamilyToken::new("overlay-z-index",            "var(--layer-overlay)"),
    FamilyToken::new("overlay-backdrop-bg",         "var(--color-overlay-50)"),
    FamilyToken::new("overlay-backdrop-blur",       "4px"),
    FamilyToken::new("overlay-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("overlay-transition-ease",     "var(--motion-ease-standard)"),

    // Dialog
    FamilyToken::new("dialog-overlay-bg",               "var(--color-overlay-50)"),
    FamilyToken::new("dialog-overlay-z-index",          "var(--layer-overlay)"),
    FamilyToken::new("dialog-content-bg",               "var(--theme-surface-bg)"),
    FamilyToken::new("dialog-content-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-content-width",            "var(--layout-width-lg)"),
    FamilyToken::new("dialog-content-max-width",        "90vw"),
    FamilyToken::new("dialog-content-padding",          "var(--space-lg)"),
    FamilyToken::new("dialog-content-radius",           "var(--radius-md)"),
    FamilyToken::new("dialog-content-shadow",           "var(--shadow-2xl)"),
    FamilyToken::new("dialog-header-gap",               "var(--space-sm)"),
    FamilyToken::new("dialog-footer-gap",               "var(--space-sm)"),
    FamilyToken::new("dialog-title-fg",                 "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-title-font-size",          "var(--font-size-lg)"),
    FamilyToken::new("dialog-title-font-weight",        "var(--font-weight-semibold)"),
    FamilyToken::new("dialog-description-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("dialog-description-font-size",    "var(--font-size-sm)"),
    FamilyToken::new("dialog-close-fg",                 "var(--theme-surface-fg-muted)"),
    FamilyToken::new("dialog-close-fg-hover",           "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-transition-duration",      "var(--motion-duration-normal)"),

    // Drawer
    FamilyToken::new("drawer-overlay-bg",            "var(--color-overlay-50)"),
    FamilyToken::new("drawer-overlay-z-index",       "var(--layer-overlay)"),
    FamilyToken::new("drawer-bg",                    "var(--theme-surface-bg)"),
    FamilyToken::new("drawer-fg",                    "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-width",                 "var(--layout-width-md)"),
    FamilyToken::new("drawer-height",                "40vh"),
    FamilyToken::new("drawer-padding",               "var(--space-lg)"),
    FamilyToken::new("drawer-shadow",                "var(--shadow-2xl)"),
    FamilyToken::new("drawer-header-gap",            "var(--space-sm)"),
    FamilyToken::new("drawer-footer-gap",            "var(--space-sm)"),
    FamilyToken::new("drawer-title-fg",              "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-title-font-size",       "var(--font-size-lg)"),
    FamilyToken::new("drawer-title-font-weight",     "var(--font-weight-semibold)"),
    FamilyToken::new("drawer-description-fg",        "var(--theme-surface-fg-muted)"),
    FamilyToken::new("drawer-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("drawer-close-fg",              "var(--theme-surface-fg-muted)"),
    FamilyToken::new("drawer-close-fg-hover",        "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-transition-duration",   "var(--motion-duration-normal)"),
    FamilyToken::new("drawer-transition-ease",       "var(--motion-ease-standard)"),

    // Sheet
    FamilyToken::new("sheet-overlay-bg",             "var(--color-overlay-50)"),
    FamilyToken::new("sheet-overlay-z-index",        "var(--layer-overlay)"),
    FamilyToken::new("sheet-bg",                     "var(--theme-surface-bg)"),
    FamilyToken::new("sheet-fg",                     "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-width",                  "var(--layout-width-md)"),
    FamilyToken::new("sheet-height",                 "40vh"),
    FamilyToken::new("sheet-padding",                "var(--space-lg)"),
    FamilyToken::new("sheet-shadow",                 "var(--shadow-2xl)"),
    FamilyToken::new("sheet-header-gap",             "var(--space-sm)"),
    FamilyToken::new("sheet-footer-gap",             "var(--space-sm)"),
    FamilyToken::new("sheet-title-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-title-font-size",        "var(--font-size-lg)"),
    FamilyToken::new("sheet-title-font-weight",      "var(--font-weight-semibold)"),
    FamilyToken::new("sheet-description-fg",         "var(--theme-surface-fg-muted)"),
    FamilyToken::new("sheet-description-font-size",  "var(--font-size-sm)"),
    FamilyToken::new("sheet-close-fg",               "var(--theme-surface-fg-muted)"),
    FamilyToken::new("sheet-close-fg-hover",         "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-transition-duration",    "var(--motion-duration-normal)"),
    FamilyToken::new("sheet-transition-ease",        "var(--motion-ease-standard)"),

    // DropdownMenu
    FamilyToken::new("dropdown-menu-bg",                    "var(--theme-overlay-bg)"),
    FamilyToken::new("dropdown-menu-fg",                    "var(--theme-surface-fg)"),
    FamilyToken::new("dropdown-menu-radius",                "var(--radius-md)"),
    FamilyToken::new("dropdown-menu-shadow",                "var(--shadow-lg)"),
    FamilyToken::new("dropdown-menu-border-color",          "var(--theme-surface-border)"),
    FamilyToken::new("dropdown-menu-border-width",          "1px"),
    FamilyToken::new("dropdown-menu-min-width",             "var(--layout-width-sm)"),
    FamilyToken::new("dropdown-menu-z-index",               "var(--layer-overlay)"),
    FamilyToken::new("dropdown-menu-padding",               "var(--space-xs)"),
    FamilyToken::new("dropdown-menu-item-height",           "var(--space-xl)"),
    FamilyToken::new("dropdown-menu-item-padding",          "var(--space-sm)"),
    FamilyToken::new("dropdown-menu-item-hover-bg",         "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-hover-fg",         "var(--theme-action-accent-fg)"),
    FamilyToken::new("dropdown-menu-item-selected-bg",      "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-checked-bg",       "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-checked-fg",       "var(--theme-action-accent-fg)"),
    FamilyToken::new("dropdown-menu-separator-color",       "var(--theme-surface-border)"),
    FamilyToken::new("dropdown-menu-separator-margin-y",    "var(--space-xs)"),
    FamilyToken::new("dropdown-menu-transition-duration",   "var(--motion-duration-fast)"),
    FamilyToken::new("dropdown-menu-transition-ease",       "var(--motion-ease-standard)"),
];
