//! Component tokens — Overlay
//! Dialog, Drawer, Sheet, Popover, HoverCard, Tooltip, ConfirmDialog, Modal, DropdownMenu

use crate::design::tokens::FamilyToken;

pub const OVERLAY_TOKENS: &[FamilyToken] = &[
    // Overlay foundation
    FamilyToken::new("overlay-z-index",            "var(--layer-overlay)"),
    FamilyToken::new("overlay-backdrop-bg",        "var(--color-overlay-50)"),
    FamilyToken::new("overlay-backdrop-blur",      "var(--blur-sm)"),
    FamilyToken::new("overlay-transition-duration","var(--motion-duration-normal)"),
    FamilyToken::new("overlay-transition-ease",    "var(--motion-ease-standard)"),

    // Dialog
    FamilyToken::new("dialog-overlay-bg",               "var(--color-overlay-50)"),
    FamilyToken::new("dialog-overlay-z-index",          "var(--layer-overlay)"),
    FamilyToken::new("dialog-content-bg",               "var(--theme-surface-bg)"),
    FamilyToken::new("dialog-content-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-content-width",            "var(--layout-width-lg)"),
    FamilyToken::new("dialog-content-max-width",        "90vw"),
    FamilyToken::new("dialog-content-padding",          "var(--space-lg)"),
    FamilyToken::new("dialog-content-radius",           "var(--radius-md)"),
    FamilyToken::new("dialog-content-shadow",           "var(--shadow-2xl)"),
    FamilyToken::new("dialog-header-gap",               "var(--space-sm)"),
    FamilyToken::new("dialog-footer-gap",               "var(--space-sm)"),
    FamilyToken::new("dialog-title-fg",                 "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-title-font-size",          "var(--font-size-lg)"),
    FamilyToken::new("dialog-title-font-weight",        "var(--font-weight-semibold)"),
    FamilyToken::new("dialog-description-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("dialog-description-font-size",    "var(--font-size-sm)"),
    FamilyToken::new("dialog-close-fg",                 "var(--theme-surface-fg-muted)"),
    FamilyToken::new("dialog-close-hover-fg",           "var(--theme-surface-fg)"),
    FamilyToken::new("dialog-transition-duration",      "var(--motion-duration-normal)"),

    // Popover
    FamilyToken::new("popover-bg",                   "var(--theme-surface-bg)"),
    FamilyToken::new("popover-fg",                   "var(--theme-surface-fg)"),
    FamilyToken::new("popover-border-color",         "var(--theme-surface-border)"),
    FamilyToken::new("popover-border-width",         "var(--border-thin)"),
    FamilyToken::new("popover-radius",               "var(--radius-md)"),
    FamilyToken::new("popover-shadow",               "var(--shadow-lg)"),
    FamilyToken::new("popover-padding",              "var(--space-md)"),
    FamilyToken::new("popover-width",                "var(--size-3xl)"),
    FamilyToken::new("popover-z-index",              "var(--layer-overlay)"),
    FamilyToken::new("popover-transition-duration",  "var(--motion-duration-fast)"),
    FamilyToken::new("popover-transition-ease",      "var(--motion-ease-standard)"),

    // HoverCard
    FamilyToken::new("hover-card-bg",                  "var(--theme-surface-bg)"),
    FamilyToken::new("hover-card-fg",                  "var(--theme-surface-fg)"),
    FamilyToken::new("hover-card-border-color",        "var(--theme-surface-border)"),
    FamilyToken::new("hover-card-border-width",        "var(--border-thin)"),
    FamilyToken::new("hover-card-radius",              "var(--radius-md)"),
    FamilyToken::new("hover-card-shadow",              "var(--shadow-lg)"),
    FamilyToken::new("hover-card-padding",             "var(--space-md)"),
    FamilyToken::new("hover-card-width",               "var(--size-3xl)"),
    FamilyToken::new("hover-card-z-index",             "var(--layer-overlay)"),
    FamilyToken::new("hover-card-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("hover-card-transition-ease",     "var(--motion-ease-standard)"),

    // Tooltip
    FamilyToken::new("tooltip-bg",                  "var(--theme-surface-fg)"),
    FamilyToken::new("tooltip-fg",                  "var(--theme-surface-bg)"),
    FamilyToken::new("tooltip-padding",             "var(--space-xs) var(--space-sm)"),
    FamilyToken::new("tooltip-radius",              "var(--radius-sm)"),
    FamilyToken::new("tooltip-font-size",           "var(--font-size-xs)"),
    FamilyToken::new("tooltip-font-weight",         "var(--font-weight-medium)"),
    FamilyToken::new("tooltip-shadow",              "var(--shadow-md)"),
    FamilyToken::new("tooltip-z-index",             "var(--layer-tooltip)"),
    FamilyToken::new("tooltip-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("tooltip-transition-ease",     "var(--motion-ease-standard)"),
    FamilyToken::new("tooltip-max-width",           "var(--size-3xl)"),
    FamilyToken::new("tooltip-offset",              "var(--space-xs)"),
    FamilyToken::new("tooltip-arrow-size",           "var(--space-sm)"),

    // ConfirmDialog
    FamilyToken::new("confirm-dialog-overlay-bg",            "var(--color-overlay-50)"),
    FamilyToken::new("confirm-dialog-overlay-z-index",       "var(--layer-overlay)"),
    FamilyToken::new("confirm-dialog-content-bg",            "var(--theme-surface-bg)"),
    FamilyToken::new("confirm-dialog-content-fg",            "var(--theme-surface-fg)"),
    FamilyToken::new("confirm-dialog-content-width",         "28rem"),
    FamilyToken::new("confirm-dialog-content-max-width",     "90vw"),
    FamilyToken::new("confirm-dialog-content-padding",       "var(--space-lg)"),
    FamilyToken::new("confirm-dialog-content-radius",        "var(--radius-md)"),
    FamilyToken::new("confirm-dialog-content-shadow",        "var(--shadow-2xl)"),
    FamilyToken::new("confirm-dialog-title-fg",              "var(--theme-surface-fg)"),
    FamilyToken::new("confirm-dialog-title-font-size",       "var(--font-size-lg)"),
    FamilyToken::new("confirm-dialog-title-font-weight",     "var(--font-weight-semibold)"),
    FamilyToken::new("confirm-dialog-description-fg",        "var(--theme-surface-fg-muted)"),
    FamilyToken::new("confirm-dialog-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("confirm-dialog-footer-gap",            "var(--space-sm)"),
    FamilyToken::new("confirm-dialog-header-gap",            "var(--space-sm)"),
    FamilyToken::new("confirm-dialog-transition-duration",   "var(--motion-duration-normal)"),
    FamilyToken::new("confirm-dialog-transition-ease",       "var(--motion-ease-standard)"),

    // Modal
    FamilyToken::new("modal-overlay-bg",             "var(--color-overlay-50)"),
    FamilyToken::new("modal-overlay-z-index",        "var(--layer-overlay)"),
    FamilyToken::new("modal-content-bg",             "var(--theme-surface-bg)"),
    FamilyToken::new("modal-content-fg",             "var(--theme-surface-fg)"),
    FamilyToken::new("modal-content-width",          "var(--layout-width-lg)"),
    FamilyToken::new("modal-content-max-width",      "90vw"),
    FamilyToken::new("modal-content-padding",        "var(--space-lg)"),
    FamilyToken::new("modal-content-radius",         "var(--radius-lg)"),
    FamilyToken::new("modal-content-shadow",         "var(--shadow-2xl)"),
    FamilyToken::new("modal-title-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("modal-title-font-size",        "var(--font-size-lg)"),
    FamilyToken::new("modal-title-font-weight",      "var(--font-weight-semibold)"),
    FamilyToken::new("modal-header-gap",             "var(--space-sm)"),
    FamilyToken::new("modal-footer-gap",             "var(--space-sm)"),
    FamilyToken::new("modal-description-fg",         "var(--theme-surface-fg-muted)"),
    FamilyToken::new("modal-description-font-size",  "var(--font-size-sm)"),
    FamilyToken::new("modal-transition-duration",    "var(--motion-duration-normal)"),
    FamilyToken::new("modal-transition-ease",        "var(--motion-ease-standard)"),

    // Drawer
    FamilyToken::new("drawer-overlay-bg",            "var(--color-overlay-50)"),
    FamilyToken::new("drawer-overlay-z-index",       "var(--layer-overlay)"),
    FamilyToken::new("drawer-bg",                    "var(--theme-surface-bg)"),
    FamilyToken::new("drawer-fg",                    "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-width",                 "var(--layout-width-md)"),
    FamilyToken::new("drawer-height",                "40vh"),
    FamilyToken::new("drawer-padding",               "var(--space-lg)"),
    FamilyToken::new("drawer-shadow",                "var(--shadow-2xl)"),
    FamilyToken::new("drawer-header-gap",            "var(--space-sm)"),
    FamilyToken::new("drawer-footer-gap",            "var(--space-sm)"),
    FamilyToken::new("drawer-title-fg",              "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-title-font-size",       "var(--font-size-lg)"),
    FamilyToken::new("drawer-title-font-weight",     "var(--font-weight-semibold)"),
    FamilyToken::new("drawer-description-fg",        "var(--theme-surface-fg-muted)"),
    FamilyToken::new("drawer-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("drawer-close-fg",              "var(--theme-surface-fg-muted)"),
    FamilyToken::new("drawer-close-hover-fg",        "var(--theme-surface-fg)"),
    FamilyToken::new("drawer-transition-duration",   "var(--motion-duration-normal)"),
    FamilyToken::new("drawer-transition-ease",       "var(--motion-ease-standard)"),
    FamilyToken::new("drawer-transform-open",          "translateX(0)"),
    FamilyToken::new("drawer-transform-closed-right",  "translateX(100%)"),
    FamilyToken::new("drawer-transform-closed-left",   "translateX(-100%)"),
    FamilyToken::new("drawer-transform-closed-top",    "translateY(-100%)"),
    FamilyToken::new("drawer-transform-closed-bottom", "translateY(100%)"),

    // Sheet
    FamilyToken::new("sheet-overlay-bg",              "var(--color-overlay-50)"),
    FamilyToken::new("sheet-overlay-z-index",         "var(--layer-overlay)"),
    FamilyToken::new("sheet-bg",                      "var(--theme-surface-bg)"),
    FamilyToken::new("sheet-fg",                      "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-width",                   "var(--layout-width-md)"),
    FamilyToken::new("sheet-height",                  "40vh"),
    FamilyToken::new("sheet-padding",                 "var(--space-lg)"),
    FamilyToken::new("sheet-shadow",                  "var(--shadow-2xl)"),
    FamilyToken::new("sheet-header-gap",              "var(--space-sm)"),
    FamilyToken::new("sheet-footer-gap",              "var(--space-sm)"),
    FamilyToken::new("sheet-title-fg",                "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-title-font-size",         "var(--font-size-lg)"),
    FamilyToken::new("sheet-title-font-weight",       "var(--font-weight-semibold)"),
    FamilyToken::new("sheet-description-fg",          "var(--theme-surface-fg-muted)"),
    FamilyToken::new("sheet-description-font-size",   "var(--font-size-sm)"),
    FamilyToken::new("sheet-close-fg",                "var(--theme-surface-fg-muted)"),
    FamilyToken::new("sheet-close-hover-fg",          "var(--theme-surface-fg)"),
    FamilyToken::new("sheet-transition-duration",     "var(--motion-duration-normal)"),
    FamilyToken::new("sheet-transition-ease",         "var(--motion-ease-standard)"),
    FamilyToken::new("sheet-transform-closed-right",  "translateX(100%)"),
    FamilyToken::new("sheet-transform-closed-left",   "translateX(-100%)"),
    FamilyToken::new("sheet-transform-closed-top",    "translateY(-100%)"),
    FamilyToken::new("sheet-transform-closed-bottom", "translateY(100%)"),
    FamilyToken::new("sheet-transform-open",          "translateX(0) translateY(0)"),

    // DropdownMenu
    FamilyToken::new("dropdown-menu-bg",                  "var(--theme-overlay-bg)"),
    FamilyToken::new("dropdown-menu-fg",                  "var(--theme-surface-fg)"),
    FamilyToken::new("dropdown-menu-radius",              "var(--radius-md)"),
    FamilyToken::new("dropdown-menu-shadow",              "var(--shadow-lg)"),
    FamilyToken::new("dropdown-menu-border-color",        "var(--theme-surface-border)"),
    FamilyToken::new("dropdown-menu-border-width",        "var(--border-thin)"),
    FamilyToken::new("dropdown-menu-min-width",           "var(--layout-width-sm)"),
    FamilyToken::new("dropdown-menu-z-index",             "var(--layer-dropdown)"),
    FamilyToken::new("dropdown-menu-padding-y",           "var(--space-xs)"),
    FamilyToken::new("dropdown-menu-item-height",         "var(--space-xl)"),
    FamilyToken::new("dropdown-menu-item-padding",        "var(--space-sm)"),
    FamilyToken::new("dropdown-menu-item-hover-bg",       "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-hover-fg",       "var(--theme-action-accent-fg)"),
    FamilyToken::new("dropdown-menu-item-selected-bg",    "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-checked-bg",     "var(--theme-action-accent-bg)"),
    FamilyToken::new("dropdown-menu-item-checked-fg",     "var(--theme-action-accent-fg)"),
    FamilyToken::new("dropdown-menu-separator-color",     "var(--theme-surface-border)"),
    FamilyToken::new("dropdown-menu-separator-margin-y",  "var(--space-xs)"),
    FamilyToken::new("dropdown-menu-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("dropdown-menu-transition-ease",     "var(--motion-ease-standard)"),
];
