//! Component tokens — Selection
//! Accordion, Collapsible, Combobox, ContextMenu, Menu, Menubar, Tree, Command, Checkbox, Radio, Tabs

use crate::design::tokens::FamilyToken;

pub const SELECTION_TOKENS: &[FamilyToken] = &[
    // Selection foundation
    FamilyToken::new("selection-color",   "var(--theme-action-primary-bg)"),
    FamilyToken::new("selection-spacing", "var(--space-sm)"),

    // Checkbox
    FamilyToken::new("checkbox-size",                 "var(--space-lg)"),
    FamilyToken::new("checkbox-radius",               "var(--radius-sm)"),
    FamilyToken::new("checkbox-bg",                   "var(--theme-surface-bg)"),
    FamilyToken::new("checkbox-checked-fg",           "var(--theme-action-primary-fg)"),
    FamilyToken::new("checkbox-border-color",         "var(--theme-surface-border)"),
    FamilyToken::new("checkbox-border-width",         "var(--border-thin)"),
    FamilyToken::new("checkbox-checked-border-color", "var(--theme-action-primary-bg)"),
    FamilyToken::new("checkbox-checked-bg",           "var(--theme-action-primary-bg)"),
    FamilyToken::new("checkbox-gap",                  "var(--space-sm)"),
    FamilyToken::new("checkbox-transition-duration",  "var(--motion-duration-fast)"),
    FamilyToken::new("checkbox-disabled-opacity",     "var(--opacity-disabled)"),
    FamilyToken::new("checkbox-focus-ring-width",     "var(--focus-ring-width)"),
    FamilyToken::new("checkbox-focus-ring-color",     "var(--theme-action-focus-ring)"),

    // Radio
    FamilyToken::new("radio-size",                    "var(--space-lg)"),
    FamilyToken::new("radio-bg",                      "var(--theme-surface-bg)"),
    FamilyToken::new("radio-border-color",            "var(--theme-surface-border)"),
    FamilyToken::new("radio-border-width",            "var(--border-thin)"),
    FamilyToken::new("radio-checked-border-color",    "var(--theme-action-primary-bg)"),
    FamilyToken::new("radio-dot-size",                "var(--space-sm)"),
    FamilyToken::new("radio-dot-color",               "var(--theme-action-primary-fg)"),
    FamilyToken::new("radio-checked-dot-color",       "var(--theme-action-primary-fg)"),
    FamilyToken::new("radio-disabled-dot-color",      "var(--theme-surface-fg-muted)"),
    FamilyToken::new("radio-checked-bg",              "var(--theme-action-primary-bg)"),
    FamilyToken::new("radio-disabled-bg",             "var(--theme-surface-muted)"),
    FamilyToken::new("radio-disabled-border-color",   "var(--theme-surface-border)"),
    FamilyToken::new("radio-hover-border-color",      "var(--theme-action-primary-bg)"),
    FamilyToken::new("radio-disabled-fg",             "var(--theme-surface-fg-muted)"),
    FamilyToken::new("radio-bg-disabled",              "var(--theme-surface-muted)"),
    FamilyToken::new("radio-border-color-disabled",    "var(--theme-surface-border)"),
    FamilyToken::new("radio-dot-color-disabled",       "var(--theme-surface-fg-muted)"),
    FamilyToken::new("radio-focus-ring-shadow",        "0 0 0 var(--focus-ring-width) var(--theme-action-focus-ring)"),
    FamilyToken::new("radio-group-gap",               "var(--space-sm)"),
    FamilyToken::new("radio-group-item-gap",          "var(--space-xs)"),
    FamilyToken::new("radio-group-label-font-size",   "var(--font-size-sm)"),
    FamilyToken::new("radio-transition-duration",     "var(--motion-duration-fast)"),
    FamilyToken::new("radio-disabled-opacity",        "var(--opacity-disabled)"),
    FamilyToken::new("radio-focus-ring-width",        "var(--focus-ring-width)"),
    FamilyToken::new("radio-focus-ring-color",        "var(--theme-action-focus-ring)"),

    // Tabs
    FamilyToken::new("tabs-gap",                           "var(--space-xs)"),
    FamilyToken::new("tabs-list-bg",                       "var(--theme-surface-muted)"),
    FamilyToken::new("tabs-list-padding",                  "var(--space-xs)"),
    FamilyToken::new("tabs-list-radius",                   "var(--radius-md)"),
    FamilyToken::new("tabs-list-gap",                      "var(--space-xs)"),
    FamilyToken::new("tabs-trigger-padding-x",             "var(--space-md)"),
    FamilyToken::new("tabs-trigger-padding-y",             "var(--space-sm)"),
    FamilyToken::new("tabs-trigger-radius",                "var(--radius-sm)"),
    FamilyToken::new("tabs-trigger-fg",                    "var(--theme-surface-fg-muted)"),
    FamilyToken::new("tabs-trigger-font-size",             "var(--font-size-sm)"),
    FamilyToken::new("tabs-trigger-font-weight",           "var(--font-weight-medium)"),
    FamilyToken::new("tabs-trigger-transition-duration",   "var(--motion-duration-fast)"),
    FamilyToken::new("tabs-trigger-active-fg",             "var(--theme-action-primary-fg)"),
    FamilyToken::new("tabs-trigger-active-bg",             "var(--theme-action-primary-bg)"),
    FamilyToken::new("tabs-trigger-hover-bg",              "var(--theme-surface-muted)"),
    FamilyToken::new("tabs-trigger-hover-fg",              "var(--theme-surface-fg)"),
    FamilyToken::new("tabs-trigger-disabled-opacity",      "var(--opacity-disabled)"),
    FamilyToken::new("tabs-trigger-focus-ring-color",      "var(--theme-action-focus-ring)"),
    FamilyToken::new("tabs-trigger-focus-ring-width",      "var(--focus-ring-width)"),
    FamilyToken::new("tabs-trigger-focus-ring-offset",     "var(--focus-ring-offset)"),
    FamilyToken::new("tabs-content-padding",               "var(--space-md)"),

    // Accordion
    FamilyToken::new("accordion-gap",                             "var(--space-sm)"),
    FamilyToken::new("accordion-item-border-width",               "var(--border-thin)"),
    FamilyToken::new("accordion-item-border-color",               "var(--theme-surface-border)"),
    FamilyToken::new("accordion-item-border-color-active",        "var(--theme-action-primary-bg)"),
    FamilyToken::new("accordion-item-border-radius",              "var(--radius-md)"),
    FamilyToken::new("accordion-trigger-bg",                      "transparent"),
    FamilyToken::new("accordion-trigger-fg",                      "var(--theme-surface-fg)"),
    FamilyToken::new("accordion-trigger-padding-x",               "var(--space-md)"),
    FamilyToken::new("accordion-trigger-padding-y",               "var(--space-sm)"),
    FamilyToken::new("accordion-trigger-font-weight",             "var(--font-weight-medium)"),
    FamilyToken::new("accordion-trigger-transition-duration",     "var(--motion-duration-fast)"),
    FamilyToken::new("accordion-trigger-transition-ease",         "var(--motion-ease-standard)"),
    FamilyToken::new("accordion-trigger-hover-bg",                "var(--theme-surface-muted)"),
    FamilyToken::new("accordion-trigger-open-fg",                 "var(--theme-action-primary-bg)"),
    FamilyToken::new("accordion-trigger-open-bg",                 "var(--theme-surface-muted)"),
    FamilyToken::new("accordion-trigger-disabled-fg",             "var(--theme-surface-fg-muted)"),
    FamilyToken::new("accordion-trigger-disabled-opacity",        "var(--opacity-disabled)"),
    FamilyToken::new("accordion-trigger-fg-disabled",             "var(--theme-surface-fg-muted)"),
    FamilyToken::new("accordion-trigger-opacity-disabled",        "var(--opacity-disabled)"),
    FamilyToken::new("accordion-content-padding-top",             "var(--space-sm)"),
    FamilyToken::new("accordion-content-padding-x",               "var(--space-md)"),
    FamilyToken::new("accordion-content-padding-y",               "var(--space-sm)"),
    FamilyToken::new("accordion-icon-size",                       "var(--space-md)"),
    FamilyToken::new("accordion-icon-rotation",                   "var(--motion-rotate-open)"),

    // Collapsible
    FamilyToken::new("collapsible-gap",                    "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-bg",             "transparent"),
    FamilyToken::new("collapsible-trigger-fg",             "var(--theme-surface-fg)"),
    FamilyToken::new("collapsible-trigger-padding",        "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-radius",         "var(--radius-sm)"),
    FamilyToken::new("collapsible-trigger-hover-bg",       "var(--theme-surface-muted)"),
    FamilyToken::new("collapsible-trigger-open-fg",        "var(--theme-action-primary-bg)"),
    FamilyToken::new("collapsible-content-padding",        "var(--space-sm)"),
    FamilyToken::new("collapsible-transition-duration",    "var(--motion-duration-normal)"),
    FamilyToken::new("collapsible-transition-ease",        "var(--motion-ease-standard)"),

    // Combobox
    FamilyToken::new("combobox-bg",                    "var(--theme-surface-bg)"),
    FamilyToken::new("combobox-fg",                    "var(--theme-surface-fg)"),
    FamilyToken::new("combobox-border-color",          "var(--theme-surface-border)"),
    FamilyToken::new("combobox-border-width",          "var(--border-thin)"),
    FamilyToken::new("combobox-height",                "var(--space-2xl)"),
    FamilyToken::new("combobox-padding-x",             "var(--space-sm)"),
    FamilyToken::new("combobox-radius",                "var(--radius-sm)"),
    FamilyToken::new("combobox-gap",                   "var(--space-sm)"),
    FamilyToken::new("combobox-disabled-opacity",      "var(--opacity-disabled)"),
    FamilyToken::new("combobox-focus-ring-width",      "var(--focus-ring-width)"),
    FamilyToken::new("combobox-focus-ring-color",      "var(--theme-action-focus-ring)"),
    FamilyToken::new("combobox-popover-bg",            "var(--theme-overlay-bg)"),
    FamilyToken::new("combobox-popover-padding-y",     "var(--space-xs)"),
    FamilyToken::new("combobox-popover-radius",        "var(--radius-md)"),
    FamilyToken::new("combobox-popover-shadow",        "var(--shadow-lg)"),
    FamilyToken::new("combobox-item-height",           "var(--space-xl)"),
    FamilyToken::new("combobox-item-padding",          "var(--space-sm)"),
    FamilyToken::new("combobox-item-hover-bg",         "var(--theme-action-accent-bg)"),
    FamilyToken::new("combobox-item-selected-bg",      "var(--theme-action-accent-bg)"),
    FamilyToken::new("combobox-empty-fg",              "var(--theme-surface-fg-muted)"),
    FamilyToken::new("combobox-empty-padding",         "var(--space-sm)"),

    // ContextMenu
    FamilyToken::new("context-menu-bg",                    "var(--theme-overlay-bg)"),
    FamilyToken::new("context-menu-fg",                    "var(--theme-surface-fg)"),
    FamilyToken::new("context-menu-padding",               "var(--space-xs)"),
    FamilyToken::new("context-menu-radius",                "var(--radius-md)"),
    FamilyToken::new("context-menu-shadow",                "var(--shadow-lg)"),
    FamilyToken::new("context-menu-border-color",          "var(--theme-surface-border)"),
    FamilyToken::new("context-menu-border-width",          "var(--border-thin)"),
    FamilyToken::new("context-menu-min-width",             "var(--layout-width-sm)"),
    FamilyToken::new("context-menu-z-index",               "var(--layer-overlay)"),
    FamilyToken::new("context-menu-item-height",           "var(--space-xl)"),
    FamilyToken::new("context-menu-item-padding",          "var(--space-sm)"),
    FamilyToken::new("context-menu-item-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("context-menu-item-hover-bg",         "var(--theme-action-accent-bg)"),
    FamilyToken::new("context-menu-separator-color",       "var(--theme-surface-border)"),
    FamilyToken::new("context-menu-separator-margin-y",    "var(--space-xs)"),
    FamilyToken::new("context-menu-label-fg",              "var(--theme-surface-fg-muted)"),
    FamilyToken::new("context-menu-label-font-size",       "var(--font-size-xs)"),
    FamilyToken::new("context-menu-label-padding",         "var(--space-sm)"),
    FamilyToken::new("context-menu-shortcut-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("context-menu-shortcut-font-size",    "var(--font-size-xs)"),
    FamilyToken::new("context-menu-transition-duration",   "var(--motion-duration-fast)"),
    FamilyToken::new("context-menu-transition-ease",       "var(--motion-ease-standard)"),
    FamilyToken::new("context-menu-x",                     "0px"),
    FamilyToken::new("context-menu-y",                     "0px"),

    // Menu
    FamilyToken::new("menu-bg",                        "var(--theme-surface-bg)"),
    FamilyToken::new("menu-padding",                   "var(--space-sm)"),
    FamilyToken::new("menu-gap",                       "var(--space-xs)"),
    FamilyToken::new("menu-item-bg",                   "transparent"),
    FamilyToken::new("menu-item-height",               "var(--space-2xl)"),
    FamilyToken::new("menu-item-padding",              "var(--space-sm)"),
    FamilyToken::new("menu-item-radius",               "var(--radius-sm)"),
    FamilyToken::new("menu-item-fg",                   "var(--theme-surface-fg)"),
    FamilyToken::new("menu-item-font-size",            "var(--font-size-sm)"),
    FamilyToken::new("menu-item-hover-bg",             "var(--theme-surface-muted)"),
    FamilyToken::new("menu-item-active-bg",            "var(--theme-action-accent-bg)"),
    FamilyToken::new("menu-item-active-fg",            "var(--theme-action-accent-fg)"),
    FamilyToken::new("menu-item-transition-duration",  "var(--motion-duration-fast)"),
    FamilyToken::new("menu-item-transition-ease",      "var(--motion-ease-standard)"),
    FamilyToken::new("menu-separator-margin",          "var(--space-xs) 0"),

    // Menubar
    FamilyToken::new("menubar-bg",                       "var(--theme-surface-bg)"),
    FamilyToken::new("menubar-border-color",             "var(--theme-surface-border)"),
    FamilyToken::new("menubar-border-width",             "0 0 var(--border-thin) 0"),
    FamilyToken::new("menubar-padding",                  "var(--space-sm)"),
    FamilyToken::new("menubar-gap",                      "var(--space-xs)"),
    FamilyToken::new("menubar-radius",                   "var(--radius-md)"),
    FamilyToken::new("menubar-trigger-padding",          "var(--space-sm)"),
    FamilyToken::new("menubar-trigger-radius",           "var(--radius-sm)"),
    FamilyToken::new("menubar-trigger-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("menubar-trigger-hover-bg",         "var(--theme-surface-muted)"),
    FamilyToken::new("menubar-trigger-expanded-bg",      "var(--theme-action-accent-bg)"),
    FamilyToken::new("menubar-trigger-expanded-fg",      "var(--theme-action-accent-fg)"),
    FamilyToken::new("menubar-subitem-bg-hover",         "var(--theme-surface-muted)"),
    FamilyToken::new("menubar-content-bg",               "var(--theme-overlay-bg)"),
    FamilyToken::new("menubar-content-padding-y",        "var(--space-xs)"),
    FamilyToken::new("menubar-content-radius",           "var(--radius-md)"),
    FamilyToken::new("menubar-content-shadow",           "var(--shadow-lg)"),
    FamilyToken::new("menubar-content-min-width",        "var(--layout-width-sm)"),
    FamilyToken::new("menubar-subitem-height",           "var(--space-xl)"),
    FamilyToken::new("menubar-subitem-padding",          "var(--space-sm) var(--space-md)"),
    FamilyToken::new("menubar-subitem-fg",               "var(--theme-surface-fg)"),
    FamilyToken::new("menubar-subitem-radius",           "var(--radius-sm)"),
    FamilyToken::new("menubar-subitem-hover-bg",         "var(--theme-action-accent-bg)"),
    FamilyToken::new("menubar-subitem-transition",       "var(--motion-duration-fast)"),
    FamilyToken::new("menubar-separator-height",         "var(--border-thin)"),
    FamilyToken::new("menubar-separator-bg",             "var(--theme-surface-border)"),
    FamilyToken::new("menubar-separator-margin",         "var(--space-xs) 0"),
    FamilyToken::new("menubar-transition-duration",      "var(--motion-duration-fast)"),
    FamilyToken::new("menubar-transition-ease",          "var(--motion-ease-standard)"),

    // Tree
    FamilyToken::new("tree-gap",                         "var(--space-2xs)"),
    FamilyToken::new("tree-indent",                      "var(--space-md)"),
    FamilyToken::new("tree-item-height",                 "var(--space-xl)"),
    FamilyToken::new("tree-item-padding-x",              "var(--space-sm)"),
    FamilyToken::new("tree-item-padding-y",              "var(--space-2xs)"),
    FamilyToken::new("tree-item-radius",                 "var(--radius-sm)"),
    FamilyToken::new("tree-item-fg",                     "var(--theme-surface-fg)"),
    FamilyToken::new("tree-item-fg-muted",               "var(--theme-surface-fg-muted)"),
    FamilyToken::new("tree-item-font-size",              "var(--font-size-sm)"),
    FamilyToken::new("tree-item-font-weight-parent",     "var(--font-weight-medium)"),
    FamilyToken::new("tree-item-font-weight-leaf",       "var(--font-weight-normal)"),
    FamilyToken::new("tree-item-hover-bg",               "var(--theme-action-secondary-bg)"),
    FamilyToken::new("tree-item-selected-bg",            "var(--theme-action-accent-bg)"),
    FamilyToken::new("tree-item-active-bg",              "var(--theme-action-primary-bg)"),
    FamilyToken::new("tree-item-focus-bg",               "var(--theme-surface-muted)"),
    FamilyToken::new("tree-item-active-indicator",       "var(--theme-action-primary-bg)"),
    FamilyToken::new("tree-icon-size",                   "var(--space-md)"),
    FamilyToken::new("tree-icon-rotation",               "90deg"),
    FamilyToken::new("tree-indent-depth-1",              "var(--space-lg)"),
    FamilyToken::new("tree-indent-depth-2",              "var(--space-xl)"),
    FamilyToken::new("tree-guide-color",                 "var(--theme-surface-border)"),
    FamilyToken::new("tree-transition-duration",         "var(--motion-duration-fast)"),
    FamilyToken::new("tree-transition-ease",             "var(--motion-ease-standard)"),

    // Command
    FamilyToken::new("command-bg",                         "var(--theme-overlay-bg)"),
    FamilyToken::new("command-fg",                         "var(--theme-surface-fg)"),
    FamilyToken::new("command-radius",                     "var(--radius-md)"),
    FamilyToken::new("command-shadow",                     "var(--shadow-2xl)"),
    FamilyToken::new("command-border-color",               "var(--theme-surface-border)"),
    FamilyToken::new("command-border-width",               "var(--border-thin)"),
    FamilyToken::new("command-padding",                    "var(--space-xs)"),
    FamilyToken::new("command-gap",                        "var(--space-xs)"),
    FamilyToken::new("command-input-height",               "var(--space-2xl)"),
    FamilyToken::new("command-input-padding",              "var(--space-sm) var(--space-md)"),
    FamilyToken::new("command-input-font-size",            "var(--font-size-sm)"),
    FamilyToken::new("command-input-border-bottom",        "var(--border-thin) solid var(--theme-surface-border)"),
    FamilyToken::new("command-list-padding",               "var(--space-sm)"),
    FamilyToken::new("command-list-max-height",            "var(--layout-width-md)"),
    FamilyToken::new("command-item-height",                "var(--space-2xl)"),
    FamilyToken::new("command-item-padding",               "var(--space-sm)"),
    FamilyToken::new("command-item-radius",                "var(--radius-sm)"),
    FamilyToken::new("command-item-hover-bg",              "var(--theme-action-accent-bg)"),
    FamilyToken::new("command-item-selected-bg",           "var(--theme-action-accent-bg)"),
    FamilyToken::new("command-item-active-bg",             "var(--theme-action-accent-bg)"),
    FamilyToken::new("command-item-active-fg",             "var(--theme-action-accent-fg)"),
    FamilyToken::new("command-group-heading-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("command-group-heading-font-size",    "var(--font-size-xs)"),
    FamilyToken::new("command-group-heading-padding",      "var(--space-sm)"),
    FamilyToken::new("command-separator-color",            "var(--theme-surface-border)"),
    FamilyToken::new("command-separator-margin-y",         "var(--space-xs)"),
    FamilyToken::new("command-empty-fg",                   "var(--theme-surface-fg-muted)"),
    FamilyToken::new("command-empty-padding",              "var(--space-xl) var(--space-md)"),
];
