// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LIST_API: ComponentApi = ComponentApi {
    id: "list",
    props: &[
        PropDef { name: "list_type", kind: PropType::String, required: false, default: Some("unordered"), description: "" },
        PropDef { name: "header", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "footer", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "items", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

