// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LIST_API: ComponentApi = ComponentApi {
    id: "list",
    description: "Single list item with title and description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selection_mode", kind: PropType::String, required: false, default: Some("none"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const LISTITEM_API: ComponentApi = ComponentApi {
    id: "list-item",
    description: "Single list item with title and description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selected", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const LISTITEMTITLE_API: ComponentApi = ComponentApi {
    id: "list-item-title",
    description: "Single list item with title and description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const LISTITEMDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "list-item-description",
    description: "Single list item with title and description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

