// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LIST_API: ComponentApi = ComponentApi {
    id: "list",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selection_mode", kind: PropType::String, required: false, default: Some("none"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const LISTITEM_API: ComponentApi = ComponentApi {
    id: "list-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "selected", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

pub const LISTITEMTITLE_API: ComponentApi = ComponentApi {
    id: "list-item-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const LISTITEMDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "list-item-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

