pub struct PrimitiveToken {
    pub name: &'static str,
    pub value: &'static str,
}

pub const PRIMITIVE_VALUES: &[PrimitiveToken] = &[
    PrimitiveToken { name: "primitive-neutral-950", value: "220 16% 11%" },
    PrimitiveToken { name: "primitive-neutral-900", value: "217 32% 17%" },
    PrimitiveToken { name: "primitive-neutral-800", value: "215 25% 27%" },
    PrimitiveToken { name: "primitive-neutral-700", value: "217 19% 35%" },
    PrimitiveToken { name: "primitive-neutral-600", value: "215 14% 48%" },
    PrimitiveToken { name: "primitive-neutral-500", value: "220 9% 60%" },
    PrimitiveToken { name: "primitive-neutral-400", value: "218 11% 73%" },
    PrimitiveToken { name: "primitive-neutral-300", value: "216 12% 84%" },
    PrimitiveToken { name: "primitive-neutral-200", value: "220 13% 91%" },
    PrimitiveToken { name: "primitive-neutral-100", value: "220 14% 96%" },
    PrimitiveToken { name: "primitive-neutral-50", value: "210 20% 98%" },
    PrimitiveToken { name: "primitive-white", value: "0 0% 100%" },
    PrimitiveToken { name: "primitive-black", value: "0 0% 0%" },
    PrimitiveToken { name: "primitive-amber-500", value: "38 92% 50%" },
    PrimitiveToken { name: "primitive-amber-600", value: "32 95% 44%" },
    PrimitiveToken { name: "primitive-red-500", value: "0 84% 60%" },
    PrimitiveToken { name: "primitive-red-600", value: "0 72% 51%" },
    PrimitiveToken { name: "primitive-green-50", value: "138 76% 97%" },
    PrimitiveToken { name: "primitive-green-100", value: "141 84% 93%" },
    PrimitiveToken { name: "primitive-green-200", value: "141 79% 85%" },
    PrimitiveToken { name: "primitive-green-300", value: "142 77% 73%" },
    PrimitiveToken { name: "primitive-green-400", value: "142 69% 58%" },
    PrimitiveToken { name: "primitive-green-500", value: "142 71% 45%" },
    PrimitiveToken { name: "primitive-green-600", value: "142 76% 36%" },
    PrimitiveToken { name: "primitive-green-700", value: "142 72% 29%" },
    PrimitiveToken { name: "primitive-green-800", value: "143 64% 24%" },
    PrimitiveToken { name: "primitive-green-900", value: "144 61% 20%" },
    PrimitiveToken { name: "primitive-green-950", value: "145 80% 11%" },
    PrimitiveToken { name: "primitive-space-0", value: "0" },
    PrimitiveToken { name: "primitive-space-px", value: "1px" },
    PrimitiveToken { name: "primitive-space-0-5", value: "0.125rem" },
    PrimitiveToken { name: "primitive-space-1", value: "0.25rem" },
    PrimitiveToken { name: "primitive-space-1-5", value: "0.375rem" },
    PrimitiveToken { name: "primitive-space-2", value: "0.5rem" },
    PrimitiveToken { name: "primitive-space-2-5", value: "0.625rem" },
    PrimitiveToken { name: "primitive-space-3", value: "0.75rem" },
    PrimitiveToken { name: "primitive-space-3-5", value: "0.875rem" },
    PrimitiveToken { name: "primitive-space-4", value: "1rem" },
    PrimitiveToken { name: "primitive-space-5", value: "1.25rem" },
    PrimitiveToken { name: "primitive-space-6", value: "1.5rem" },
    PrimitiveToken { name: "primitive-space-7", value: "1.75rem" },
    PrimitiveToken { name: "primitive-space-8", value: "2rem" },
    PrimitiveToken { name: "primitive-space-9", value: "2.25rem" },
    PrimitiveToken { name: "primitive-space-10", value: "2.5rem" },
    PrimitiveToken { name: "primitive-space-11", value: "2.75rem" },
    PrimitiveToken { name: "primitive-space-12", value: "3rem" },
    PrimitiveToken { name: "primitive-space-14", value: "3.5rem" },
    PrimitiveToken { name: "primitive-space-16", value: "4rem" },
    PrimitiveToken { name: "primitive-space-20", value: "5rem" },
    PrimitiveToken { name: "primitive-space-24", value: "6rem" },
    PrimitiveToken { name: "primitive-space-xs", value: "0.25rem" },
    PrimitiveToken { name: "primitive-space-sm", value: "0.5rem" },
    PrimitiveToken { name: "primitive-space-md", value: "1rem" },
    PrimitiveToken { name: "primitive-space-lg", value: "1.5rem" },
    PrimitiveToken { name: "primitive-space-xl", value: "2rem" },
    PrimitiveToken { name: "primitive-space-2xl", value: "2.5rem" },
    PrimitiveToken { name: "primitive-space-3xl", value: "3rem" },
    PrimitiveToken { name: "primitive-radius-none", value: "0" },
    PrimitiveToken { name: "primitive-radius-sm", value: "0.25rem" },
    PrimitiveToken { name: "primitive-radius-md", value: "0.375rem" },
    PrimitiveToken { name: "primitive-radius-lg", value: "0.5rem" },
    PrimitiveToken { name: "primitive-radius-xl", value: "0.75rem" },
    PrimitiveToken { name: "primitive-radius-2xl", value: "1rem" },
    PrimitiveToken { name: "primitive-radius-3xl", value: "1.5rem" },
    PrimitiveToken { name: "primitive-radius-full", value: "9999px" },
    PrimitiveToken { name: "primitive-shadow-xs", value: "0 1px 2px 0 rgb(0 0 0 / 0.05)" },
    PrimitiveToken { name: "primitive-shadow-sm", value: "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)" },
    PrimitiveToken { name: "primitive-shadow-md", value: "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)" },
    PrimitiveToken { name: "primitive-shadow-lg", value: "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)" },
    PrimitiveToken { name: "primitive-shadow-xl", value: "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)" },
    PrimitiveToken { name: "primitive-shadow-2xl", value: "0 25px 50px -12px rgb(0 0 0 / 0.25)" },
    PrimitiveToken { name: "primitive-font-sans", value: "ui-sans-serif, system-ui, sans-serif" },
    PrimitiveToken { name: "primitive-font-serif", value: "ui-serif, Georgia, Cambria, serif" },
    PrimitiveToken { name: "primitive-font-mono", value: "ui-monospace, 'Cascadia Code', 'Source Code Pro', Menlo, monospace" },
    PrimitiveToken { name: "primitive-font-size-xs", value: "0.75rem" },
    PrimitiveToken { name: "primitive-font-size-sm", value: "0.875rem" },
    PrimitiveToken { name: "primitive-font-size-md", value: "1rem" },
    PrimitiveToken { name: "primitive-font-size-lg", value: "1.125rem" },
    PrimitiveToken { name: "primitive-font-size-xl", value: "1.25rem" },
    PrimitiveToken { name: "primitive-font-size-2xl", value: "1.5rem" },
    PrimitiveToken { name: "primitive-font-size-3xl", value: "1.875rem" },
    PrimitiveToken { name: "primitive-font-size-4xl", value: "2.25rem" },
    PrimitiveToken { name: "primitive-font-size-5xl", value: "3rem" },
    PrimitiveToken { name: "primitive-font-size-6xl", value: "3.75rem" },
    PrimitiveToken { name: "primitive-font-size-7xl", value: "4.5rem" },
    PrimitiveToken { name: "primitive-font-weight-thin", value: "100" },
    PrimitiveToken { name: "primitive-font-weight-extralight", value: "200" },
    PrimitiveToken { name: "primitive-font-weight-light", value: "300" },
    PrimitiveToken { name: "primitive-font-weight-normal", value: "400" },
    PrimitiveToken { name: "primitive-font-weight-medium", value: "500" },
    PrimitiveToken { name: "primitive-font-weight-semibold", value: "600" },
    PrimitiveToken { name: "primitive-font-weight-bold", value: "700" },
    PrimitiveToken { name: "primitive-font-weight-extrabold", value: "800" },
    PrimitiveToken { name: "primitive-font-weight-black", value: "900" },
    PrimitiveToken { name: "primitive-line-height-none", value: "1" },
    PrimitiveToken { name: "primitive-line-height-tight", value: "1.25" },
    PrimitiveToken { name: "primitive-line-height-snug", value: "1.375" },
    PrimitiveToken { name: "primitive-line-height-normal", value: "1.5" },
    PrimitiveToken { name: "primitive-line-height-relaxed", value: "1.625" },
    PrimitiveToken { name: "primitive-line-height-loose", value: "2" },
    PrimitiveToken { name: "primitive-letter-spacing-tighter", value: "-0.05em" },
    PrimitiveToken { name: "primitive-letter-spacing-tight", value: "-0.025em" },
    PrimitiveToken { name: "primitive-letter-spacing-normal", value: "0" },
    PrimitiveToken { name: "primitive-letter-spacing-wide", value: "0.025em" },
    PrimitiveToken { name: "primitive-letter-spacing-wider", value: "0.05em" },
    PrimitiveToken { name: "primitive-letter-spacing-widest", value: "0.1em" },
    PrimitiveToken { name: "primitive-motion-duration-instant", value: "0ms" },
    PrimitiveToken { name: "primitive-motion-duration-fast", value: "100ms" },
    PrimitiveToken { name: "primitive-motion-duration-normal", value: "200ms" },
    PrimitiveToken { name: "primitive-motion-duration-slow", value: "300ms" },
    PrimitiveToken { name: "primitive-motion-duration-slower", value: "400ms" },
    PrimitiveToken { name: "primitive-motion-duration-slowest", value: "500ms" },
    PrimitiveToken { name: "primitive-motion-ease-linear", value: "linear" },
    PrimitiveToken { name: "primitive-motion-ease-in", value: "cubic-bezier(0.4, 0, 1, 1)" },
    PrimitiveToken { name: "primitive-motion-ease-out", value: "cubic-bezier(0, 0, 0.2, 1)" },
    PrimitiveToken { name: "primitive-motion-ease-in-out", value: "cubic-bezier(0.4, 0, 0.2, 1)" },
    PrimitiveToken { name: "primitive-motion-ease-emphasized", value: "cubic-bezier(0.2, 0, 0, 1)" },
    PrimitiveToken { name: "primitive-motion-ease-bounce", value: "cubic-bezier(0.68, -0.55, 0.265, 1.55)" },
    PrimitiveToken { name: "primitive-z-base", value: "0" },
    PrimitiveToken { name: "primitive-z-dropdown", value: "1000" },
    PrimitiveToken { name: "primitive-z-sticky", value: "1100" },
    PrimitiveToken { name: "primitive-z-fixed", value: "1200" },
    PrimitiveToken { name: "primitive-z-overlay", value: "1300" },
    PrimitiveToken { name: "primitive-z-modal", value: "1400" },
    PrimitiveToken { name: "primitive-z-popover", value: "1500" },
    PrimitiveToken { name: "primitive-z-tooltip", value: "1600" },
    PrimitiveToken { name: "primitive-opacity-0", value: "0" },
    PrimitiveToken { name: "primitive-opacity-5", value: "0.05" },
    PrimitiveToken { name: "primitive-opacity-10", value: "0.1" },
    PrimitiveToken { name: "primitive-opacity-20", value: "0.2" },
    PrimitiveToken { name: "primitive-opacity-30", value: "0.3" },
    PrimitiveToken { name: "primitive-opacity-40", value: "0.4" },
    PrimitiveToken { name: "primitive-opacity-50", value: "0.5" },
    PrimitiveToken { name: "primitive-opacity-60", value: "0.6" },
    PrimitiveToken { name: "primitive-opacity-70", value: "0.7" },
    PrimitiveToken { name: "primitive-opacity-80", value: "0.8" },
    PrimitiveToken { name: "primitive-opacity-90", value: "0.9" },
    PrimitiveToken { name: "primitive-opacity-95", value: "0.95" },
    PrimitiveToken { name: "primitive-opacity-100", value: "1" },
    PrimitiveToken { name: "primitive-opacity-hover", value: "0.9" },
    PrimitiveToken { name: "primitive-opacity-disabled", value: "0.5" },
    PrimitiveToken { name: "primitive-border-width", value: "1px" },
    PrimitiveToken { name: "primitive-font-size-base", value: "1rem" },
    PrimitiveToken { name: "primitive-icon-size-sm", value: "1rem" },
    PrimitiveToken { name: "border-width-hairline", value: "0.5px" },
    PrimitiveToken { name: "border-width-thin", value: "1px" },
];

pub const PRIMITIVE_TOKENS: &[&str] = &[
    "primitive-neutral-950", "primitive-neutral-900", "primitive-neutral-800",
    "primitive-neutral-700", "primitive-neutral-600", "primitive-neutral-500",
    "primitive-neutral-400", "primitive-neutral-300", "primitive-neutral-200",
    "primitive-neutral-100", "primitive-neutral-50", "primitive-white", "primitive-black",
    "primitive-amber-500", "primitive-amber-600", "primitive-red-500", "primitive-red-600",
    "primitive-green-50", "primitive-green-100", "primitive-green-200", "primitive-green-300",
    "primitive-green-400", "primitive-green-500", "primitive-green-600", "primitive-green-700",
    "primitive-green-800", "primitive-green-900", "primitive-green-950",
    "primitive-space-0", "primitive-space-px", "primitive-space-0-5", "primitive-space-1",
    "primitive-space-1-5", "primitive-space-2", "primitive-space-2-5", "primitive-space-3",
    "primitive-space-3-5", "primitive-space-4", "primitive-space-5", "primitive-space-6",
    "primitive-space-7", "primitive-space-8", "primitive-space-9", "primitive-space-10",
    "primitive-space-11", "primitive-space-12", "primitive-space-14", "primitive-space-16",
    "primitive-space-20", "primitive-space-24",
    "primitive-space-xs", "primitive-space-sm", "primitive-space-md", "primitive-space-lg",
    "primitive-space-xl", "primitive-space-2xl", "primitive-space-3xl",
    "primitive-radius-none", "primitive-radius-sm", "primitive-radius-md", "primitive-radius-lg",
    "primitive-radius-xl", "primitive-radius-2xl", "primitive-radius-3xl", "primitive-radius-full",
    "primitive-shadow-xs", "primitive-shadow-sm", "primitive-shadow-md", "primitive-shadow-lg",
    "primitive-shadow-xl", "primitive-shadow-2xl",
    "primitive-font-sans", "primitive-font-serif", "primitive-font-mono",
    "primitive-font-size-xs", "primitive-font-size-sm", "primitive-font-size-md",
    "primitive-font-size-lg", "primitive-font-size-xl", "primitive-font-size-2xl",
    "primitive-font-size-3xl", "primitive-font-size-4xl", "primitive-font-size-5xl",
    "primitive-font-size-6xl", "primitive-font-size-7xl",
    "primitive-font-weight-thin", "primitive-font-weight-extralight", "primitive-font-weight-light",
    "primitive-font-weight-normal", "primitive-font-weight-medium", "primitive-font-weight-semibold",
    "primitive-font-weight-bold", "primitive-font-weight-extrabold", "primitive-font-weight-black",
    "primitive-line-height-none", "primitive-line-height-tight", "primitive-line-height-snug",
    "primitive-line-height-normal", "primitive-line-height-relaxed", "primitive-line-height-loose",
    "primitive-letter-spacing-tighter", "primitive-letter-spacing-tight", "primitive-letter-spacing-normal",
    "primitive-letter-spacing-wide", "primitive-letter-spacing-wider", "primitive-letter-spacing-widest",
    "primitive-motion-duration-instant", "primitive-motion-duration-fast", "primitive-motion-duration-normal",
    "primitive-motion-duration-slow", "primitive-motion-duration-slower", "primitive-motion-duration-slowest",
    "primitive-motion-ease-linear", "primitive-motion-ease-in", "primitive-motion-ease-out",
    "primitive-motion-ease-in-out", "primitive-motion-ease-emphasized", "primitive-motion-ease-bounce",
    "primitive-z-base", "primitive-z-dropdown", "primitive-z-sticky", "primitive-z-fixed",
    "primitive-z-overlay", "primitive-z-modal", "primitive-z-popover", "primitive-z-tooltip",
    "primitive-opacity-0", "primitive-opacity-5", "primitive-opacity-10", "primitive-opacity-20",
    "primitive-opacity-30", "primitive-opacity-40", "primitive-opacity-50", "primitive-opacity-60",
    "primitive-opacity-70", "primitive-opacity-80", "primitive-opacity-90", "primitive-opacity-95",
    "primitive-opacity-100", "primitive-opacity-hover", "primitive-opacity-disabled",
    "primitive-border-width", "primitive-font-size-base", "primitive-icon-size-sm",
    "border-width-hairline", "border-width-thin",
];
