use crate::design::tokens::FamilyToken;

/// FAMILY C — Forms & Inputs
/// Components: Button, Field, Input, Select, Switch, Toggle, Slider, Calendar, ColorPicker, Label, RadioGroup, Textarea, Kbd, ButtonGroup
/// Scope: Data entry, validation, form composition

pub const FAMILY_C_FORMS: &[FamilyToken] = &[
    // Forms foundation
    FamilyToken::new("forms-color", "var(--theme-action-primary-bg)"),
    FamilyToken::new("forms-radius", "var(--radius-sm)"),
    FamilyToken::new("forms-padding-y", "var(--space-sm)"),
    FamilyToken::new("forms-disabled-opacity", "var(--state-disabled-opacity)"),

    // Validation
    FamilyToken::new("validation-error", "var(--color-destructive)"),
    FamilyToken::new("validation-warning", "var(--color-warning)"),
    FamilyToken::new("validation-success", "var(--color-success)"),

    // KBD (Keyboard display)
    FamilyToken::new("kbd-padding-x", "0.375rem"),
    FamilyToken::new("kbd-padding-y", "0.125rem"),
    FamilyToken::new("kbd-radius", "var(--radius-sm)"),
    FamilyToken::new("kbd-inline-gap", "var(--space-xs)"),
    FamilyToken::new("kbd-border-width", "1px"),
    FamilyToken::new("kbd-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("kbd-bg", "var(--theme-surface-muted)"),
    FamilyToken::new("kbd-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("kbd-font-family", "monospace"),
    FamilyToken::new("kbd-font-size", "var(--font-size-xs)"),
    FamilyToken::new("kbd-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("kbd-line-height", "1"),
    FamilyToken::new("kbd-shadow", "var(--shadow-sm)"),

    // Button
    FamilyToken::new("button-height", "var(--space-2xl)"),
    FamilyToken::new("button-padding-x", "var(--space-md)"),
    FamilyToken::new("button-padding-y", "var(--space-sm)"),
    FamilyToken::new("button-radius", "var(--radius-sm)"),
    FamilyToken::new("button-gap", "var(--space-sm)"),
    
    // Button variants
    FamilyToken::new("button-primary-bg", "var(--theme-action-primary-bg)"),
    FamilyToken::new("button-primary-fg", "var(--color-primary-foreground)"),
    FamilyToken::new("button-outline-fg", "var(--theme-action-primary-bg)"),
    FamilyToken::new("button-outline-border", "var(--theme-surface-border)"),
    FamilyToken::new("button-ghost-bg", "transparent"),
    FamilyToken::new("button-ghost-bg-hover", "var(--theme-action-accent-bg)"),
    FamilyToken::new("button-ghost-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("button-danger-bg", "var(--color-destructive)"),
    FamilyToken::new("button-danger-fg", "var(--color-destructive-foreground)"),
    FamilyToken::new("button-success-bg", "var(--color-success)"),
    FamilyToken::new("button-success-fg", "var(--color-success-foreground)"),
    FamilyToken::new("button-warning-bg", "var(--color-warning)"),
    FamilyToken::new("button-warning-fg", "var(--theme-surface-fg)"),

    // Button Group
    FamilyToken::new("button-group-gap", "var(--space-xs)"),
    FamilyToken::new("button-group-direction", "row"),
    FamilyToken::new("button-group-align", "center"),
    FamilyToken::new("button-group-radius-merge", "0"),

    // Field
    FamilyToken::new("field-border", "1px solid var(--theme-surface-border)"),
    FamilyToken::new("field-height", "var(--space-2xl)"),
    FamilyToken::new("field-padding", "var(--space-sm)"),
    FamilyToken::new("field-gap", "var(--space-sm)"),
    FamilyToken::new("field-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("field-label-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("field-label-fg-disabled", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("field-label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-label-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("field-description-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("field-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-description-line-height", "var(--line-height-normal)"),
    FamilyToken::new("field-error-fg", "var(--color-destructive)"),
    FamilyToken::new("field-error-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-error-list-gap", "var(--space-xs)"),
    FamilyToken::new("field-validation-error-fg", "var(--color-destructive)"),
    FamilyToken::new("field-validation-success-fg", "var(--color-success)"),
    FamilyToken::new("field-validation-warning-fg", "var(--color-warning)"),
    FamilyToken::new("field-separator-color", "var(--theme-surface-border)"),
    FamilyToken::new("field-separator-label-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("field-separator-label-padding-x", "var(--space-sm)"),
    FamilyToken::new("field-separator-margin-y", "var(--space-md)"),
    FamilyToken::new("field-orientation-gap-horizontal", "var(--space-sm)"),
    FamilyToken::new("field-orientation-gap-vertical", "var(--space-xs)"),

    // Input
    FamilyToken::new("input-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("input-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("input-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("input-border-width", "1px"),
    FamilyToken::new("input-height", "var(--space-2xl)"),
    FamilyToken::new("input-padding-x", "var(--space-sm)"),
    FamilyToken::new("input-padding-y", "var(--space-sm)"),
    FamilyToken::new("input-radius", "var(--radius-sm)"),
    FamilyToken::new("input-font-family", "inherit"),
    FamilyToken::new("input-font-size", "var(--font-size-sm)"),
    FamilyToken::new("input-font-weight", "var(--font-weight-normal)"),
    FamilyToken::new("input-line-height", "var(--line-height-normal)"),
    FamilyToken::new("input-placeholder", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("input-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("input-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("input-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("input-focus-ring-offset", "var(--state-focus-ring-offset)"),
    FamilyToken::new("input-error-border", "var(--color-destructive)"),
    FamilyToken::new("input-success-border", "var(--color-success)"),
    FamilyToken::new("input-sm-height", "var(--size-input-sm)"),
    FamilyToken::new("input-sm-font-size", "var(--font-size-xs)"),
    FamilyToken::new("input-md-height", "var(--space-2xl)"),
    FamilyToken::new("input-lg-height", "var(--size-icon-lg)"),
    FamilyToken::new("input-lg-font-size", "var(--font-size-base)"),
    FamilyToken::new("input-group-gap", "0"),
    FamilyToken::new("input-group-radius-merge", "0"),
    FamilyToken::new("input-group-align", "center"),

    // Input OTP
    FamilyToken::new("input-otp-slot-size", "var(--space-2xl)"),
    FamilyToken::new("input-otp-slot-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("input-otp-slot-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("input-otp-slot-border", "1px solid var(--theme-surface-border)"),
    FamilyToken::new("input-otp-slot-radius", "var(--radius-sm)"),
    FamilyToken::new("input-otp-slot-active-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("input-otp-slot-active-border", "var(--color-ring)"),
    FamilyToken::new("input-otp-slot-disabled-bg", "var(--theme-surface-muted)"),
    FamilyToken::new("input-otp-slot-disabled-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("input-otp-font-family", "monospace"),
    FamilyToken::new("input-otp-font-size", "var(--font-size-base)"),
    FamilyToken::new("input-otp-font-weight", "var(--font-weight-semibold)"),

    // Textarea
    FamilyToken::new("textarea-min-height", "var(--size-textarea-min)"),
    FamilyToken::new("textarea-max-height", "var(--layout-width-md)"),
    FamilyToken::new("textarea-resize", "vertical"),

    // Select
    FamilyToken::new("select-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("select-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("select-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("select-border-width", "1px"),
    FamilyToken::new("select-height", "var(--space-2xl)"),
    FamilyToken::new("select-padding-x", "var(--space-sm)"),
    FamilyToken::new("select-radius", "var(--radius-sm)"),
    FamilyToken::new("select-gap", "var(--space-sm)"),
    FamilyToken::new("select-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("select-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("select-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("select-focus-ring-offset", "var(--state-focus-ring-offset)"),
    FamilyToken::new("select-content-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("select-content-padding-y", "var(--space-xs)"),
    FamilyToken::new("select-content-radius", "var(--radius-md)"),
    FamilyToken::new("select-content-shadow", "var(--shadow-lg)"),
    FamilyToken::new("select-content-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("select-content-border-width", "1px"),
    FamilyToken::new("select-item-height", "var(--size-input-sm)"),
    FamilyToken::new("select-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("select-item-hover-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("select-item-selected-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("select-item-selected-fg", "var(--color-accent-foreground)"),
    FamilyToken::new("select-separator-color", "var(--theme-surface-border)"),
    FamilyToken::new("select-separator-height", "1px"),
    FamilyToken::new("select-separator-margin-y", "var(--space-xs)"),

    // Switch
    FamilyToken::new("switch-width", "var(--size-switch-width)"),
    FamilyToken::new("switch-height", "var(--space-lg)"),
    FamilyToken::new("switch-radius", "var(--radius-full)"),
    FamilyToken::new("switch-track-bg", "var(--color-input)"),
    FamilyToken::new("switch-track-bg-checked", "var(--theme-action-primary-bg)"),
    FamilyToken::new("switch-thumb-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("switch-thumb-size", "var(--font-size-xl)"),
    FamilyToken::new("switch-thumb-radius", "var(--radius-full)"),
    FamilyToken::new("switch-thumb-translate-unchecked", "var(--space-xs)"),
    FamilyToken::new("switch-thumb-translate-checked", "var(--size-switch-translate)"),
    FamilyToken::new("switch-disabled-opacity", "var(--state-disabled-opacity)"),

    // Toggle
    FamilyToken::new("toggle-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("toggle-radius", "var(--radius-sm)"),
    FamilyToken::new("toggle-border-width", "1px"),
    FamilyToken::new("toggle-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("toggle-hover-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("toggle-active-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("toggle-active-fg", "var(--color-accent-foreground)"),
    FamilyToken::new("toggle-group-gap", "var(--space-xs)"),
    FamilyToken::new("toggle-group-direction", "row"),
    FamilyToken::new("toggle-group-wrap", "nowrap"),

    // Slider
    FamilyToken::new("slider-height", "var(--font-size-xl)"),
    FamilyToken::new("slider-padding", "0"),
    FamilyToken::new("slider-track-bg", "var(--color-secondary)"),
    FamilyToken::new("slider-track-height", "var(--space-sm)"),
    FamilyToken::new("slider-track-radius", "var(--radius-full)"),
    FamilyToken::new("slider-range-bg", "var(--theme-action-primary-bg)"),
    FamilyToken::new("slider-thumb-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("slider-thumb-size", "var(--font-size-xl)"),
    FamilyToken::new("slider-thumb-radius", "var(--radius-full)"),
    FamilyToken::new("slider-thumb-border-color", "var(--theme-action-primary-bg)"),
    FamilyToken::new("slider-thumb-border-width", "2px"),
    FamilyToken::new("slider-thumb-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("slider-thumb-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("slider-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("slider-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("slider-transition-ease", "var(--motion-ease-standard)"),

    // Calendar
    FamilyToken::new("calendar-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("calendar-padding", "var(--space-md)"),
    FamilyToken::new("calendar-radius", "var(--radius-md)"),
    FamilyToken::new("calendar-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("calendar-border-width", "1px"),
    FamilyToken::new("calendar-header-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("calendar-header-font-size", "var(--font-size-sm)"),
    FamilyToken::new("calendar-header-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("calendar-header-gap", "var(--space-sm)"),
    FamilyToken::new("calendar-grid-gap", "var(--space-xs)"),
    FamilyToken::new("calendar-cell-size", "var(--size-cell)"),
    FamilyToken::new("calendar-cell-radius", "var(--radius-sm)"),
    FamilyToken::new("calendar-cell-font-size", "var(--font-size-sm)"),
    FamilyToken::new("calendar-cell-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("calendar-cell-fg-disabled", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("calendar-cell-fg-selected", "var(--color-primary-foreground)"),
    FamilyToken::new("calendar-cell-bg-hover", "var(--theme-action-accent-bg)"),
    FamilyToken::new("calendar-cell-bg-selected", "var(--theme-action-primary-bg)"),
    FamilyToken::new("calendar-cell-bg-disabled", "transparent"),
    FamilyToken::new("calendar-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("calendar-transition-ease", "var(--motion-ease-standard)"),

    // ColorPicker
    FamilyToken::new("color-picker-size", "var(--size-color-picker)"),
    FamilyToken::new("color-picker-radius", "var(--radius-md)"),
    FamilyToken::new("color-picker-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("color-picker-border-width", "1px"),
    FamilyToken::new("color-picker-trigger-size", "var(--space-2xl)"),
    FamilyToken::new("color-picker-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("color-picker-swatch-size", "var(--size-input-sm)"),
    FamilyToken::new("color-picker-swatch-radius", "var(--radius-xs)"),
    FamilyToken::new("color-picker-swatch-border-width", "1px"),
    FamilyToken::new("color-picker-swatch-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("color-picker-swatch-border-color-selected", "var(--theme-action-primary-bg)"),
    FamilyToken::new("color-picker-panel-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("color-picker-panel-padding", "var(--space-md)"),
    FamilyToken::new("color-picker-panel-radius", "var(--radius-md)"),
    FamilyToken::new("color-picker-panel-shadow", "var(--shadow-lg)"),
    FamilyToken::new("color-picker-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("color-picker-transition-ease", "var(--motion-ease-standard)"),

    // Label
    FamilyToken::new("label-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("label-fg-muted", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("label-fg-disabled", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("label-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("label-line-height", "var(--line-height-normal)"),
    FamilyToken::new("label-margin-bottom", "var(--space-sm)"),

    // RadioGroup
    FamilyToken::new("radio-group-gap", "var(--space-sm)"),
    FamilyToken::new("radio-group-item-gap", "var(--space-sm)"),
    FamilyToken::new("radio-group-label-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("radio-group-label-fg-disabled", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("radio-group-label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("radio-group-label-font-weight", "var(--font-weight-medium)"),

    // Form
    FamilyToken::new("form-gap", "var(--space-lg)"),
    FamilyToken::new("form-actions-gap", "var(--space-sm)"),
    FamilyToken::new("form-actions-justify", "flex-end"),
    FamilyToken::new("form-actions-padding-top", "var(--space-lg)"),
    FamilyToken::new("form-actions-border-top", "1px solid var(--theme-surface-border)"),
    FamilyToken::new("form-error-summary-bg", "var(--theme-state-error-bg)"),
    FamilyToken::new("form-error-summary-padding-x", "var(--space-md)"),
    FamilyToken::new("form-error-summary-padding-y", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-radius", "var(--radius-md)"),
    FamilyToken::new("form-error-summary-border-color", "var(--color-destructive)"),
    FamilyToken::new("form-error-summary-border-width", "1px"),
    FamilyToken::new("form-error-summary-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-title-fg", "var(--color-destructive)"),
    FamilyToken::new("form-error-summary-title-font-size", "var(--font-size-sm)"),
    FamilyToken::new("form-error-summary-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("form-error-summary-list-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-item-fg", "var(--color-destructive)"),
    FamilyToken::new("form-error-summary-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("form-error-summary-item-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-item-icon-color", "var(--color-destructive)"),
    FamilyToken::new("form-error-summary-item-icon-size", "var(--space-md)"),
    // Form (tokens simplificados faltantes)
    FamilyToken::new("form-help-text-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("form-label-font-size", "var(--font-size-sm)"),

];
