use crate::design::tokens::FamilyToken;

/// FAMILY F — Data & Media
/// Components: Card, Table, DataTable, Icon, IconButton, Chart, Kbd, CodeBlock,
///             Avatar, Stat, CopyButton, ScrollArea, ListItem, Markdown
/// Scope: Data display, media presentation, code representation, documentation

pub const FAMILY_F_DATA: &[FamilyToken] = &[

    // ── Data Foundation ───────────────────────────────────────────────────────
    FamilyToken::new("data-radius",  "var(--radius-md)"),
    FamilyToken::new("data-shadow",  "var(--shadow-sm)"),
    FamilyToken::new("data-spacing", "var(--space-md)"),

    // ── Card ──────────────────────────────────────────────────────────────────
    FamilyToken::new("card-bg",                      "var(--theme-surface-bg)"),
    FamilyToken::new("card-border",                  "var(--theme-surface-border)"),
    FamilyToken::new("card-radius",                  "var(--radius-md)"),
    FamilyToken::new("card-shadow",                  "var(--shadow-sm)"),
    FamilyToken::new("card-border-width",            "1px"),
    FamilyToken::new("card-border-color",            "var(--theme-surface-border)"),
    FamilyToken::new("card-padding",                 "var(--space-lg)"),
    FamilyToken::new("card-content-gap",             "var(--space-md)"),
    FamilyToken::new("card-header-gap",              "var(--space-sm)"),
    FamilyToken::new("card-header-padding",          "0 0 var(--space-md) 0"),
    FamilyToken::new("card-footer-gap",              "var(--space-sm)"),
    FamilyToken::new("card-footer-padding",          "var(--space-md) 0 0 0"),
    FamilyToken::new("card-fg",                      "var(--theme-surface-fg)"),
    FamilyToken::new("card-title-fg",                "var(--theme-surface-fg)"),
    FamilyToken::new("card-title-font-size",         "var(--font-size-lg)"),
    FamilyToken::new("card-title-font-weight",       "var(--font-weight-semibold)"),
    FamilyToken::new("card-description-fg",          "var(--theme-surface-fg-muted)"),
    FamilyToken::new("card-description-font-size",   "var(--font-size-sm)"),
    FamilyToken::new("card-description-line-height", "var(--line-height-tight)"),

    // ── Table ─────────────────────────────────────────────────────────────────
    FamilyToken::new("table-border-color",         "var(--theme-surface-border)"),
    FamilyToken::new("table-border-width",         "1px"),
    FamilyToken::new("table-row-height",           "var(--space-2xl)"),
    FamilyToken::new("table-row-bg-hover",         "var(--theme-surface-muted)"),
    FamilyToken::new("table-row-bg-selected",      "var(--theme-action-accent-bg)"),
    FamilyToken::new("table-row-bg-striped",       "color-mix(in srgb, var(--theme-surface-fg) 3%, transparent)"),
    FamilyToken::new("table-row-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("table-row-transition-ease",  "var(--motion-ease-standard)"),
    FamilyToken::new("table-cell-fg",              "var(--theme-surface-fg)"),
    FamilyToken::new("table-cell-font-size",       "var(--font-size-sm)"),
    FamilyToken::new("table-cell-padding-x",       "var(--space-md)"),
    FamilyToken::new("table-cell-padding-y",       "var(--space-sm)"),
    FamilyToken::new("table-header-bg",            "var(--theme-surface-muted)"),
    FamilyToken::new("table-header-fg",            "var(--theme-surface-fg)"),
    FamilyToken::new("table-header-font-size",     "var(--font-size-sm)"),
    FamilyToken::new("table-header-font-weight",   "var(--font-weight-semibold)"),
    FamilyToken::new("table-header-height",        "var(--space-xl)"),
    FamilyToken::new("table-caption-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("table-caption-font-size",    "var(--font-size-sm)"),
    FamilyToken::new("table-caption-padding-y",    "var(--space-sm)"),

    // ── DataTable ─────────────────────────────────────────────────────────────
    FamilyToken::new("datatable-border-color",           "var(--table-border-color)"),
    FamilyToken::new("datatable-header-bg",              "var(--table-header-bg)"),
    FamilyToken::new("datatable-row-bg-hover",           "var(--table-row-bg-hover)"),
    FamilyToken::new("datatable-row-bg-selected",        "var(--table-row-bg-selected)"),
    FamilyToken::new("datatable-toolbar-gap",            "var(--space-sm)"),
    FamilyToken::new("datatable-toolbar-padding-y",      "var(--space-sm)"),
    FamilyToken::new("datatable-toolbar-padding-x",      "var(--space-sm)"),
    FamilyToken::new("datatable-filter-max-width",       "300px"),
    FamilyToken::new("datatable-density-compact-padding-y",     "var(--space-xs)"),
    FamilyToken::new("datatable-density-compact-padding-x",     "var(--space-sm)"),
    FamilyToken::new("datatable-density-comfortable-padding-y", "var(--space-sm)"),
    FamilyToken::new("datatable-density-comfortable-padding-x", "var(--space-md)"),
    FamilyToken::new("datatable-density-spacious-padding-y",    "var(--space-md)"),
    FamilyToken::new("datatable-density-spacious-padding-x",    "var(--space-lg)"),

    // ── Icon ──────────────────────────────────────────────────────────────────
    FamilyToken::new("icon-size-sm",       "var(--space-md)"),
    FamilyToken::new("icon-size-md",       "var(--font-size-xl)"),
    FamilyToken::new("icon-size-lg",       "var(--space-lg)"),
    FamilyToken::new("icon-color",         "var(--theme-surface-fg)"),
    FamilyToken::new("icon-color-muted",   "var(--theme-surface-fg-muted)"),
    FamilyToken::new("icon-color-disabled","var(--theme-surface-fg-muted)"),
    FamilyToken::new("icon-vertical-align","middle"),

    // ── Icon Button ───────────────────────────────────────────────────────────
    FamilyToken::new("icon-button-size-sm",           "var(--space-xl)"),
    FamilyToken::new("icon-button-size-md",           "var(--space-2xl)"),
    FamilyToken::new("icon-button-size-lg",           "var(--size-icon-lg)"),
    FamilyToken::new("icon-button-padding-sm",        "var(--space-sm)"),
    FamilyToken::new("icon-button-padding-md",        "var(--space-sm)"),
    FamilyToken::new("icon-button-padding-lg",        "var(--space-sm)"),
    FamilyToken::new("icon-button-radius",            "var(--radius-sm)"),
    FamilyToken::new("icon-button-bg",                "transparent"),
    FamilyToken::new("icon-button-bg-hover",          "var(--theme-action-accent-bg)"),
    FamilyToken::new("icon-button-bg-active",         "var(--theme-action-accent-bg)"),
    FamilyToken::new("icon-button-fg",                "var(--theme-surface-fg)"),
    FamilyToken::new("icon-button-fg-disabled",       "var(--theme-surface-fg-muted)"),
    FamilyToken::new("icon-button-transition-duration","var(--motion-duration-fast)"),
    FamilyToken::new("icon-button-transition-ease",   "var(--motion-ease-standard)"),

    // ── Chart ─────────────────────────────────────────────────────────────────
    FamilyToken::new("chart-bg",                  "var(--theme-surface-bg)"),
    FamilyToken::new("chart-padding",             "var(--space-md)"),
    FamilyToken::new("chart-radius",              "var(--radius-md)"),
    FamilyToken::new("chart-grid-color",          "var(--theme-surface-border)"),
    FamilyToken::new("chart-grid-stroke-width",   "1px"),
    FamilyToken::new("chart-axis-fg",             "var(--theme-surface-fg-muted)"),
    FamilyToken::new("chart-axis-font-size",      "var(--font-size-xs)"),
    FamilyToken::new("chart-axis-tick-size",      "4px"),
    FamilyToken::new("chart-legend-gap",          "var(--space-md)"),
    FamilyToken::new("chart-legend-item-fg",      "var(--theme-surface-fg)"),
    FamilyToken::new("chart-legend-item-font-size","var(--font-size-sm)"),
    FamilyToken::new("chart-tooltip-bg",          "var(--theme-overlay-bg)"),
    FamilyToken::new("chart-tooltip-fg",          "var(--color-popover-foreground)"),
    FamilyToken::new("chart-tooltip-font-size",   "var(--font-size-sm)"),
    FamilyToken::new("chart-tooltip-radius",      "var(--radius-sm)"),
    FamilyToken::new("chart-tooltip-shadow",      "var(--shadow-md)"),
    FamilyToken::new("chart-tooltip-padding",     "var(--space-sm) var(--space-md)"),
    FamilyToken::new("chart-crosshair-color",     "var(--theme-surface-border)"),
    FamilyToken::new("chart-crosshair-width",     "1px"),
    FamilyToken::new("chart-legend-dot-size",     "10px"),
    FamilyToken::new("chart-sync-highlight-bg",   "var(--theme-primary-subtle, rgba(99,102,241,0.08))"),
    FamilyToken::new("chart-overlay-z",           "10"),

    // ── Kbd ───────────────────────────────────────────────────────────────────
    FamilyToken::new("kbd-bg",           "var(--theme-surface-muted)"),
    FamilyToken::new("kbd-fg",           "var(--theme-surface-fg)"),
    FamilyToken::new("kbd-padding-x",    "var(--space-sm)"),
    FamilyToken::new("kbd-padding-y",    "var(--space-xs)"),
    FamilyToken::new("kbd-radius",       "var(--radius-sm)"),
    FamilyToken::new("kbd-shadow",       "var(--shadow-sm)"),
    FamilyToken::new("kbd-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("kbd-border-width", "1px"),
    FamilyToken::new("kbd-font-family",  "monospace"),
    FamilyToken::new("kbd-font-size",    "var(--font-size-xs)"),
    FamilyToken::new("kbd-font-weight",  "var(--font-weight-semibold)"),
    FamilyToken::new("kbd-line-height",  "var(--space-md)"),
    FamilyToken::new("kbd-muted-bg",     "var(--theme-surface-muted)"),
    FamilyToken::new("kbd-muted-fg",     "var(--theme-surface-fg-muted)"),
    FamilyToken::new("kbd-inline-gap",   "var(--space-xs)"),
    FamilyToken::new("kbd-gap",              "var(--space-xs)"),
    FamilyToken::new("kbd-separator-color",  "var(--theme-surface-fg-muted)"),
    FamilyToken::new("kbd-size-sm-font",     "var(--font-size-2xs)"),
    FamilyToken::new("kbd-size-sm-padding-x","var(--space-xs)"),
    FamilyToken::new("kbd-size-sm-padding-y","2px"),

    // ── Code Block ────────────────────────────────────────────────────────────
    FamilyToken::new("code-block-bg",                  "var(--theme-surface-muted)"),
    FamilyToken::new("code-block-radius",              "var(--radius-md)"),
    FamilyToken::new("code-block-border-color",        "var(--theme-surface-border)"),
    FamilyToken::new("code-block-border-width",        "1px"),
    FamilyToken::new("code-block-content-padding-x",   "var(--space-md)"),
    FamilyToken::new("code-block-content-padding-y",   "var(--space-md)"),
    FamilyToken::new("code-block-font-family",         "monospace"),
    FamilyToken::new("code-block-font-size",           "var(--font-size-sm)"),
    FamilyToken::new("code-block-line-height",         "var(--line-height-normal)"),
    FamilyToken::new("code-block-header-bg",           "var(--theme-surface-muted)"),
    FamilyToken::new("code-block-header-fg",           "var(--theme-surface-fg)"),
    FamilyToken::new("code-block-header-height",       "var(--space-xl)"),
    FamilyToken::new("code-block-header-gap",          "var(--space-sm)"),
    FamilyToken::new("code-block-language-fg",         "var(--theme-surface-fg-muted)"),
    FamilyToken::new("code-block-language-font-size",  "var(--font-size-xs)"),

    // ── Avatar ────────────────────────────────────────────────────────────────
    FamilyToken::new("avatar-size-xs",               "1.5rem"),
    FamilyToken::new("avatar-size-sm",               "2rem"),
    FamilyToken::new("avatar-size-md",               "2.5rem"),
    FamilyToken::new("avatar-size-lg",               "3rem"),
    FamilyToken::new("avatar-size-xl",               "4rem"),
    FamilyToken::new("avatar-radius",                "var(--radius-full)"),
    FamilyToken::new("avatar-radius-square",         "var(--radius-xs)"),
    FamilyToken::new("avatar-radius-rounded",        "var(--radius-lg)"),
    FamilyToken::new("avatar-bg",                    "var(--theme-surface-muted)"),
    FamilyToken::new("avatar-border-color",          "var(--theme-surface-border)"),
    FamilyToken::new("avatar-border-width",          "1px"),
    FamilyToken::new("avatar-fallback-bg",           "var(--theme-surface-muted)"),
    FamilyToken::new("avatar-fallback-fg",           "var(--theme-surface-fg-muted)"),
    FamilyToken::new("avatar-fallback-font-size",    "var(--font-size-sm)"),
    FamilyToken::new("avatar-fallback-font-weight",  "var(--font-weight-medium)"),
    FamilyToken::new("avatar-image-fit",             "cover"),
    FamilyToken::new("avatar-fg",                    "var(--theme-surface-fg-muted)"),
    FamilyToken::new("avatar-status-size",           "25%"),
    FamilyToken::new("avatar-status-border-width",   "2px"),
    FamilyToken::new("avatar-status-border-color",   "var(--theme-surface-bg)"),
    FamilyToken::new("avatar-status-online-bg",      "var(--color-success)"),
    FamilyToken::new("avatar-status-offline-bg",     "var(--theme-surface-fg-muted)"),
    FamilyToken::new("avatar-status-busy-bg",        "var(--color-destructive)"),
    FamilyToken::new("avatar-status-away-bg",        "var(--color-warning)"),
    FamilyToken::new("avatar-badge-size",            "var(--space-md)"),
    FamilyToken::new("avatar-badge-offset",          "-4px"),
    FamilyToken::new("avatar-badge-bg",              "var(--color-destructive)"),
    FamilyToken::new("avatar-badge-fg",              "var(--color-destructive-foreground)"),
    FamilyToken::new("avatar-badge-font-size",       "var(--font-size-xs)"),
    FamilyToken::new("avatar-badge-font-weight",     "var(--font-weight-semibold)"),
    FamilyToken::new("avatar-group-overlap",         "-0.5rem"),

    // ── Stat ──────────────────────────────────────────────────────────────────
    FamilyToken::new("stat-gap",               "var(--space-xs)"),
    FamilyToken::new("stat-align",             "flex-start"),
    FamilyToken::new("stat-value-fg",          "var(--theme-surface-fg)"),
    FamilyToken::new("stat-value-font-size",   "var(--font-size-3xl)"),
    FamilyToken::new("stat-value-font-weight", "var(--font-weight-bold)"),
    FamilyToken::new("stat-label-fg",          "var(--theme-surface-fg-muted)"),
    FamilyToken::new("stat-label-font-size",   "var(--font-size-sm)"),

    // ── Copy Button ───────────────────────────────────────────────────────────
    FamilyToken::new("copy-button-icon-size",          "var(--space-md)"),
    FamilyToken::new("copy-button-icon-color",         "var(--theme-surface-fg-muted)"),
    FamilyToken::new("copy-button-icon-color-copied",  "var(--color-success)"),
    FamilyToken::new("copy-button-success-bg",     "var(--color-success)"),
    FamilyToken::new("copy-button-success-fg",     "var(--color-success-foreground)"),
    FamilyToken::new("copy-button-success-border", "var(--color-success)"),
    FamilyToken::new("copy-button-error-bg",       "var(--color-destructive)"),
    FamilyToken::new("copy-button-error-fg",       "var(--color-destructive-foreground)"),
    FamilyToken::new("copy-button-error-border",   "var(--color-destructive)"),
    FamilyToken::new("copy-button-bg",             "transparent"),
    FamilyToken::new("copy-button-fg",             "var(--theme-surface-fg)"),
    FamilyToken::new("copy-button-border",         "var(--theme-surface-border)"),
    FamilyToken::new("copy-button-bg-hover",       "var(--theme-surface-muted)"),
    FamilyToken::new("copy-button-copied-bg",          "var(--theme-state-success-bg)"),
    FamilyToken::new("copy-button-copied-fg",          "var(--color-success)"),
    FamilyToken::new("copy-button-transition-duration","var(--motion-duration-normal)"),
    FamilyToken::new("copy-button-transition-ease",    "var(--motion-ease-standard)"),

    // ── Scroll Area ───────────────────────────────────────────────────────────
    FamilyToken::new("scroll-area-bg",                  "transparent"),
    FamilyToken::new("scroll-area-border",              "none"),
    FamilyToken::new("scroll-area-radius",              "0"),
    FamilyToken::new("scroll-area-padding",             "0"),
    FamilyToken::new("scroll-area-max-height",          "100%"),
    FamilyToken::new("scrollbar-size",                  "8px"),
    FamilyToken::new("scrollbar-radius",                "var(--radius-full)"),
    FamilyToken::new("scrollbar-track-bg",              "transparent"),
    FamilyToken::new("scrollbar-thumb-bg",              "var(--theme-surface-border)"),
    FamilyToken::new("scrollbar-thumb-hover-bg",        "var(--theme-surface-fg-muted)"),
    FamilyToken::new("scrollbar-thumb-active-bg",       "var(--theme-surface-fg)"),
    FamilyToken::new("scrollbar-transition",            "background var(--motion-duration-fast) var(--motion-ease-standard)"),
    FamilyToken::new("scrollbar-thumb-min-size",        "40px"),

    // ── List ──────────────────────────────────────────────────────────────────
    FamilyToken::new("list-gap",            "var(--space-sm)"),
    FamilyToken::new("list-item-padding",   "var(--space-sm) var(--space-md)"),
    FamilyToken::new("list-item-padding-y", "var(--space-sm)"),
    FamilyToken::new("list-item-border",    "1px solid var(--theme-surface-border)"),
    FamilyToken::new("list-item-bg-hover",  "var(--theme-action-accent-bg)"),

    // ── Markdown ──────────────────────────────────────────────────────────────
    FamilyToken::new("markdown-max-width",          "75ch"),
    FamilyToken::new("markdown-padding",            "var(--space-lg)"),
    FamilyToken::new("markdown-font-family",        "var(--font-family-sans)"),
    FamilyToken::new("markdown-font-size",          "var(--font-size-md)"),
    FamilyToken::new("markdown-line-height",        "var(--line-height-relaxed)"),
    FamilyToken::new("markdown-fg",                 "var(--theme-surface-fg)"),
    FamilyToken::new("markdown-heading-fg",         "var(--theme-surface-fg)"),
    FamilyToken::new("markdown-link-fg",            "var(--theme-action-primary-bg)"),
    FamilyToken::new("markdown-blockquote-border",  "var(--theme-action-primary-bg)"),
    FamilyToken::new("markdown-blockquote-fg",      "var(--theme-surface-fg-muted)"),
    FamilyToken::new("markdown-hr-color",           "var(--theme-surface-border-muted)"),
    FamilyToken::new("markdown-inline-code-bg",     "var(--theme-surface-muted)"),
    FamilyToken::new("markdown-inline-code-fg",     "var(--color-destructive)"),
    FamilyToken::new("markdown-inline-code-radius", "var(--radius-sm)"),

    // ── Markdown Toolbar ──────────────────────────────────────────────────────
    FamilyToken::new("markdown-toolbar-gap",             "var(--space-xs)"),
    FamilyToken::new("markdown-toolbar-padding-x",       "var(--space-sm)"),
    FamilyToken::new("markdown-toolbar-padding-y",       "var(--space-xs)"),
    FamilyToken::new("markdown-toolbar-border-color",    "var(--theme-surface-border-muted)"),
    FamilyToken::new("markdown-toolbar-item-padding-x",  "var(--space-sm)"),
    FamilyToken::new("markdown-toolbar-item-padding-y",  "var(--space-xs)"),
    FamilyToken::new("markdown-toolbar-item-radius",     "var(--radius-sm)"),
    FamilyToken::new("markdown-toolbar-item-fg",         "var(--theme-surface-fg-muted)"),
    FamilyToken::new("markdown-toolbar-item-fg-hover",   "var(--theme-surface-fg)"),
    FamilyToken::new("markdown-toolbar-item-bg-hover",   "var(--theme-surface-muted)"),
    FamilyToken::new("markdown-toolbar-item-border-color","var(--theme-surface-border-muted)"),

    // ── Markdown TOC ──────────────────────────────────────────────────────────
    FamilyToken::new("markdown-toc-border-color",        "var(--theme-surface-border-muted)"),
    FamilyToken::new("markdown-toc-border-radius",       "var(--radius-md)"),
    FamilyToken::new("markdown-toc-padding",             "var(--space-md)"),
    FamilyToken::new("markdown-toc-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("markdown-toc-transition-ease",     "var(--motion-ease-standard)"),
    FamilyToken::new("markdown-toc-link-fg",             "var(--theme-surface-fg-muted)"),
    FamilyToken::new("markdown-toc-link-fg-hover",       "var(--theme-surface-fg)"),
    FamilyToken::new("markdown-toc-link-bg-hover",       "var(--theme-surface-muted)"),
    FamilyToken::new("markdown-toc-link-fg-active",      "var(--theme-action-primary-bg)"),
    FamilyToken::new("markdown-toc-link-bg-active",      "var(--theme-surface-muted)"),
    FamilyToken::new("markdown-toc-link-border-active",  "var(--theme-action-primary-bg)"),
    FamilyToken::new("markdown-toc-link-font-size",      "var(--font-size-sm)"),
    FamilyToken::new("markdown-toc-link-font-weight-active", "var(--font-weight-semibold)"),
    FamilyToken::new("markdown-toc-indent-l3",           "var(--space-md)"),
    FamilyToken::new("markdown-toc-indent-l4",           "var(--space-lg)"),
    FamilyToken::new("markdown-toc-indent-l5",           "var(--space-xl)"),
    FamilyToken::new("icon-color-primary",     "var(--color-primary)"),
    FamilyToken::new("icon-color-destructive", "var(--color-destructive)"),
    FamilyToken::new("icon-color-success",     "var(--color-success)"),
    FamilyToken::new("icon-color-warning",     "var(--color-warning)"),
    FamilyToken::new("icon-stroke-width",      "2"),
];
