use crate::design::tokens::FamilyToken;

/// FAMILY B — Selection & Menus
/// Components: Accordion, Collapsible, Combobox, ContextMenu, DropdownMenu, Menu, Menubar, Tree, Command, Checkbox, Radio, Tabs
/// Scope: Selection lists, contextual menus, hierarchical navigation, toggles

pub const FAMILY_B_SELECTION: &[FamilyToken] = &[
    // Selection foundation
    FamilyToken::new("selection-color", "var(--theme-action-primary-bg)"),
    FamilyToken::new("selection-spacing", "var(--space-sm)"),
    FamilyToken::new("selection-hover-opacity", "var(--state-hover-opacity)"),

    // Checkbox
    FamilyToken::new("checkbox-size", "1.25rem"),
    FamilyToken::new("checkbox-radius", "var(--radius-sm)"),
    FamilyToken::new("checkbox-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("checkbox-bg-checked", "var(--theme-action-primary-bg)"),
    FamilyToken::new("checkbox-fg-checked", "var(--color-primary-foreground)"),
    FamilyToken::new("checkbox-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("checkbox-border-width", "1px"),
    FamilyToken::new("checkbox-border-color-checked", "var(--theme-action-primary-bg)"),
    FamilyToken::new("checkbox-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("checkbox-disabled-opacity", "var(--state-disabled-opacity)"),

    // Radio
    FamilyToken::new("radio-size", "1.25rem"),
    FamilyToken::new("radio-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("radio-bg-checked", "var(--theme-action-primary-bg)"),
    FamilyToken::new("radio-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("radio-border-width", "1px"),
    FamilyToken::new("radio-border-color-checked", "var(--theme-action-primary-bg)"),
    FamilyToken::new("radio-dot-size", "0.5rem"),
    FamilyToken::new("radio-dot-color", "var(--color-primary-foreground)"),
    FamilyToken::new("radio-group-gap", "var(--space-sm)"),
    FamilyToken::new("radio-group-item-gap", "var(--space-xs)"),
    FamilyToken::new("radio-group-label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("radio-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("radio-disabled-opacity", "var(--state-disabled-opacity)"),

    // Tabs
    FamilyToken::new("tabs-gap", "var(--space-xs)"),
    FamilyToken::new("tabs-list-bg", "var(--theme-surface-muted)"),
    FamilyToken::new("tabs-list-padding", "var(--space-xs)"),
    FamilyToken::new("tabs-list-radius", "var(--radius-md)"),
    FamilyToken::new("tabs-trigger-padding-x", "var(--space-md)"),
    FamilyToken::new("tabs-trigger-padding-y", "var(--space-sm)"),
    FamilyToken::new("tabs-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("tabs-trigger-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("tabs-trigger-fg-active", "var(--theme-surface-fg)"),
    FamilyToken::new("tabs-trigger-bg-active", "var(--theme-surface-bg)"),
    FamilyToken::new("tabs-trigger-font-size", "var(--font-size-sm)"),
    FamilyToken::new("tabs-trigger-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("tabs-trigger-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("tabs-content-padding", "var(--space-md)"),

    // Accordion
    FamilyToken::new("accordion-gap", "var(--space-sm)"),
    FamilyToken::new("accordion-item-border-width", "1px"),
    FamilyToken::new("accordion-item-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("accordion-item-border-radius", "var(--radius-md)"),
    FamilyToken::new("accordion-trigger-bg", "transparent"),
    FamilyToken::new("accordion-trigger-bg-hover", "var(--theme-surface-muted)"),
    FamilyToken::new("accordion-trigger-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("accordion-trigger-padding-x", "var(--space-md)"),
    FamilyToken::new("accordion-trigger-padding-y", "var(--space-sm)"),
    FamilyToken::new("accordion-trigger-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("accordion-trigger-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("accordion-trigger-transition-ease", "var(--motion-ease-standard)"),
    FamilyToken::new("accordion-content-padding-x", "var(--space-md)"),
    FamilyToken::new("accordion-content-padding-y", "var(--space-sm)"),
    FamilyToken::new("accordion-content-padding-top", "0"),
    FamilyToken::new("accordion-icon-size", "var(--space-md)"),
    FamilyToken::new("accordion-icon-rotation", "180deg"),

    // Collapsible
    FamilyToken::new("collapsible-gap", "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-bg", "transparent"),
    FamilyToken::new("collapsible-trigger-bg-hover", "var(--theme-surface-muted)"),
    FamilyToken::new("collapsible-trigger-padding", "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("collapsible-content-padding", "var(--space-sm)"),
    FamilyToken::new("collapsible-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("collapsible-transition-ease", "var(--motion-ease-standard)"),

    // Combobox
    FamilyToken::new("combobox-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("combobox-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("combobox-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("combobox-border-width", "1px"),
    FamilyToken::new("combobox-height", "var(--space-2xl)"),
    FamilyToken::new("combobox-padding-x", "var(--space-sm)"),
    FamilyToken::new("combobox-radius", "var(--radius-sm)"),
    FamilyToken::new("combobox-gap", "var(--space-sm)"),
    FamilyToken::new("combobox-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("combobox-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("combobox-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("combobox-popover-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("combobox-popover-padding-y", "var(--space-xs)"),
    FamilyToken::new("combobox-popover-radius", "var(--radius-md)"),
    FamilyToken::new("combobox-popover-shadow", "var(--shadow-lg)"),
    FamilyToken::new("combobox-item-height", "var(--space-xl)"),
    FamilyToken::new("combobox-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("combobox-item-hover-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("combobox-item-selected-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("combobox-empty-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("combobox-empty-padding", "var(--space-sm)"),

    // ContextMenu
    FamilyToken::new("context-menu-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("context-menu-fg", "var(--color-popover-foreground)"),
    FamilyToken::new("context-menu-padding-y", "var(--space-xs)"),
    FamilyToken::new("context-menu-radius", "var(--radius-md)"),
    FamilyToken::new("context-menu-shadow", "var(--shadow-lg)"),
    FamilyToken::new("context-menu-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("context-menu-border-width", "1px"),
    FamilyToken::new("context-menu-min-width", "var(--layout-width-sm)"),
    FamilyToken::new("context-menu-item-height", "var(--space-xl)"),
    FamilyToken::new("context-menu-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("context-menu-item-hover-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("context-menu-separator-color", "var(--theme-surface-border)"),
    FamilyToken::new("context-menu-separator-margin-y", "var(--space-xs)"),
    FamilyToken::new("context-menu-label-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("context-menu-label-font-size", "var(--font-size-xs)"),
    FamilyToken::new("context-menu-label-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("context-menu-shortcut-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("context-menu-shortcut-font-size", "var(--font-size-xs)"),

    // Menu
    FamilyToken::new("menu-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("menu-padding", "var(--space-sm)"),
    FamilyToken::new("menu-gap", "var(--space-xs)"),
    FamilyToken::new("menu-item-height", "var(--font-size-4xl)"),
    FamilyToken::new("menu-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("menu-item-radius", "var(--radius-sm)"),
    FamilyToken::new("menu-item-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("menu-item-bg-hover", "var(--theme-action-accent-bg)"),
    FamilyToken::new("menu-item-bg-active", "var(--theme-action-accent-bg)"),
    FamilyToken::new("menu-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("menu-item-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("menu-item-transition-ease", "var(--motion-ease-standard)"),

    // Menubar
    FamilyToken::new("menubar-bg", "var(--theme-surface-bg)"),
    FamilyToken::new("menubar-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("menubar-border-width", "0 0 1px 0"),
    FamilyToken::new("menubar-padding", "var(--space-sm)"),
    FamilyToken::new("menubar-gap", "var(--space-xs)"),
    FamilyToken::new("menubar-trigger-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("menubar-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("menubar-trigger-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("menubar-trigger-bg-hover", "var(--theme-action-accent-bg)"),
    FamilyToken::new("menubar-trigger-bg-expanded", "var(--theme-action-accent-bg)"),
    FamilyToken::new("menubar-content-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("menubar-content-padding-y", "var(--space-xs)"),
    FamilyToken::new("menubar-content-radius", "var(--radius-md)"),
    FamilyToken::new("menubar-content-shadow", "var(--shadow-lg)"),
    FamilyToken::new("menubar-content-min-width", "var(--layout-width-sm)"),

    // Tree
    FamilyToken::new("tree-gap", "var(--space-xs)"),
    FamilyToken::new("tree-indent", "var(--space-md)"),
    FamilyToken::new("tree-item-height", "var(--space-xl)"),
    FamilyToken::new("tree-item-padding", "var(--space-xs) var(--space-sm)"),
    FamilyToken::new("tree-item-radius", "var(--radius-sm)"),
    FamilyToken::new("tree-item-fg", "var(--theme-surface-fg)"),
    FamilyToken::new("tree-item-bg-hover", "var(--theme-action-accent-bg)"),
    FamilyToken::new("tree-item-bg-selected", "var(--theme-action-accent-bg)"),
    FamilyToken::new("tree-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("tree-icon-size", "var(--space-md)"),
    FamilyToken::new("tree-icon-rotation", "90deg"),
    FamilyToken::new("tree-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("tree-transition-ease", "var(--motion-ease-standard)"),

    // Command
    FamilyToken::new("command-bg", "var(--theme-overlay-bg)"),
    FamilyToken::new("command-fg", "var(--color-popover-foreground)"),
    FamilyToken::new("command-radius", "var(--radius-md)"),
    FamilyToken::new("command-shadow", "var(--shadow-2xl)"),
    FamilyToken::new("command-border-color", "var(--theme-surface-border)"),
    FamilyToken::new("command-border-width", "1px"),
    FamilyToken::new("command-input-height", "var(--size-icon-lg)"),
    FamilyToken::new("command-input-padding", "var(--space-sm) var(--space-md)"),
    FamilyToken::new("command-input-font-size", "var(--font-size-sm)"),
    FamilyToken::new("command-input-border-bottom", "1px solid var(--theme-surface-border)"),
    FamilyToken::new("command-list-padding", "var(--space-sm)"),
    FamilyToken::new("command-list-max-height", "var(--layout-width-md)"),
    FamilyToken::new("command-item-height", "var(--space-2xl)"),
    FamilyToken::new("command-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("command-item-radius", "var(--radius-sm)"),
    FamilyToken::new("command-item-hover-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("command-item-selected-bg", "var(--theme-action-accent-bg)"),
    FamilyToken::new("command-group-heading-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("command-group-heading-font-size", "var(--font-size-xs)"),
    FamilyToken::new("command-group-heading-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("command-separator-color", "var(--theme-surface-border)"),
    FamilyToken::new("command-separator-margin-y", "var(--space-xs)"),
    FamilyToken::new("command-empty-fg", "var(--theme-surface-fg-muted)"),
    FamilyToken::new("command-empty-padding", "var(--space-xl) var(--space-md)"),
    // Command (tokens simplificados faltantes)
    FamilyToken::new("command-gap", "var(--space-xs)"),
    FamilyToken::new("command-padding", "var(--space-xs)"),
    FamilyToken::new("command-item-bg-hover", "var(--theme-action-accent-bg)"),

    // Tree (tokens faltantes)
    FamilyToken::new("tree-indent-depth-1", "var(--space-lg)"),
    FamilyToken::new("tree-item-padding-x", "var(--space-sm)"),
    FamilyToken::new("tree-item-padding-y", "var(--space-xs)"),
    FamilyToken::new("tree-row-height", "var(--space-2xl)"),

];
