// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HEROTITLE_API: ComponentApi = ComponentApi {
    id: "hero-title",
    description: "Hero typography and label components",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HEROSUBTITLE_API: ComponentApi = ComponentApi {
    id: "hero-subtitle",
    description: "Hero typography and label components",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HERODESCRIPTION_API: ComponentApi = ComponentApi {
    id: "hero-description",
    description: "Hero typography and label components",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HEROMEDIA_API: ComponentApi = ComponentApi {
    id: "hero-media",
    description: "Hero typography and label components",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HEROACTIONS_API: ComponentApi = ComponentApi {
    id: "hero-actions",
    description: "Hero typography and label components",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

