// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HEROTITLE_API: ComponentApi = ComponentApi {
    id: "hero-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const HEROSUBTITLE_API: ComponentApi = ComponentApi {
    id: "hero-subtitle",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const HERODESCRIPTION_API: ComponentApi = ComponentApi {
    id: "hero-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

