// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SPLIT_API: ComponentApi = ComponentApi {
    id: "split",
    props: &[
        PropDef { name: "ratio", kind: PropType::String, required: false, default: Some("half"), description: "" },
        PropDef { name: "aside", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "main", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

