// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CODEBLOCK_API: ComponentApi = ComponentApi {
    id: "code-block",
    props: &[
        PropDef { name: "code", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "language", kind: PropType::String, required: false, default: Some("text"), description: "" },
        PropDef { name: "filename", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "show_copy", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "show_line_numbers", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

