// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CODEBLOCK_API: ComponentApi = ComponentApi {
    id: "code-block",
    description: "Syntax-highlighted code display",
    props: &[
        PropDef { name: "code", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "language", kind: PropType::String, required: false, default: Some("text"), description: "Prop value" },
        PropDef { name: "filename", kind: PropType::String, required: false, default: None, description: "Prop value" },
        PropDef { name: "show_line_numbers", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

