// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const BUTTONGROUP_API: ComponentApi = ComponentApi {
    id: "button-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "attached", kind: PropType::String, required: false, default: Some("off"), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

