// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const BREADCRUMB_API: ComponentApi = ComponentApi {
    id: "breadcrumb",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const BREADCRUMBITEM_API: ComponentApi = ComponentApi {
    id: "breadcrumb-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const BREADCRUMBLINK_API: ComponentApi = ComponentApi {
    id: "breadcrumb-link",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const BREADCRUMBPAGE_API: ComponentApi = ComponentApi {
    id: "breadcrumb-page",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const BREADCRUMBSEPARATOR_API: ComponentApi = ComponentApi {
    id: "breadcrumb-separator",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const BREADCRUMBELLIPSIS_API: ComponentApi = ComponentApi {
    id: "breadcrumb-ellipsis",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

