// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const BREADCRUMB_API: ComponentApi = ComponentApi {
    id: "breadcrumb",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const BREADCRUMBITEM_API: ComponentApi = ComponentApi {
    id: "breadcrumb-item",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const BREADCRUMBLINK_API: ComponentApi = ComponentApi {
    id: "breadcrumb-link",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: false, default: None, description: "Navigation target URL" },
        PropDef { name: "state", kind: PropType::Enum(&["inactive", "active"]), required: false, default: Some("inactive"), description: "Loading or visibility state" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const BREADCRUMBPAGE_API: ComponentApi = ComponentApi {
    id: "breadcrumb-page",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const BREADCRUMBSEPARATOR_API: ComponentApi = ComponentApi {
    id: "breadcrumb-separator",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const BREADCRUMBELLIPSIS_API: ComponentApi = ComponentApi {
    id: "breadcrumb-ellipsis",
    description: "Navigation breadcrumb trail",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

