// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HEADER_API: ComponentApi = ComponentApi {
    id: "header",
    props: &[
        PropDef { name: "logo", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "nav", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "center", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "actions", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "bottom", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

