// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HOVERCARD_API: ComponentApi = ComponentApi {
    id: "hover-card",
    description: "Hover card popup",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HOVERCARDTRIGGER_API: ComponentApi = ComponentApi {
    id: "hover-card-trigger",
    description: "Hover card popup",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const HOVERCARDCONTENT_API: ComponentApi = ComponentApi {
    id: "hover-card-content",
    description: "Hover card popup",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
        PropDef { name: "side", kind: PropType::String, required: false, default: Some("top"), description: "Tooltip or popover side" },
    ],
};

