// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HOVERCARD_API: ComponentApi = ComponentApi {
    id: "hover-card",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("closed"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const HOVERCARDTRIGGER_API: ComponentApi = ComponentApi {
    id: "hover-card-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const HOVERCARDCONTENT_API: ComponentApi = ComponentApi {
    id: "hover-card-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "side", kind: PropType::Enum(&["top", "bottom", "left", "right"]), required: false, default: Some("top"), description: "" },
    ],
};

