// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PAGEHEADER_API: ComponentApi = ComponentApi {
    id: "page-header",
    props: &[
        PropDef { name: "breadcrumb", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "subtitle", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "actions", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

