// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PAGEHEADER_API: ComponentApi = ComponentApi {
    id: "page-header",
    description: "Page title and actions header block",
    props: &[
        PropDef { name: "breadcrumb", kind: PropType::Children, required: false, default: None, description: "Breadcrumb navigation slot" },
        PropDef { name: "title", kind: PropType::Children, required: false, default: None, description: "Title slot or text" },
        PropDef { name: "subtitle", kind: PropType::Children, required: false, default: None, description: "Subtitle slot or text" },
        PropDef { name: "actions", kind: PropType::Children, required: false, default: None, description: "Actions region slot" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

