use crate::design::tokens::FamilyToken;

/// FAMILY B — Selection & Menus
/// Components: Accordion, Collapsible, Combobox, ContextMenu, DropdownMenu, Menu, Menubar, Tree, Command
/// Scope: Selection lists, contextual menus, hierarchical navigation

pub const FAMILY_B_SELECTION: &[FamilyToken] = &[
    // Selection foundation
    FamilyToken::new("selection-color", "var(--semantic-brand-solid)"),
    FamilyToken::new("selection-spacing", "var(--space-sm)"),
    FamilyToken::new("selection-hover-opacity", "var(--state-hover-opacity)"),

    // Accordion
    FamilyToken::new("accordion-gap", "var(--space-sm)"),
    FamilyToken::new("accordion-item-border-width", "1px"),
    FamilyToken::new("accordion-item-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("accordion-item-border-radius", "var(--radius-md)"),
    FamilyToken::new("accordion-trigger-bg", "transparent"),
    FamilyToken::new("accordion-trigger-bg-hover", "var(--semantic-surface-hover)"),
    FamilyToken::new("accordion-trigger-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("accordion-trigger-padding-x", "var(--space-md)"),
    FamilyToken::new("accordion-trigger-padding-y", "var(--space-sm)"),
    FamilyToken::new("accordion-trigger-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("accordion-trigger-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("accordion-trigger-transition-ease", "var(--motion-ease-standard)"),
    FamilyToken::new("accordion-content-padding-x", "var(--space-md)"),
    FamilyToken::new("accordion-content-padding-y", "var(--space-sm)"),
    FamilyToken::new("accordion-content-padding-top", "0"),
    FamilyToken::new("accordion-icon-size", "var(--space-md)"),
    FamilyToken::new("accordion-icon-rotation", "180deg"),
    FamilyToken::new("accordion-trigger-fg-active", "var(--semantic-brand-solid)"),
    FamilyToken::new("accordion-content-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("accordion-content-font-size", "var(--font-size-sm)"),
    FamilyToken::new("accordion-icon-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("accordion-icon-transition-ease", "var(--motion-ease-standard)"),

    // Collapsible
    FamilyToken::new("collapsible-gap", "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-bg", "transparent"),
    FamilyToken::new("collapsible-trigger-bg-hover", "var(--semantic-surface-hover)"),
    FamilyToken::new("collapsible-trigger-padding", "var(--space-sm)"),
    FamilyToken::new("collapsible-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("collapsible-content-padding", "var(--space-sm)"),
    FamilyToken::new("collapsible-transition-duration", "var(--motion-duration-normal)"),
    FamilyToken::new("collapsible-transition-ease", "var(--motion-ease-standard)"),

    // Combobox
    FamilyToken::new("combobox-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("combobox-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("combobox-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("combobox-border-width", "1px"),
    FamilyToken::new("combobox-height", "var(--space-2xl)"),
    FamilyToken::new("combobox-padding-x", "var(--space-sm)"),
    FamilyToken::new("combobox-radius", "var(--radius-sm)"),
    FamilyToken::new("combobox-gap", "var(--space-sm)"),
    FamilyToken::new("combobox-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("combobox-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("combobox-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("combobox-popover-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("combobox-popover-padding-y", "var(--space-xs)"),
    FamilyToken::new("combobox-popover-radius", "var(--radius-md)"),
    FamilyToken::new("combobox-popover-shadow", "var(--shadow-lg)"),
    FamilyToken::new("combobox-trigger-height", "var(--space-2xl)"),
    FamilyToken::new("combobox-trigger-padding-x", "var(--space-sm)"),
    FamilyToken::new("combobox-trigger-padding-y", "var(--space-xs)"),
    FamilyToken::new("combobox-trigger-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("combobox-trigger-icon-size", "1rem"),
    FamilyToken::new("combobox-item-height", "var(--space-xl)"),
    FamilyToken::new("combobox-item-padding-x", "var(--space-sm)"),
    FamilyToken::new("combobox-item-padding-y", "var(--space-xs)"),
    FamilyToken::new("combobox-item-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("combobox-item-bg-hover", "var(--semantic-surface-sunken)"),
    FamilyToken::new("combobox-item-bg-selected", "var(--semantic-surface-emphasis)"),
    FamilyToken::new("combobox-item-fg-selected", "var(--semantic-text-on-emphasis)"),
    FamilyToken::new("combobox-item-icon-size", "1rem"),
    FamilyToken::new("combobox-empty-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("combobox-empty-padding", "var(--space-sm)"),
    FamilyToken::new("combobox-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("combobox-transition-ease", "var(--motion-ease-standard)"),

    // ContextMenu
    FamilyToken::new("context-menu-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("context-menu-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("context-menu-padding-y", "var(--space-xs)"),
    FamilyToken::new("context-menu-radius", "var(--radius-md)"),
    FamilyToken::new("context-menu-shadow", "var(--shadow-lg)"),
    FamilyToken::new("context-menu-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("context-menu-border-width", "1px"),
    FamilyToken::new("context-menu-min-width", "var(--layout-width-sm)"),
    FamilyToken::new("context-menu-item-height", "var(--space-xl)"),
    FamilyToken::new("context-menu-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("context-menu-item-hover-bg", "var(--semantic-surface-hover)"),
    FamilyToken::new("context-menu-separator-color", "var(--semantic-surface-border)"),
    FamilyToken::new("context-menu-separator-margin-y", "var(--space-xs)"),
    FamilyToken::new("context-menu-label-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("context-menu-label-font-size", "var(--font-size-xs)"),
    FamilyToken::new("context-menu-label-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("context-menu-shortcut-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("context-menu-shortcut-font-size", "var(--font-size-xs)"),

    // Menu
    FamilyToken::new("menu-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("menu-padding", "var(--space-sm)"),
    FamilyToken::new("menu-gap", "var(--space-xs)"),
    FamilyToken::new("menu-item-height", "var(--font-size-4xl)"),
    FamilyToken::new("menu-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("menu-item-radius", "var(--radius-sm)"),
    FamilyToken::new("menu-item-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("menu-item-bg-hover", "var(--semantic-surface-hover)"),
    FamilyToken::new("menu-item-bg-active", "var(--semantic-surface-hover)"),
    FamilyToken::new("menu-item-fg-active", "var(--semantic-text-primary)"),
    FamilyToken::new("menu-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("menu-item-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("menu-item-transition-ease", "var(--motion-ease-standard)"),

    // Menubar
    FamilyToken::new("menubar-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("menubar-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("menubar-border-width", "0 0 1px 0"),
    FamilyToken::new("menubar-padding", "var(--space-sm)"),
    FamilyToken::new("menubar-gap", "var(--space-xs)"),
    FamilyToken::new("menubar-trigger-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("menubar-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("menubar-trigger-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("menubar-trigger-bg-hover", "var(--semantic-surface-hover)"),
    FamilyToken::new("menubar-trigger-bg-expanded", "var(--semantic-surface-hover)"),
    FamilyToken::new("menubar-item-bg-active", "var(--semantic-brand-solid)"),
    FamilyToken::new("menubar-item-fg-active", "var(--color-primary-foreground)"),
    FamilyToken::new("menubar-content-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("menubar-content-padding-y", "var(--space-xs)"),
    FamilyToken::new("menubar-content-radius", "var(--radius-md)"),
    FamilyToken::new("menubar-content-shadow", "var(--shadow-lg)"),
    FamilyToken::new("menubar-content-min-width", "var(--layout-width-sm)"),

    // Tree (has interactive version)
    FamilyToken::new("tree-gap", "var(--space-xs)"),
    FamilyToken::new("tree-indent", "var(--space-md)"),
    FamilyToken::new("tree-item-height", "var(--space-xl)"),
    FamilyToken::new("tree-item-padding", "var(--space-xs) var(--space-sm)"),
    FamilyToken::new("tree-item-radius", "var(--radius-sm)"),
    FamilyToken::new("tree-item-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("tree-item-bg-hover", "var(--semantic-surface-hover)"),
    FamilyToken::new("tree-item-bg-selected", "var(--semantic-surface-hover)"),
    FamilyToken::new("tree-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("tree-icon-size", "var(--space-md)"),
    FamilyToken::new("tree-icon-rotation", "90deg"),
    FamilyToken::new("tree-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("tree-transition-ease", "var(--motion-ease-standard)"),

    // Command
    FamilyToken::new("command-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("command-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("command-radius", "var(--radius-md)"),
    FamilyToken::new("command-shadow", "var(--shadow-2xl)"),
    FamilyToken::new("command-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("command-border-width", "1px"),
    FamilyToken::new("command-input-height", "var(--size-icon-lg)"),
    FamilyToken::new("command-input-padding", "var(--space-sm) var(--space-md)"),
    FamilyToken::new("command-input-font-size", "var(--font-size-sm)"),
    FamilyToken::new("command-input-border-bottom", "1px solid var(--semantic-surface-border)"),
    FamilyToken::new("command-list-padding", "var(--space-sm)"),
    FamilyToken::new("command-list-max-height", "var(--layout-width-md)"),
    FamilyToken::new("command-item-height", "var(--space-2xl)"),
    FamilyToken::new("command-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("command-item-radius", "var(--radius-sm)"),
    FamilyToken::new("command-item-hover-bg", "var(--semantic-surface-hover)"),
    FamilyToken::new("command-item-selected-bg", "var(--semantic-surface-hover)"),
    FamilyToken::new("command-group-heading-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("command-group-heading-font-size", "var(--font-size-xs)"),
    FamilyToken::new("command-group-heading-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("command-separator-color", "var(--semantic-surface-border)"),
    FamilyToken::new("command-separator-margin-y", "var(--space-xs)"),
    FamilyToken::new("command-empty-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("command-empty-padding", "var(--space-xl) var(--space-md)"),
];
