use crate::design::tokens::FamilyToken;

/// FAMILY C — Forms & Inputs
/// Components: Button, Field, Input, Select, Checkbox, Switch, Toggle, Slider, Calendar, ColorPicker, Label, RadioGroup, Textarea
/// Scope: Data entry, validation, form composition

pub const FAMILY_C_FORMS: &[FamilyToken] = &[
    // Forms foundation
    FamilyToken::new("forms-color", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("forms-radius", "var(--radius-sm)"),
    FamilyToken::new("forms-padding-y", "var(--space-sm)"),
    FamilyToken::new("forms-disabled-opacity", "var(--state-disabled-opacity)"),

    // Validation
    FamilyToken::new("validation-error", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("validation-warning", "var(--semantic-feedback-warning-text)"),
    FamilyToken::new("validation-success", "var(--semantic-feedback-success-text)"),

    // Button (has interactive version)
    FamilyToken::new("button-height", "var(--space-2xl)"),
    FamilyToken::new("button-padding-x", "var(--space-md)"),
    FamilyToken::new("button-padding-y", "var(--space-sm)"),
    FamilyToken::new("button-radius", "var(--radius-sm)"),
    FamilyToken::new("button-gap", "var(--space-sm)"),

    FamilyToken::new("button-ghost-bg", "transparent"),
    FamilyToken::new("button-ghost-bg-hover", "var(--semantic-action-secondary-hover)"),
    FamilyToken::new("button-ghost-fg", "var(--semantic-action-secondary-fg)"),

    // Button — primary (solid)
    FamilyToken::new("button-primary-bg", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("button-primary-fg", "var(--semantic-action-primary-fg)"),
    FamilyToken::new("button-primary-bg-hover", "var(--semantic-action-primary-hover)"),
    FamilyToken::new("button-primary-bg-active", "var(--semantic-action-primary-active)"),


    // Button — outline
    FamilyToken::new("button-outline-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("button-outline-border", "var(--semantic-surface-border)"),
    
    // Button — ghost
    FamilyToken::new("button-ghost-fg", "var(--semantic-text-secondary)"),

    // Button — danger
    FamilyToken::new("button-danger-bg", "var(--semantic-error-bg)"),
    FamilyToken::new("button-danger-fg", "var(--semantic-error-fg)"),

    // Button — success
    FamilyToken::new("button-success-bg", "var(--semantic-success-bg)"),
    FamilyToken::new("button-success-fg", "var(--semantic-success-fg)"),

    // Field
    FamilyToken::new("field-border", "1px solid var(--semantic-surface-border)"),
    FamilyToken::new("field-height", "var(--space-2xl)"),
    FamilyToken::new("field-padding", "var(--space-sm)"),
    FamilyToken::new("field-gap", "var(--space-sm)"),
    FamilyToken::new("field-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("field-label-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("field-label-fg-disabled", "var(--semantic-text-disabled)"),
    FamilyToken::new("field-label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-label-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("field-description-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("field-description-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-description-line-height", "var(--line-height-normal)"),
    FamilyToken::new("field-error-fg", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("field-error-font-size", "var(--font-size-sm)"),
    FamilyToken::new("field-error-list-gap", "var(--space-xs)"),
    FamilyToken::new("field-validation-error-fg", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("field-validation-success-fg", "var(--semantic-feedback-success-text)"),
    FamilyToken::new("field-validation-warning-fg", "var(--semantic-feedback-warning-text)"),
    FamilyToken::new("field-separator-color", "var(--semantic-surface-border)"),
    FamilyToken::new("field-separator-label-fg", "var(--semantic-text-secondary)"),
    FamilyToken::new("field-separator-label-padding-x", "var(--space-sm)"),
    FamilyToken::new("field-separator-margin-y", "var(--space-md)"),
    FamilyToken::new("field-orientation-gap-horizontal", "var(--space-sm)"),
    FamilyToken::new("field-orientation-gap-vertical", "var(--space-xs)"),

    // Input (has interactive version)
    FamilyToken::new("input-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("input-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("input-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("input-border-width", "1px"),
    FamilyToken::new("input-height", "var(--space-2xl)"),
    FamilyToken::new("input-padding-x", "var(--space-sm)"),
    FamilyToken::new("input-padding-y", "var(--space-sm)"),
    FamilyToken::new("input-radius", "var(--radius-sm)"),
    FamilyToken::new("input-font-family", "inherit"),
    FamilyToken::new("input-font-size", "var(--font-size-sm)"),
    FamilyToken::new("input-font-weight", "var(--font-weight-normal)"),
    FamilyToken::new("input-line-height", "var(--line-height-normal)"),
    FamilyToken::new("input-placeholder", "var(--semantic-text-secondary)"),
    FamilyToken::new("input-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("input-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("input-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("input-focus-ring-offset", "var(--state-focus-ring-offset)"),
    FamilyToken::new("input-error-border", "var(--semantic-feedback-danger-border)"),
    FamilyToken::new("input-success-border", "var(--semantic-feedback-success-border)"),
    FamilyToken::new("input-sm-height", "var(--size-input-sm)"),
    FamilyToken::new("input-sm-font-size", "var(--font-size-xs)"),
    FamilyToken::new("input-md-height", "var(--space-2xl)"),
    FamilyToken::new("input-lg-height", "var(--size-icon-lg)"),
    FamilyToken::new("input-lg-font-size", "var(--font-size-base)"),
    FamilyToken::new("input-group-gap", "0"),
    FamilyToken::new("input-group-radius-merge", "0"),
    FamilyToken::new("input-group-align", "center"),

    // Input OTP (has interactive version)
    FamilyToken::new("input-otp-slot-size", "var(--space-2xl)"),
    FamilyToken::new("input-otp-slot-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("input-otp-slot-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("input-otp-slot-border", "1px solid var(--semantic-surface-border)"),
    FamilyToken::new("input-otp-slot-radius", "var(--radius-sm)"),
    FamilyToken::new("input-otp-slot-active-bg", "var(--semantic-action-secondary-bg)"),
    FamilyToken::new("input-otp-slot-active-border", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("input-otp-slot-disabled-bg", "var(--semantic-surface-disabled)"),
    FamilyToken::new("input-otp-slot-disabled-fg", "var(--semantic-text-disabled)"),
    FamilyToken::new("input-otp-font-family", "monospace"),
    FamilyToken::new("input-otp-font-size", "var(--font-size-base)"),
    FamilyToken::new("input-otp-font-weight", "var(--font-weight-semibold)"),

    // Textarea (has interactive version)
    FamilyToken::new("textarea-min-height", "var(--size-textarea-min)"),
    FamilyToken::new("textarea-max-height", "var(--layout-width-md)"),
    FamilyToken::new("textarea-resize", "vertical"),

    // Select
    FamilyToken::new("select-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("select-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("select-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("select-border-width", "1px"),
    FamilyToken::new("select-height", "var(--space-2xl)"),
    FamilyToken::new("select-padding-x", "var(--space-sm)"),
    FamilyToken::new("select-radius", "var(--radius-sm)"),
    FamilyToken::new("select-gap", "var(--space-sm)"),
    FamilyToken::new("select-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("select-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("select-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("select-focus-ring-offset", "var(--state-focus-ring-offset)"),
    FamilyToken::new("select-content-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("select-content-padding-y", "var(--space-xs)"),
    FamilyToken::new("select-content-radius", "var(--radius-md)"),
    FamilyToken::new("select-content-shadow", "var(--shadow-lg)"),
    FamilyToken::new("select-content-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("select-content-border-width", "1px"),
    FamilyToken::new("select-item-height", "var(--size-input-sm)"),
    FamilyToken::new("select-item-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("select-item-hover-bg", "var(--semantic-action-secondary-hover)"),
    FamilyToken::new("select-item-selected-bg", "var(--semantic-brand-solid)"),
    FamilyToken::new("select-item-selected-fg", "var(--color-primary-foreground)"),
    FamilyToken::new("select-separator-color", "var(--semantic-surface-border)"),
    FamilyToken::new("select-separator-height", "1px"),
    FamilyToken::new("select-separator-margin-y", "var(--space-xs)"),

    // Checkbox (has interactive version)
    FamilyToken::new("checkbox-size", "var(--font-size-xl)"),
    FamilyToken::new("checkbox-radius", "var(--radius-xs)"),
    FamilyToken::new("checkbox-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("checkbox-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("checkbox-border-width", "1px"),
    FamilyToken::new("checkbox-checked-bg", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("checkbox-checked-border-color", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("checkbox-hover-border-color", "var(--semantic-action-primary-hover)"),
    FamilyToken::new("checkbox-check-color", "var(--semantic-action-primary-fg)"),
    FamilyToken::new("checkbox-check-font-size", "var(--font-size-xs)"),
    FamilyToken::new("checkbox-disabled-opacity", "var(--state-disabled-opacity)"),

    // Switch (has interactive version)
    FamilyToken::new("switch-width", "var(--size-switch-width)"),
    FamilyToken::new("switch-height", "var(--space-lg)"),
    FamilyToken::new("switch-radius", "var(--radius-full)"),
    FamilyToken::new("switch-track-bg", "var(--semantic-surface-sunken)"),
    FamilyToken::new("switch-track-bg-checked", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("switch-thumb-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("switch-thumb-size", "var(--font-size-xl)"),
    FamilyToken::new("switch-thumb-radius", "var(--radius-full)"),
    FamilyToken::new("switch-thumb-translate-unchecked", "var(--space-xs)"),
    FamilyToken::new("switch-thumb-translate-checked", "var(--size-switch-translate)"),
    FamilyToken::new("switch-disabled-opacity", "var(--state-disabled-opacity)"),

    // Toggle
    FamilyToken::new("toggle-padding", "var(--space-sm) var(--space-sm)"),
    FamilyToken::new("toggle-radius", "var(--radius-sm)"),
    FamilyToken::new("toggle-border-width", "1px"),
    FamilyToken::new("toggle-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("toggle-hover-bg", "var(--semantic-action-secondary-hover)"),
    FamilyToken::new("toggle-active-bg", "var(--semantic-action-secondary-active)"),
    FamilyToken::new("toggle-active-fg", "var(--semantic-action-secondary-fg)"),
    FamilyToken::new("toggle-group-gap", "var(--space-xs)"),
    FamilyToken::new("toggle-group-direction", "row"),
    FamilyToken::new("toggle-group-wrap", "nowrap"),

    // Slider (has interactive version)
    FamilyToken::new("slider-height", "var(--font-size-xl)"),
    FamilyToken::new("slider-padding", "0"),
    FamilyToken::new("slider-track-bg", "var(--semantic-surface-sunken)"),
    FamilyToken::new("slider-track-height", "var(--space-sm)"),
    FamilyToken::new("slider-track-radius", "var(--radius-full)"),
    FamilyToken::new("slider-range-bg", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("slider-thumb-bg", "var(--semantic-surface-base)"),
    FamilyToken::new("slider-thumb-size", "var(--font-size-xl)"),
    FamilyToken::new("slider-thumb-radius", "var(--radius-full)"),
    FamilyToken::new("slider-thumb-border-color", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("slider-thumb-border-width", "2px"),
    FamilyToken::new("slider-thumb-focus-ring-color", "var(--state-focus-ring-color)"),
    FamilyToken::new("slider-thumb-focus-ring-width", "var(--state-focus-ring-width)"),
    FamilyToken::new("slider-disabled-opacity", "var(--state-disabled-opacity)"),
    FamilyToken::new("slider-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("slider-transition-ease", "var(--motion-ease-standard)"),

    // Calendar
    FamilyToken::new("calendar-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("calendar-padding", "var(--space-md)"),
    FamilyToken::new("calendar-radius", "var(--radius-md)"),
    FamilyToken::new("calendar-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("calendar-border-width", "1px"),
    FamilyToken::new("calendar-header-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("calendar-header-font-size", "var(--font-size-sm)"),
    FamilyToken::new("calendar-header-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("calendar-header-gap", "var(--space-sm)"),
    FamilyToken::new("calendar-grid-gap", "var(--space-xs)"),
    FamilyToken::new("calendar-cell-size", "var(--size-cell)"),
    FamilyToken::new("calendar-cell-radius", "var(--radius-sm)"),
    FamilyToken::new("calendar-cell-font-size", "var(--font-size-sm)"),
    FamilyToken::new("calendar-cell-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("calendar-cell-fg-disabled", "var(--semantic-text-disabled)"),
    FamilyToken::new("calendar-cell-fg-selected", "var(--semantic-action-primary-fg)"),
    FamilyToken::new("calendar-cell-bg-hover", "var(--semantic-action-secondary-hover)"),
    FamilyToken::new("calendar-cell-bg-selected", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("calendar-cell-bg-disabled", "transparent"),
    FamilyToken::new("calendar-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("calendar-transition-ease", "var(--motion-ease-standard)"),

    // ColorPicker (has interactive version)
    FamilyToken::new("color-picker-size", "var(--size-color-picker)"),
    FamilyToken::new("color-picker-radius", "var(--radius-md)"),
    FamilyToken::new("color-picker-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("color-picker-border-width", "1px"),
    FamilyToken::new("color-picker-trigger-size", "var(--space-2xl)"),
    FamilyToken::new("color-picker-trigger-radius", "var(--radius-sm)"),
    FamilyToken::new("color-picker-swatch-size", "var(--size-input-sm)"),
    FamilyToken::new("color-picker-swatch-radius", "var(--radius-xs)"),
    FamilyToken::new("color-picker-swatch-border-width", "1px"),
    FamilyToken::new("color-picker-swatch-border-color", "var(--semantic-surface-border)"),
    FamilyToken::new("color-picker-swatch-border-color-selected", "var(--semantic-action-primary-bg)"),
    FamilyToken::new("color-picker-panel-bg", "var(--semantic-surface-elevated)"),
    FamilyToken::new("color-picker-panel-padding", "var(--space-md)"),
    FamilyToken::new("color-picker-panel-radius", "var(--radius-md)"),
    FamilyToken::new("color-picker-panel-shadow", "var(--shadow-lg)"),
    FamilyToken::new("color-picker-transition-duration", "var(--motion-duration-fast)"),
    FamilyToken::new("color-picker-transition-ease", "var(--motion-ease-standard)"),

    // Label
    FamilyToken::new("label-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("label-fg-muted", "var(--semantic-text-secondary)"),
    FamilyToken::new("label-fg-disabled", "var(--semantic-text-disabled)"),
    FamilyToken::new("label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("label-font-weight", "var(--font-weight-medium)"),
    FamilyToken::new("label-line-height", "var(--line-height-normal)"),
    FamilyToken::new("label-margin-bottom", "var(--space-sm)"),

    // RadioGroup
    FamilyToken::new("radio-group-gap", "var(--space-sm)"),
    FamilyToken::new("radio-group-item-gap", "var(--space-sm)"),
    FamilyToken::new("radio-group-label-fg", "var(--semantic-text-primary)"),
    FamilyToken::new("radio-group-label-fg-disabled", "var(--semantic-text-disabled)"),
    FamilyToken::new("radio-group-label-font-size", "var(--font-size-sm)"),
    FamilyToken::new("radio-group-label-font-weight", "var(--font-weight-medium)"),

    // Form
    FamilyToken::new("form-gap", "var(--space-lg)"),
    FamilyToken::new("form-actions-gap", "var(--space-sm)"),
    FamilyToken::new("form-actions-justify", "flex-end"),
    FamilyToken::new("form-actions-padding-top", "var(--space-lg)"),
    FamilyToken::new("form-actions-border-top", "1px solid var(--semantic-surface-border)"),
    // Form Error Summary (has interactive version)
    FamilyToken::new("form-error-summary-bg", "var(--semantic-error-surface)"),
    FamilyToken::new("form-error-summary-padding-x", "var(--space-md)"),
    FamilyToken::new("form-error-summary-padding-y", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-radius", "var(--radius-md)"),
    FamilyToken::new("form-error-summary-border-color", "var(--semantic-feedback-danger-border)"),
    FamilyToken::new("form-error-summary-border-width", "1px"),
    FamilyToken::new("form-error-summary-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-title-fg", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("form-error-summary-title-font-size", "var(--font-size-sm)"),
    FamilyToken::new("form-error-summary-title-font-weight", "var(--font-weight-semibold)"),
    FamilyToken::new("form-error-summary-list-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-item-fg", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("form-error-summary-item-font-size", "var(--font-size-sm)"),
    FamilyToken::new("form-error-summary-item-gap", "var(--space-sm)"),
    FamilyToken::new("form-error-summary-item-icon-color", "var(--semantic-feedback-danger-text)"),
    FamilyToken::new("form-error-summary-item-icon-size", "var(--space-md)"),
    // Button Group
    FamilyToken::new("button-group-gap", "0"),
    FamilyToken::new("button-group-radius", "var(--radius-md)"),

];
