// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TABLEOFCONTENTS_API: ComponentApi = ComponentApi {
    id: "table-of-contents",
    props: &[
        PropDef { name: "items", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "mode", kind: PropType::String, required: false, default: Some("simple"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "title", kind: PropType::String, required: false, default: Some("On this page"), description: "" },
    ],
};

