// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const NAVIGATIONMENU_API: ComponentApi = ComponentApi {
    id: "navigation-menu",
    description: "Navigation menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const NAVIGATIONMENUITEM_API: ComponentApi = ComponentApi {
    id: "navigation-menu-item",
    description: "Navigation menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const NAVIGATIONMENUCONTENT_API: ComponentApi = ComponentApi {
    id: "navigation-menu-content",
    description: "Navigation menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

