// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const THREEPANELAYOUT_API: ComponentApi = ComponentApi {
    id: "three-pane-layout",
    description: "Three-column layout with left nav, center content and right aside",
    props: &[
        PropDef { name: "left", kind: PropType::Children, required: false, default: None, description: "Left panel slot" },
        PropDef { name: "center", kind: PropType::Children, required: false, default: None, description: "Center panel slot" },
        PropDef { name: "right", kind: PropType::Children, required: false, default: None, description: "Right panel slot" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

