// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ICONBUTTON_API: ComponentApi = ComponentApi {
    id: "icon-button",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_label", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "ghost", "outline", "solid", "destructive"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "loading", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

