// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ICONBUTTON_API: ComponentApi = ComponentApi {
    id: "icon-button",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_label", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("md"), description: "" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "loading", kind: PropType::String, required: false, default: Some("idle"), description: "" },
        PropDef { name: "pressed", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

