// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CHECKBOX_API: ComponentApi = ComponentApi {
    id: "checkbox",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "checked", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CHECKBOXREACTIVE_API: ComponentApi = ComponentApi {
    id: "checkbox-reactive",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "checked", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

