#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../.."

echo "📝 Generating canonrs.css entry point..."

OUTPUT="canonrs-ui/styles/canonrs.css"

cat > "$OUTPUT" << 'EOF'
/* 🔒 AUTO-GENERATED - DO NOT EDIT */
/* Generated by scripts/core/generate-canonrs-entry.sh */

/* 1. Themes gerados (--color-*) */
@import "./.generated/themes.css";

/* 2. Tokens base físicos */
@import "./tokens/base/globals.css";
@import "./tokens/base/core.css";

/* 3. Theme ativo (runtime conditional) */
@import "./themes/dark.css";
@import "./themes/light.css";

/* 4. Semantic mapping (neutro) */
@import "./tokens/semantic.css";

/* 5. Tokens base UI */
@import "./tokens/base/ui.css";
@import "./tokens/base/layout.css";
@import "./tokens/base/blocks.css";

/* 6. Families gerados */
EOF

for family in $(ls canonrs-ui/styles/.generated/family-*.css 2>/dev/null | sort); do
  echo "@import \"./$(basename "$(dirname "$family")")/$(basename "$family")\";" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'EOF'

/* 7. Variants */
EOF

for variant in $(ls canonrs-ui/styles/variants/*.css 2>/dev/null | sort); do
  echo "@import \"./variants/$(basename "$variant")\";" >> "$OUTPUT"
done

cat >> "$OUTPUT" << 'EOF'

/* 8. UI components */
EOF

for ui in $(ls canonrs-ui/styles/ui/*.css 2>/dev/null | sort); do
  echo "@import \"./ui/$(basename "$ui")\";" >> "$OUTPUT"
done

echo "✅ Generated: $OUTPUT ($(wc -l < "$OUTPUT") lines)"
