// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const STACK_API: ComponentApi = ComponentApi {
    id: "stack",
    props: &[
        PropDef { name: "direction", kind: PropType::String, required: false, default: Some("vertical"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "items", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

