// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SHEET_API: ComponentApi = ComponentApi {
    id: "sheet",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "side", kind: PropType::Enum(&["right", "left", "top", "bottom"]), required: false, default: Some("right"), description: "" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("closed"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SHEETOVERLAY_API: ComponentApi = ComponentApi {
    id: "sheet-overlay",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SHEETCONTENT_API: ComponentApi = ComponentApi {
    id: "sheet-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_labelledby", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "aria_describedby", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const SHEETTRIGGER_API: ComponentApi = ComponentApi {
    id: "sheet-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

