// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{InlineNoticeVariant}; 

pub const INLINENOTICE_API: ComponentApi = ComponentApi {
    id: "inline-notice",
    description: "Inline notice message",
    props: &[
        PropDef { name: "content", kind: PropType::String, required: false, default: None, description: "Content region slot" },
        PropDef { name: "icon", kind: PropType::String, required: false, default: None, description: "Prop value" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

