// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CAROUSEL_API: ComponentApi = ComponentApi {
    id: "carousel",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "initial_index", kind: PropType::Number, required: false, default: Some("0"), description: "" },
        PropDef { name: "autoplay", kind: PropType::String, required: false, default: Some("off"), description: "" },
        PropDef { name: "interval", kind: PropType::Number, required: false, default: Some("5000"), description: "" },
        PropDef { name: "loop_state", kind: PropType::String, required: false, default: Some("on"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CAROUSELTRACK_API: ComponentApi = ComponentApi {
    id: "carousel-track",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CAROUSELITEM_API: ComponentApi = ComponentApi {
    id: "carousel-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "active", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

pub const CAROUSELPREV_API: ComponentApi = ComponentApi {
    id: "carousel-prev",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CAROUSELNEXT_API: ComponentApi = ComponentApi {
    id: "carousel-next",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CAROUSELINDICATORS_API: ComponentApi = ComponentApi {
    id: "carousel-indicators",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const CAROUSELDOT_API: ComponentApi = ComponentApi {
    id: "carousel-dot",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "active", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

