// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOOLTIPPROVIDER_API: ComponentApi = ComponentApi {
    id: "tooltip-provider",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "delay_open", kind: PropType::Number, required: false, default: Some("400"), description: "" },
        PropDef { name: "delay_close", kind: PropType::Number, required: false, default: Some("100"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TOOLTIP_API: ComponentApi = ComponentApi {
    id: "tooltip",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("closed"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TOOLTIPTRIGGER_API: ComponentApi = ComponentApi {
    id: "tooltip-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "tooltip_id", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TOOLTIPCONTENT_API: ComponentApi = ComponentApi {
    id: "tooltip-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("closed"), description: "" },
        PropDef { name: "side", kind: PropType::Enum(&["top", "bottom", "left", "right"]), required: false, default: Some("top"), description: "" },
        PropDef { name: "tooltip_id", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

