// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const STATCARD_API: ComponentApi = ComponentApi {
    id: "stat-card",
    props: &[
        PropDef { name: "trend", kind: PropType::String, required: false, default: Some("neutral"), description: "" },
        PropDef { name: "icon", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "change", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

