// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{InputVariant, InputSize}; 

pub const INPUT_API: ComponentApi = ComponentApi {
    id: "input",
    description: "Text input field",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "input_type", kind: PropType::String, required: false, default: Some("text"), description: "HTML input type attribute" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "Form field name" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "placeholder", kind: PropType::String, required: false, default: Some(""), description: "Placeholder text" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some(""), description: "Accessible label for screen readers" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("md"), description: "Size variant of the component" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "Whether the component is disabled" },
    ],
};

