// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LINK_API: ComponentApi = ComponentApi {
    id: "link",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "href", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "muted", "underline"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "external", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

