// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ACCORDION_API: ComponentApi = ComponentApi {
    id: "accordion",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "selection", kind: PropType::Enum(&["single", "multiple"]), required: false, default: Some("single"), description: "" },
        PropDef { name: "collapsible", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const ACCORDIONITEM_API: ComponentApi = ComponentApi {
    id: "accordion-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "default_open", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

pub const ACCORDIONTRIGGER_API: ComponentApi = ComponentApi {
    id: "accordion-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const ACCORDIONCONTENT_API: ComponentApi = ComponentApi {
    id: "accordion-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "open", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

