// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PULSE_API: ComponentApi = ComponentApi {
    id: "pulse",
    description: "Pulse animation wrapper",
    props: &[
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("medium"), description: "Size variant of the component" },
        PropDef { name: "speed", kind: PropType::String, required: false, default: Some("normal"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

