// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PULSE_API: ComponentApi = ComponentApi {
    id: "pulse",
    props: &[
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "" },
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("medium"), description: "" },
        PropDef { name: "speed", kind: PropType::String, required: false, default: Some("normal"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

