pub struct SemanticMapping {
    pub token: &'static str,
    pub light_value: &'static str,
    pub dark_value: &'static str,
}

pub const SEMANTIC_MAPPINGS: &[SemanticMapping] = &[
    SemanticMapping {
        token: "color-background",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-neutral-950)",
    },
    SemanticMapping {
        token: "color-foreground",
        light_value: "var(--primitive-neutral-950)",
        dark_value: "var(--primitive-neutral-50)",
    },
    SemanticMapping {
        token: "color-card",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-neutral-900)",
    },
    SemanticMapping {
        token: "color-border",
        light_value: "var(--primitive-neutral-200)",
        dark_value: "var(--primitive-neutral-800)",
    },
    SemanticMapping {
        token: "color-muted",
        light_value: "var(--primitive-neutral-100)",
        dark_value: "var(--primitive-neutral-800)",
    },
    SemanticMapping {
        token: "color-muted-hsl",
        light_value: "var(--primitive-neutral-100)",
        dark_value: "var(--primitive-neutral-800)",
    },
    SemanticMapping {
        token: "color-muted-foreground",
        light_value: "var(--primitive-neutral-500)",
        dark_value: "var(--primitive-neutral-400)",
    },
    SemanticMapping {
        token: "color-primary",
        light_value: "var(--primitive-amber-500)",
        dark_value: "var(--primitive-amber-500)",
    },
    SemanticMapping {
        token: "color-primary-foreground",
        light_value: "var(--primitive-black)",
        dark_value: "var(--primitive-black)",
    },
    SemanticMapping {
        token: "color-accent",
        light_value: "var(--primitive-amber-500)",
        dark_value: "var(--primitive-amber-500)",
    },
    SemanticMapping {
        token: "color-warning",
        light_value: "var(--primitive-amber-500)",
        dark_value: "var(--primitive-amber-600)",
    },
    SemanticMapping {
        token: "color-success",
        light_value: "var(--primitive-green-600)",
        dark_value: "var(--primitive-green-500)",
    },
    SemanticMapping {
        token: "color-destructive",
        light_value: "var(--primitive-red-600)",
        dark_value: "var(--primitive-red-500)",
    },
    SemanticMapping {
        token: "color-bg-elevated",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-neutral-900)",
    },
    SemanticMapping {
        token: "color-bg-emphasis",
        light_value: "var(--primitive-neutral-100)",
        dark_value: "var(--primitive-neutral-800)",
    },
    SemanticMapping {
        token: "color-bg-muted",
        light_value: "var(--primitive-neutral-50)",
        dark_value: "var(--primitive-neutral-900)",
    },
    SemanticMapping {
        token: "color-bg-surface",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-neutral-950)",
    },
    SemanticMapping {
        token: "color-border-default",
        light_value: "var(--primitive-neutral-200)",
        dark_value: "var(--primitive-neutral-800)",
    },
    SemanticMapping {
        token: "color-border-emphasis",
        light_value: "var(--primitive-neutral-300)",
        dark_value: "var(--primitive-neutral-700)",
    },
    SemanticMapping {
        token: "color-border-muted",
        light_value: "var(--primitive-neutral-100)",
        dark_value: "var(--primitive-neutral-900)",
    },
    SemanticMapping {
        token: "color-fg-default",
        light_value: "var(--primitive-neutral-950)",
        dark_value: "var(--primitive-neutral-50)",
    },
    SemanticMapping {
        token: "color-fg-emphasis",
        light_value: "var(--primitive-black)",
        dark_value: "var(--primitive-white)",
    },
    SemanticMapping {
        token: "color-fg-muted",
        light_value: "var(--primitive-neutral-500)",
        dark_value: "var(--primitive-neutral-400)",
    },
    SemanticMapping {
        token: "color-fg-subtle",
        light_value: "var(--primitive-neutral-400)",
        dark_value: "var(--primitive-neutral-600)",
    },
    SemanticMapping {
        token: "color-fg-on-emphasis",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-black)",
    },
    SemanticMapping {
        token: "color-danger-bg",
        light_value: "var(--primitive-red-500)",
        dark_value: "var(--primitive-red-600)",
    },
    SemanticMapping {
        token: "color-danger-fg",
        light_value: "var(--primitive-red-600)",
        dark_value: "var(--primitive-red-500)",
    },
    SemanticMapping {
        token: "color-success-bg",
        light_value: "var(--primitive-green-500)",
        dark_value: "var(--primitive-green-600)",
    },
    SemanticMapping {
        token: "color-success-fg",
        light_value: "var(--primitive-green-600)",
        dark_value: "var(--primitive-green-500)",
    },
    SemanticMapping {
        token: "color-success-border",
        light_value: "var(--primitive-green-600)",
        dark_value: "var(--primitive-green-500)",
    },
    SemanticMapping {
        token: "color-primary-bg",
        light_value: "var(--primitive-amber-500)",
        dark_value: "var(--primitive-amber-600)",
    },
    SemanticMapping {
        token: "color-primary-fg",
        light_value: "var(--primitive-amber-600)",
        dark_value: "var(--primitive-amber-500)",
    },
    SemanticMapping {
        token: "color-primary-border",
        light_value: "var(--primitive-amber-500)",
        dark_value: "var(--primitive-amber-600)",
    },
    SemanticMapping {
        token: "color-popover",
        light_value: "var(--primitive-white)",
        dark_value: "var(--primitive-neutral-900)",
    },
    SemanticMapping { token: "space-2xs", light_value: "var(--primitive-space-0-5)", dark_value: "var(--primitive-space-0-5)" },
    SemanticMapping { token: "space-xs", light_value: "var(--primitive-space-xs)", dark_value: "var(--primitive-space-xs)" },
    SemanticMapping { token: "space-sm", light_value: "var(--primitive-space-sm)", dark_value: "var(--primitive-space-sm)" },
    SemanticMapping { token: "space-md", light_value: "var(--primitive-space-md)", dark_value: "var(--primitive-space-md)" },
    SemanticMapping { token: "space-lg", light_value: "var(--primitive-space-lg)", dark_value: "var(--primitive-space-lg)" },
    SemanticMapping { token: "space-xl", light_value: "var(--primitive-space-xl)", dark_value: "var(--primitive-space-xl)" },
    SemanticMapping { token: "space-2xl", light_value: "var(--primitive-space-2xl)", dark_value: "var(--primitive-space-2xl)" },
    SemanticMapping { token: "space-3xl", light_value: "var(--primitive-space-3xl)", dark_value: "var(--primitive-space-3xl)" },
    SemanticMapping { token: "radius-sm", light_value: "var(--primitive-radius-sm)", dark_value: "var(--primitive-radius-sm)" },
    SemanticMapping { token: "radius-md", light_value: "var(--primitive-radius-md)", dark_value: "var(--primitive-radius-md)" },
    SemanticMapping { token: "radius-lg", light_value: "var(--primitive-radius-lg)", dark_value: "var(--primitive-radius-lg)" },
    SemanticMapping { token: "radius-xl", light_value: "var(--primitive-radius-xl)", dark_value: "var(--primitive-radius-xl)" },
    SemanticMapping { token: "radius-2xl", light_value: "var(--primitive-radius-2xl)", dark_value: "var(--primitive-radius-2xl)" },
    SemanticMapping { token: "radius-full", light_value: "var(--primitive-radius-full)", dark_value: "var(--primitive-radius-full)" },
    SemanticMapping { token: "shadow-sm", light_value: "var(--primitive-shadow-sm)", dark_value: "var(--primitive-shadow-sm)" },
    SemanticMapping { token: "shadow-md", light_value: "var(--primitive-shadow-md)", dark_value: "var(--primitive-shadow-md)" },
    SemanticMapping { token: "shadow-lg", light_value: "var(--primitive-shadow-lg)", dark_value: "var(--primitive-shadow-lg)" },
    SemanticMapping { token: "shadow-xl", light_value: "var(--primitive-shadow-xl)", dark_value: "var(--primitive-shadow-xl)" },
    SemanticMapping { token: "font-family-sans", light_value: "var(--primitive-font-sans)", dark_value: "var(--primitive-font-sans)" },
    SemanticMapping { token: "font-family-mono", light_value: "var(--primitive-font-mono)", dark_value: "var(--primitive-font-mono)" },
    SemanticMapping { token: "font-size-xs", light_value: "var(--primitive-font-size-xs)", dark_value: "var(--primitive-font-size-xs)" },
    SemanticMapping { token: "font-size-sm", light_value: "var(--primitive-font-size-sm)", dark_value: "var(--primitive-font-size-sm)" },
    SemanticMapping { token: "font-size-md", light_value: "var(--primitive-font-size-md)", dark_value: "var(--primitive-font-size-md)" },
    SemanticMapping { token: "font-size-lg", light_value: "var(--primitive-font-size-lg)", dark_value: "var(--primitive-font-size-lg)" },
    SemanticMapping { token: "font-size-xl", light_value: "var(--primitive-font-size-xl)", dark_value: "var(--primitive-font-size-xl)" },
    SemanticMapping { token: "font-size-2xl", light_value: "var(--primitive-font-size-2xl)", dark_value: "var(--primitive-font-size-2xl)" },
    SemanticMapping { token: "font-size-3xl", light_value: "var(--primitive-font-size-3xl)", dark_value: "var(--primitive-font-size-3xl)" },
    SemanticMapping { token: "font-size-base", light_value: "var(--primitive-font-size-md)", dark_value: "var(--primitive-font-size-md)" },
    SemanticMapping { token: "font-weight-regular", light_value: "var(--primitive-font-weight-normal)", dark_value: "var(--primitive-font-weight-normal)" },
    SemanticMapping { token: "font-weight-medium", light_value: "var(--primitive-font-weight-medium)", dark_value: "var(--primitive-font-weight-medium)" },
    SemanticMapping { token: "font-weight-semibold", light_value: "var(--primitive-font-weight-semibold)", dark_value: "var(--primitive-font-weight-semibold)" },
    SemanticMapping { token: "font-weight-bold", light_value: "var(--primitive-font-weight-bold)", dark_value: "var(--primitive-font-weight-bold)" },
    SemanticMapping { token: "line-height-tight", light_value: "var(--primitive-line-height-tight)", dark_value: "var(--primitive-line-height-tight)" },
    SemanticMapping { token: "line-height-normal", light_value: "var(--primitive-line-height-normal)", dark_value: "var(--primitive-line-height-normal)" },
    SemanticMapping { token: "line-height-relaxed", light_value: "var(--primitive-line-height-relaxed)", dark_value: "var(--primitive-line-height-relaxed)" },
    SemanticMapping { token: "motion-duration-fast", light_value: "var(--primitive-motion-duration-fast)", dark_value: "var(--primitive-motion-duration-fast)" },
    SemanticMapping { token: "motion-duration-normal", light_value: "var(--primitive-motion-duration-normal)", dark_value: "var(--primitive-motion-duration-normal)" },
    SemanticMapping { token: "motion-ease-standard", light_value: "var(--primitive-motion-ease-out)", dark_value: "var(--primitive-motion-ease-out)" },
    SemanticMapping { token: "motion-ease-emphasized", light_value: "var(--primitive-motion-ease-emphasized)", dark_value: "var(--primitive-motion-ease-emphasized)" },
    SemanticMapping { token: "animate-delay-none", light_value: "0ms", dark_value: "0ms" },
    SemanticMapping { token: "animate-delay-short", light_value: "var(--primitive-motion-duration-fast)", dark_value: "var(--primitive-motion-duration-fast)" },
    SemanticMapping { token: "animate-delay-long", light_value: "var(--primitive-motion-duration-normal)", dark_value: "var(--primitive-motion-duration-normal)" },
    SemanticMapping { token: "animate-duration-fast", light_value: "var(--primitive-motion-duration-fast)", dark_value: "var(--primitive-motion-duration-fast)" },
    SemanticMapping { token: "animate-duration-normal", light_value: "var(--primitive-motion-duration-normal)", dark_value: "var(--primitive-motion-duration-normal)" },
    SemanticMapping { token: "animate-duration-slow", light_value: "var(--primitive-motion-duration-slow)", dark_value: "var(--primitive-motion-duration-slow)" },
    SemanticMapping { token: "animate-ease-linear", light_value: "var(--primitive-motion-ease-linear)", dark_value: "var(--primitive-motion-ease-linear)" },
    SemanticMapping { token: "animate-ease-standard", light_value: "var(--primitive-motion-ease-out)", dark_value: "var(--primitive-motion-ease-out)" },
    SemanticMapping { token: "animate-ease-emphasized", light_value: "var(--primitive-motion-ease-emphasized)", dark_value: "var(--primitive-motion-ease-emphasized)" },
];

pub const SEMANTIC_TOKENS: &[&str] = &[
    "color-card", "color-background", "color-foreground", "color-border",
    "color-muted", "color-muted-hsl", "color-muted-foreground", "color-primary",
    "color-primary-foreground", "color-destructive", "color-accent", "color-warning", "color-success",
    "color-bg-elevated", "color-bg-emphasis", "color-bg-muted", "color-bg-surface",
    "color-border-default", "color-border-emphasis", "color-border-muted",
    "color-fg-default", "color-fg-emphasis", "color-fg-muted", "color-fg-subtle", "color-fg-on-emphasis",
    "color-danger-bg", "color-danger-fg",
    "color-success-bg", "color-success-fg", "color-success-border",
    "color-primary-bg", "color-primary-fg", "color-primary-border",
    "color-popover",
    "space-2xs", "space-xs", "space-sm", "space-md", "space-lg", "space-xl", "space-2xl", "space-3xl",
    "radius-sm", "radius-md", "radius-lg", "radius-xl", "radius-2xl", "radius-full",
    "shadow-sm", "shadow-md", "shadow-lg", "shadow-xl",
    "font-family-sans", "font-family-mono",
    "font-size-xs", "font-size-sm", "font-size-md", "font-size-lg", "font-size-xl", "font-size-2xl", "font-size-3xl", "font-size-base",
    "font-weight-regular", "font-weight-medium", "font-weight-semibold", "font-weight-bold",
    "line-height-tight", "line-height-normal", "line-height-relaxed",
    "motion-duration-fast", "motion-duration-normal", "motion-ease-standard", "motion-ease-emphasized",
    "animate-delay-none", "animate-delay-short", "animate-delay-long",
    "animate-duration-fast", "animate-duration-normal", "animate-duration-slow",
    "animate-ease-linear", "animate-ease-standard", "animate-ease-emphasized",
];
