// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const MODAL_API: ComponentApi = ComponentApi {
    id: "modal",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const MODALTRIGGER_API: ComponentApi = ComponentApi {
    id: "modal-trigger",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALPORTAL_API: ComponentApi = ComponentApi {
    id: "modal-portal",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const MODALOVERLAY_API: ComponentApi = ComponentApi {
    id: "modal-overlay",
    description: "Modal window component",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALCONTENT_API: ComponentApi = ComponentApi {
    id: "modal-content",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALTITLE_API: ComponentApi = ComponentApi {
    id: "modal-title",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "modal-description",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALCLOSE_API: ComponentApi = ComponentApi {
    id: "modal-close",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const MODALFOOTER_API: ComponentApi = ComponentApi {
    id: "modal-footer",
    description: "Modal window component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

