// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const MODAL_API: ComponentApi = ComponentApi {
    id: "modal",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "open", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const MODALOVERLAY_API: ComponentApi = ComponentApi {
    id: "modal-overlay",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const MODALCONTENT_API: ComponentApi = ComponentApi {
    id: "modal-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

