// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const WIZARD_API: ComponentApi = ComponentApi {
    id: "wizard",
    props: &[
        PropDef { name: "steps", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "body", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "actions", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

