// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOGGLEGROUP_API: ComponentApi = ComponentApi {
    id: "toggle-group",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "multiple", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
    ],
};

