// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOGGLEGROUP_API: ComponentApi = ComponentApi {
    id: "toggle-group",
    description: "Group of toggle buttons",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "multiple", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const TOGGLEGROUPITEM_API: ComponentApi = ComponentApi {
    id: "toggle-group-item",
    description: "Group of toggle buttons",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "on", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
    ],
};

