// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CHART_API: ComponentApi = ComponentApi {
    id: "chart",
    description: "Data chart visualization",
    props: &[
        PropDef { name: "data", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "chart_type", kind: PropType::String, required: false, default: Some("line"), description: "Prop value" },
        PropDef { name: "height", kind: PropType::Number, required: false, default: Some("320u32"), description: "Prop value" },
        PropDef { name: "show_grid", kind: PropType::Bool, required: false, default: Some("true"), description: "Prop value" },
        PropDef { name: "show_legend", kind: PropType::Bool, required: false, default: Some("true"), description: "Prop value" },
        PropDef { name: "animate", kind: PropType::Bool, required: false, default: Some("true"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some(""), description: "Accessible label for screen readers" },
    ],
};

