// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CHART_API: ComponentApi = ComponentApi {
    id: "chart",
    props: &[
        PropDef { name: "data", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "chart_type", kind: PropType::Enum(&["bar", "line", "area", "pie", "donut", "scatter", "radar"]), required: false, default: Some("line"), description: "" },
        PropDef { name: "height", kind: PropType::Number, required: false, default: Some("320u32"), description: "" },
        PropDef { name: "show_grid", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "show_legend", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "_show_tooltip", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "animate", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_max_width", kind: PropType::Number, required: false, default: None, description: "" },
        PropDef { name: "_sync_table", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_sync_scope", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

