// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SPINNER_API: ComponentApi = ComponentApi {
    id: "spinner",
    props: &[
        PropDef { name: "size", kind: PropType::String, required: false, default: Some("medium"), description: "" },
        PropDef { name: "paused", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some("Loading"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

