// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORMFIELDBLOCK_API: ComponentApi = ComponentApi {
    id: "form-field-block",
    props: &[
        PropDef { name: "label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "input", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "hint", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "error", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

