// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORMFIELDBLOCK_API: ComponentApi = ComponentApi {
    id: "form-field-block",
    description: "Form field block with label, input, hint and error regions",
    props: &[
        PropDef { name: "label", kind: PropType::Children, required: false, default: None, description: "Accessible label text" },
        PropDef { name: "input", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "hint", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "error", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

