// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{StackPrimitive as Stack, StackDirection, StackGap}; 

pub const DATATABLEBLOCK_API: ComponentApi = ComponentApi {
    id: "data-table-block",
    description: "Data table block with toolbar, column header, rows, empty state and pagination",
    props: &[
        PropDef { name: "toolbar", kind: PropType::Children, required: false, default: None, description: "Toolbar slot" },
        PropDef { name: "header", kind: PropType::Children, required: false, default: None, description: "Header region slot" },
        PropDef { name: "body", kind: PropType::Children, required: false, default: None, description: "Body region slot" },
        PropDef { name: "empty", kind: PropType::Children, required: false, default: None, description: "Empty state slot" },
        PropDef { name: "pagination", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

