// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ALERTDIALOG_API: ComponentApi = ComponentApi {
    id: "alert-dialog",
    description: "Alert dialog for critical confirmations",
    props: &[
        PropDef { name: "trigger_label", kind: PropType::String, required: false, default: Some("Delete"), description: "Prop value" },
        PropDef { name: "confirm_label", kind: PropType::String, required: false, default: Some("Confirm"), description: "Prop value" },
        PropDef { name: "cancel_label", kind: PropType::String, required: false, default: Some("Cancel"), description: "Prop value" },
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "Title slot or text" },
        PropDef { name: "description", kind: PropType::String, required: false, default: None, description: "Description slot or text" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

