// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ALERTDIALOG_API: ComponentApi = ComponentApi {
    id: "alert-dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGTRIGGER_API: ComponentApi = ComponentApi {
    id: "alert-dialog-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("primary"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGPORTAL_API: ComponentApi = ComponentApi {
    id: "alert-dialog-portal",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const ALERTDIALOGOVERLAY_API: ComponentApi = ComponentApi {
    id: "alert-dialog-overlay",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGCONTENT_API: ComponentApi = ComponentApi {
    id: "alert-dialog-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGTITLE_API: ComponentApi = ComponentApi {
    id: "alert-dialog-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "alert-dialog-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDIALOGCLOSE_API: ComponentApi = ComponentApi {
    id: "alert-dialog-close",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("outline"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

