// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const STATGROUPBLOCK_API: ComponentApi = ComponentApi {
    id: "stat-group-block",
    description: "Dashboard stat group block for displaying metric collections",
    props: &[
        PropDef { name: "stats", kind: PropType::Children, required: false, default: None, description: "Stats slot" },
        PropDef { name: "cols", kind: PropType::String, required: false, default: Some("three"), description: "Number of grid columns" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

