// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const STATGROUPBLOCK_API: ComponentApi = ComponentApi {
    id: "stat-group-block",
    props: &[
        PropDef { name: "stats", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "cols", kind: PropType::String, required: false, default: Some("three"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

