// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{CalloutVariant}; 

pub const CALLOUT_API: ComponentApi = ComponentApi {
    id: "callout",
    description: "Callout info box",
    props: &[
        PropDef { name: "title", kind: PropType::String, required: false, default: None, description: "Title slot or text" },
        PropDef { name: "description", kind: PropType::String, required: false, default: None, description: "Description slot or text" },
        PropDef { name: "icon", kind: PropType::String, required: false, default: None, description: "Prop value" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

