// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CALLOUT_API: ComponentApi = ComponentApi {
    id: "callout",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const CALLOUTICON_API: ComponentApi = ComponentApi {
    id: "callout-icon",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const CALLOUTTITLE_API: ComponentApi = ComponentApi {
    id: "callout-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const CALLOUTDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "callout-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

