// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SIDEBARLAYOUT_API: ComponentApi = ComponentApi {
    id: "sidebar-layout",
    props: &[
        PropDef { name: "side", kind: PropType::String, required: false, default: Some("left"), description: "" },
        PropDef { name: "nav", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "main", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

