// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SIDEBARLAYOUT_API: ComponentApi = ComponentApi {
    id: "sidebar-layout",
    description: "Block-level sidebar and main content",
    props: &[
        PropDef { name: "side", kind: PropType::String, required: false, default: Some("left"), description: "Tooltip or popover side" },
        PropDef { name: "nav", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "main", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

