import { ThemeDefinition } from '../../engine/schema';

/**
 * Premium Dark TweakCN Preset
 * Idêntico à estética do TweakCN
 * Profundidade, nuance quente, contrastes suaves, elevation levels
 */
export const tweakcnDark: ThemeDefinition = {
  version: 1,
  id: 'tweakcn-dark',
  name: 'TweakCN Dark',
  author: 'Cristiano Bertulucci',
  description: 'Premium dark theme with warm nuances and soft elevation',
  modes: {
    light: {
      colors: {
        primary: { h: 14, s: 63, l: 51 },
        primaryForeground: { h: 0, s: 0, l: 100 },
        secondary: { h: 0, s: 0, l: 95 },
        secondaryForeground: { h: 18, s: 8, l: 12 },
        accent: { h: 14, s: 63, l: 51 },
        accentForeground: { h: 0, s: 0, l: 100 },
        background: { h: 0, s: 0, l: 100 },
        foreground: { h: 0, s: 0, l: 5 },
        card: { h: 0, s: 0, l: 100 },
        cardForeground: { h: 0, s: 0, l: 5 },
        popover: { h: 0, s: 0, l: 100 },
        popoverForeground: { h: 0, s: 0, l: 5 },
        muted: { h: 18, s: 6, l: 95 },
        mutedForeground: { h: 20, s: 5, l: 45 },
        destructive: { h: 0, s: 63, l: 45 },
        destructiveForeground: { h: 0, s: 0, l: 98 },
        border: { h: 18, s: 5, l: 88 },
        input: { h: 18, s: 5, l: 88 },
        ring: { h: 14, s: 63, l: 51 },
        chart1: { h: 14, s: 63, l: 51 },
        chart2: { h: 20, s: 60, l: 48 },
        chart3: { h: 26, s: 57, l: 45 },
        chart4: { h: 32, s: 54, l: 42 },
        chart5: { h: 38, s: 51, l: 39 },
        sidebarBackground: { h: 0, s: 0, l: 98 },
        sidebarForeground: { h: 0, s: 0, l: 5 },
        sidebarPrimary: { h: 14, s: 63, l: 51 },
        sidebarPrimaryForeground: { h: 0, s: 0, l: 100 },
        sidebarAccent: { h: 14, s: 63, l: 51 },
        sidebarAccentForeground: { h: 0, s: 0, l: 100 },
        sidebarBorder: { h: 18, s: 5, l: 88 },
        sidebarRing: { h: 14, s: 63, l: 51 },
      },
      typography: {
        fontSans: 'Inter',
        fontSerif: 'Merriweather',
        fontMono: 'JetBrains Mono',
        letterSpacing: 0,
      },
      spacing: {
        radius: 0.5,
        spacing: 0.25,
      },
      shadow: {
        color: { h: 0, s: 0, l: 0 },
        opacity: 0.15,
        blur: 20,
        spread: -5,
        offsetX: 0,
        offsetY: 0,
      },
    },
    dark: {
      colors: {
        primary: { h: 14, s: 63, l: 51 },
        primaryForeground: { h: 0, s: 0, l: 100 },
        secondary: { h: 0, s: 0, l: 95 },
        secondaryForeground: { h: 18, s: 8, l: 12 },
        accent: { h: 14, s: 63, l: 51 },
        accentForeground: { h: 0, s: 0, l: 100 },
        background: { h: 16, s: 10, l: 6 },
        foreground: { h: 0, s: 0, l: 98 },
        card: { h: 18, s: 8, l: 10 },
        cardForeground: { h: 0, s: 0, l: 98 },
        popover: { h: 18, s: 8, l: 12 },
        popoverForeground: { h: 0, s: 0, l: 98 },
        muted: { h: 18, s: 6, l: 20 },
        mutedForeground: { h: 20, s: 5, l: 65 },
        destructive: { h: 0, s: 63, l: 45 },
        destructiveForeground: { h: 0, s: 0, l: 98 },
        border: { h: 18, s: 5, l: 18 },
        input: { h: 18, s: 5, l: 18 },
        ring: { h: 14, s: 63, l: 51 },
        chart1: { h: 14, s: 63, l: 51 },
        chart2: { h: 20, s: 60, l: 48 },
        chart3: { h: 26, s: 57, l: 45 },
        chart4: { h: 32, s: 54, l: 42 },
        chart5: { h: 38, s: 51, l: 39 },
        sidebarBackground: { h: 18, s: 8, l: 8 },
        sidebarForeground: { h: 0, s: 0, l: 98 },
        sidebarPrimary: { h: 14, s: 63, l: 51 },
        sidebarPrimaryForeground: { h: 0, s: 0, l: 100 },
        sidebarAccent: { h: 14, s: 63, l: 51 },
        sidebarAccentForeground: { h: 0, s: 0, l: 100 },
        sidebarBorder: { h: 18, s: 5, l: 18 },
        sidebarRing: { h: 14, s: 63, l: 51 },
      },
      typography: {
        fontSans: 'Inter',
        fontSerif: 'Merriweather',
        fontMono: 'JetBrains Mono',
        letterSpacing: 0,
      },
      spacing: {
        radius: 0.5,
        spacing: 0.25,
      },
      shadow: {
        color: { h: 0, s: 0, l: 0 },
        opacity: 0.4,
        blur: 20,
        spread: -5,
        offsetX: 0,
        offsetY: 0,
      },
    },
  },
};
