// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SIDEBAR_API: ComponentApi = ComponentApi {
    id: "sidebar",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("open"), description: "" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "rail"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARHEADER_API: ComponentApi = ComponentApi {
    id: "sidebar-header",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARCONTENT_API: ComponentApi = ComponentApi {
    id: "sidebar-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARFOOTER_API: ComponentApi = ComponentApi {
    id: "sidebar-footer",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARMENU_API: ComponentApi = ComponentApi {
    id: "sidebar-menu",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARMENUITEM_API: ComponentApi = ComponentApi {
    id: "sidebar-menu-item",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "active", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
    ],
};

pub const SIDEBARMENUGROUP_API: ComponentApi = ComponentApi {
    id: "sidebar-menu-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "label", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const SIDEBARSEPARATOR_API: ComponentApi = ComponentApi {
    id: "sidebar-separator",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const SIDEBARGROUPLABEL_API: ComponentApi = ComponentApi {
    id: "sidebar-group-label",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

