// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SIDEBAR_API: ComponentApi = ComponentApi {
    id: "sidebar",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "state", kind: PropType::Enum(&["closed", "open"]), required: false, default: Some("open"), description: "Loading or visibility state" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "rail"]), required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARHEADER_API: ComponentApi = ComponentApi {
    id: "sidebar-header",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARCONTENT_API: ComponentApi = ComponentApi {
    id: "sidebar-content",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARFOOTER_API: ComponentApi = ComponentApi {
    id: "sidebar-footer",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARMENU_API: ComponentApi = ComponentApi {
    id: "sidebar-menu",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARMENUITEM_API: ComponentApi = ComponentApi {
    id: "sidebar-menu-item",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some(""), description: "Navigation target URL" },
        PropDef { name: "active", kind: PropType::Enum(&["inactive", "active"]), required: false, default: Some("inactive"), description: "Active/selected state" },
        PropDef { name: "disabled", kind: PropType::Enum(&["enabled", "disabled"]), required: false, default: Some("enabled"), description: "Whether the component is disabled" },
    ],
};

pub const SIDEBARMENUGROUP_API: ComponentApi = ComponentApi {
    id: "sidebar-menu-group",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "label", kind: PropType::String, required: false, default: None, description: "Accessible label text" },
    ],
};

pub const SIDEBARSEPARATOR_API: ComponentApi = ComponentApi {
    id: "sidebar-separator",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SIDEBARGROUPLABEL_API: ComponentApi = ComponentApi {
    id: "sidebar-group-label",
    description: "Sidebar navigation component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

