// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SWITCH_API: ComponentApi = ComponentApi {
    id: "switch",
    description: "Toggle switch on off",
    props: &[
        PropDef { name: "checked", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is checked" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "Form field name" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

