// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ASPECTRATIO_API: ComponentApi = ComponentApi {
    id: "aspect-ratio",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "ratio_w", kind: PropType::Number, required: false, default: Some("16.0f32"), description: "" },
        PropDef { name: "height", kind: PropType::Number, required: false, default: Some("9.0f32"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

