// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ASPECTRATIO_API: ComponentApi = ComponentApi {
    id: "aspect-ratio",
    description: "Aspect ratio container",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "ratio_w", kind: PropType::Number, required: false, default: Some("16.0f32"), description: "Prop value" },
        PropDef { name: "ratio_h", kind: PropType::Number, required: false, default: Some("9.0f32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

