// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CARDBLOCK_API: ComponentApi = ComponentApi {
    id: "card-block",
    description: "Card block with header, content and footer regions",
    props: &[
        PropDef { name: "header", kind: PropType::Children, required: false, default: None, description: "Header region slot" },
        PropDef { name: "content", kind: PropType::Children, required: false, default: None, description: "Content region slot" },
        PropDef { name: "footer", kind: PropType::Children, required: false, default: None, description: "Footer region slot" },
        PropDef { name: "variant", kind: PropType::Enum(&["interactive", "outlined", "elevated"]), required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

