// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DOCPROGRESS_API: ComponentApi = ComponentApi {
    id: "doc-progress",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const DOCPROGRESSSLOT_API: ComponentApi = ComponentApi {
    id: "doc-progress-slot",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "scroll_target", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "position", kind: PropType::Enum(&["top", "bottom"]), required: false, default: Some("top"), description: "" },
    ],
};

