// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DOCPROGRESS_API: ComponentApi = ComponentApi {
    id: "doc-progress",
    description: "Document progress indicator",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const DOCPROGRESSSLOT_API: ComponentApi = ComponentApi {
    id: "doc-progress-slot",
    description: "Document progress indicator",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "scroll_target", kind: PropType::String, required: false, default: Some(""), description: "Scroll target element id" },
        PropDef { name: "position", kind: PropType::String, required: false, default: Some("top"), description: "Prop value" },
    ],
};

