// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const DOCPROGRESS_API: ComponentApi = ComponentApi {
    id: "doc-progress",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

