[package]
name = "canonrs-interactions-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
    "Window", "Document", "Element", "HtmlElement",
    "EventTarget", "MouseEvent", "KeyboardEvent",
    "FocusEvent", "NodeList", "Node",
    "CssStyleDeclaration", "DomRect",
    "HtmlInputElement",
    "MutationObserver", "MutationObserverInit", "MutationRecord",
    "PointerEvent",
    "History",
    "ScrollToOptions", "ScrollBehavior",
    "IntersectionObserver", "IntersectionObserverInit", "IntersectionObserverEntry",
] }

[features]
default = []
