// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TEXTAREA_API: ComponentApi = ComponentApi {
    id: "textarea",
    props: &[
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "placeholder", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "readonly", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "required", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "aria_labelledby", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "aria_describedby", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "rows", kind: PropType::Number, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

