// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TEXTAREA_API: ComponentApi = ComponentApi {
    id: "textarea",
    description: "Multi-line text input",
    props: &[
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "placeholder", kind: PropType::String, required: false, default: Some(""), description: "Placeholder text" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "Form field name" },
        PropDef { name: "disabled", kind: PropType::Enum(&["enabled", "disabled"]), required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "readonly", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "required", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "aria_labelledby", kind: PropType::String, required: false, default: Some(""), description: "Prop value" },
        PropDef { name: "aria_describedby", kind: PropType::String, required: false, default: Some(""), description: "Prop value" },
        PropDef { name: "rows", kind: PropType::Number, required: false, default: Some("3u32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

