// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOOLBARBLOCK_API: ComponentApi = ComponentApi {
    id: "toolbar-block",
    props: &[
        PropDef { name: "left", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "center", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "right", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

