// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FIELDSET_API: ComponentApi = ComponentApi {
    id: "field-set",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDLEGEND_API: ComponentApi = ComponentApi {
    id: "field-legend",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("legend"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDGROUP_API: ComponentApi = ComponentApi {
    id: "field-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELD_API: ComponentApi = ComponentApi {
    id: "field",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "orientation", kind: PropType::String, required: false, default: Some("vertical"), description: "" },
        PropDef { name: "validation", kind: PropType::String, required: false, default: Some("none"), description: "" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDCONTENT_API: ComponentApi = ComponentApi {
    id: "field-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDLABEL_API: ComponentApi = ComponentApi {
    id: "field-label",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "html_for", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDTITLE_API: ComponentApi = ComponentApi {
    id: "field-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "field-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDERROR_API: ComponentApi = ComponentApi {
    id: "field-error",
    props: &[
        PropDef { name: ")] errors", kind: PropType::String, required: false, default: Some("vec![]"), description: "" },
        PropDef { name: "validation", kind: PropType::String, required: false, default: Some("none"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FIELDSEPARATOR_API: ComponentApi = ComponentApi {
    id: "field-separator",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

