// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FIELD_API: ComponentApi = ComponentApi {
    id: "field",
    description: "Form field wrapper with label and error",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "orientation", kind: PropType::String, required: false, default: Some("vertical"), description: "Horizontal or vertical orientation" },
        PropDef { name: "_validation", kind: PropType::String, required: false, default: Some("none"), description: "Prop value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

