// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{ResizableOrientation}; 

pub const RESIZABLE_API: ComponentApi = ComponentApi {
    id: "resizable",
    description: "Resizable panel component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "orientation", kind: PropType::String, required: false, default: Some("horizontal"), description: "Horizontal or vertical orientation" },
        PropDef { name: "min_size", kind: PropType::Number, required: false, default: Some("20u32"), description: "Prop value" },
        PropDef { name: "max_size", kind: PropType::Number, required: false, default: Some("80u32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const RESIZABLEPANEL_API: ComponentApi = ComponentApi {
    id: "resizable-panel",
    description: "Resizable panel component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "default_size", kind: PropType::Number, required: false, default: Some("50u32"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const RESIZABLEHANDLE_API: ComponentApi = ComponentApi {
    id: "resizable-handle",
    description: "Resizable panel component",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

