// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const RESIZABLE_API: ComponentApi = ComponentApi {
    id: "resizable",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "orientation", kind: PropType::Enum(&["horizontal", "vertical"]), required: false, default: Some("horizontal"), description: "" },
        PropDef { name: "min_size", kind: PropType::Number, required: false, default: Some("20u32"), description: "" },
        PropDef { name: "max_size", kind: PropType::Number, required: false, default: Some("80u32"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const RESIZABLEPANEL_API: ComponentApi = ComponentApi {
    id: "resizable-panel",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "default_size", kind: PropType::Number, required: false, default: Some("50u32"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const RESIZABLEHANDLE_API: ComponentApi = ComponentApi {
    id: "resizable-handle",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

