// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const GRID_API: ComponentApi = ComponentApi {
    id: "grid",
    props: &[
        PropDef { name: "columns", kind: PropType::String, required: false, default: Some("3u8"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "items", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

