// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const LOGO_API: ComponentApi = ComponentApi {
    id: "logo",
    props: &[
        PropDef { name: "size", kind: PropType::Enum(&["sm", "md", "lg"]), required: false, default: Some("md"), description: "" },
        PropDef { name: "variant", kind: PropType::Enum(&["brand", "neutral"]), required: false, default: Some("brand"), description: "" },
        PropDef { name: "wordmark", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "tagline", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "href", kind: PropType::String, required: false, default: Some("/"), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

