// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HERO_API: ComponentApi = ComponentApi {
    id: "hero",
    description: "Page hero block with media, content and actions regions",
    props: &[
        PropDef { name: "header", kind: PropType::Children, required: false, default: None, description: "Header region slot" },
        PropDef { name: "media", kind: PropType::Children, required: false, default: None, description: "Prop value" },
        PropDef { name: "content", kind: PropType::Children, required: false, default: None, description: "Content region slot" },
        PropDef { name: "actions", kind: PropType::Children, required: false, default: None, description: "Actions region slot" },
        PropDef { name: "footer", kind: PropType::Children, required: false, default: None, description: "Footer region slot" },
        PropDef { name: "variant", kind: PropType::Enum(&["centered", "split", "media-top"]), required: false, default: Some("centered"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

