// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const HERO_API: ComponentApi = ComponentApi {
    id: "hero",
    props: &[
        PropDef { name: "header", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "media", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "content", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "actions", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "footer", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

