[package]
name = "canonrs-interactions-gesture"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "CanonRS gesture interaction handlers"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true, features = [
    "Window", "Document", "Element", "HtmlElement",
    "EventTarget", "MouseEvent", "PointerEvent",
    "CssStyleDeclaration", "DomRect", "NodeList",
    "console", "FocusEvent", "KeyboardEvent",
    "TouchEvent", "WheelEvent", "ResizeObserver",
    "ResizeObserverEntry", "ResizeObserverSize",
    "CustomEvent", "CustomEventInit",
] }

canonrs-interactions-core = { version = "0.1.0",  path = "../canonrs-interactions-core" }

[features]
default = []
