// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ALERT_API: ComponentApi = ComponentApi {
    id: "alert",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::Enum(&["default", "destructive", "warning", "success"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTTITLE_API: ComponentApi = ComponentApi {
    id: "alert-title",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "alert-description",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

pub const ALERTCLOSEBUTTON_API: ComponentApi = ComponentApi {
    id: "alert-close-button",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

