// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const NAVITEM_API: ComponentApi = ComponentApi {
    id: "nav-item",
    props: &[
        PropDef { name: "label", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "href", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "active", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "icon", kind: PropType::Children, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const NAVGROUP_API: ComponentApi = ComponentApi {
    id: "nav-group",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "direction", kind: PropType::String, required: false, default: Some("from("vertical")"), description: "" },
    ],
};

