// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CONFIRMDIALOG_API: ComponentApi = ComponentApi {
    id: "confirm-dialog",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGTRIGGER_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-trigger",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGPORTAL_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-portal",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
    ],
};

pub const CONFIRMDIALOGCONTENT_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-content",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGTITLE_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-title",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGDESCRIPTION_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-description",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGFOOTER_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-footer",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGCANCEL_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-cancel",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

pub const CONFIRMDIALOGCONFIRM_API: ComponentApi = ComponentApi {
    id: "confirm-dialog-confirm",
    description: "Confirmation dialog",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "variant", kind: PropType::String, required: false, default: Some("default"), description: "Visual variant of the component" },
        PropDef { name: "class", kind: PropType::String, required: false, default: None, description: "Additional CSS class names" },
    ],
};

