// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const CONFIRMDIALOG_API: ComponentApi = ComponentApi {
    id: "confirm-dialog",
    props: &[
        PropDef { name: "title", kind: PropType::String, required: false, default: Some("Confirm"), description: "" },
        PropDef { name: "message", kind: PropType::String, required: false, default: Some("Are you sure you want to continue?"), description: "" },
        PropDef { name: "confirm_text", kind: PropType::String, required: false, default: Some("Confirm"), description: "" },
        PropDef { name: "cancel_text", kind: PropType::String, required: false, default: Some("Cancel"), description: "" },
        PropDef { name: "destructive", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

