// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SLIDER_API: ComponentApi = ComponentApi {
    id: "slider",
    description: "Range slider input",
    props: &[
        PropDef { name: "min", kind: PropType::Number, required: false, default: Some("0.0"), description: "Prop value" },
        PropDef { name: "max", kind: PropType::Number, required: false, default: Some("100.0"), description: "Prop value" },
        PropDef { name: "step", kind: PropType::Number, required: false, default: Some("1.0"), description: "Prop value" },
        PropDef { name: "value", kind: PropType::Number, required: false, default: Some("50.0"), description: "Current value" },
        PropDef { name: "disabled", kind: PropType::Enum(&["enabled", "disabled"]), required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "orientation", kind: PropType::Enum(&["horizontal", "vertical"]), required: false, default: Some("horizontal"), description: "Horizontal or vertical orientation" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const SLIDERWITHMARKS_API: ComponentApi = ComponentApi {
    id: "slider-with-marks",
    description: "Range slider input",
    props: &[
        PropDef { name: "min", kind: PropType::Number, required: false, default: Some("0.0"), description: "Prop value" },
        PropDef { name: "max", kind: PropType::Number, required: false, default: Some("100.0"), description: "Prop value" },
        PropDef { name: "step", kind: PropType::Number, required: false, default: Some("10.0"), description: "Prop value" },
        PropDef { name: "value", kind: PropType::Number, required: false, default: Some("50.0"), description: "Current value" },
        PropDef { name: "disabled", kind: PropType::Enum(&["enabled", "disabled"]), required: false, default: Some("enabled"), description: "Whether the component is disabled" },
        PropDef { name: "orientation", kind: PropType::Enum(&["horizontal", "vertical"]), required: false, default: Some("horizontal"), description: "Horizontal or vertical orientation" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

