// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SLIDER_API: ComponentApi = ComponentApi {
    id: "slider",
    props: &[
        PropDef { name: "min", kind: PropType::Number, required: false, default: Some("0.0"), description: "" },
        PropDef { name: "max", kind: PropType::Number, required: false, default: Some("100.0"), description: "" },
        PropDef { name: "step", kind: PropType::Number, required: false, default: Some("1.0"), description: "" },
        PropDef { name: "value", kind: PropType::Number, required: false, default: Some("50.0"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "orientation", kind: PropType::String, required: false, default: Some("horizontal"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

