// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{DataTableDensity}; 

pub const DATATABLE<T>_API: ComponentApi = ComponentApi {
    id: "data-table<-t>",
    description: "Sortable data table component",
    props: &[
        PropDef { name: "data", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "columns", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "density", kind: PropType::String, required: false, default: Some("default"), description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
        PropDef { name: "page_size", kind: PropType::Number, required: false, default: Some("10"), description: "Prop value" },
        PropDef { name: "selectable", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: "show_density", kind: PropType::Bool, required: false, default: Some("false"), description: "Prop value" },
        PropDef { name: ")] row_actions", kind: PropType::String, required: false, default: Some("vec![]"), description: "Prop value" },
        PropDef { name: ")] bulk_actions", kind: PropType::String, required: false, default: Some("vec![]"), description: "Prop value" },
        PropDef { name: "row_id_fn", kind: PropType::String, required: false, default: None, description: "Prop value" },
    ],
};

