// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const INPUTOTP_API: ComponentApi = ComponentApi {
    id: "input-otp",
    props: &[
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "length", kind: PropType::Number, required: false, default: Some("6u32"), description: "" },
    ],
};

