// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const INPUTOTP_API: ComponentApi = ComponentApi {
    id: "input-otp",
    description: "One-time password input",
    props: &[
        PropDef { name: "length", kind: PropType::Number, required: false, default: Some("6"), description: "Prop value" },
        PropDef { name: "name", kind: PropType::String, required: false, default: Some(""), description: "Form field name" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "initial_value", kind: PropType::String, required: false, default: Some(""), description: "Prop value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

