// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TABS_API: ComponentApi = ComponentApi {
    id: "tabs",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "node_ref", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "default_value", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABSLIST_API: ComponentApi = ComponentApi {
    id: "tabs-list",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABSTRIGGER_API: ComponentApi = ComponentApi {
    id: "tabs-trigger",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "active", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const TABSCONTENT_API: ComponentApi = ComponentApi {
    id: "tabs-content",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "active", kind: PropType::String, required: false, default: Some("inactive"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

