#[cfg(feature = "hydrate")]
mod behavior_registry;

#[cfg(feature = "hydrate")]
mod auto_init;

#[cfg(feature = "hydrate")]
pub mod accordion_behavior;
#[cfg(feature = "hydrate")]
pub mod breadcrumb_behavior;
#[cfg(feature = "hydrate")]
pub mod calendar_behavior;
#[cfg(feature = "hydrate")]
pub mod chart_behavior;
#[cfg(feature = "hydrate")]
pub mod collapsible_behavior;
#[cfg(feature = "hydrate")]
pub mod combobox_behavior;
#[cfg(feature = "hydrate")]
pub mod command_behavior;
#[cfg(feature = "hydrate")]
pub mod context_menu_behavior;
#[cfg(feature = "hydrate")]
pub mod copy_button_behavior;
#[cfg(feature = "hydrate")]
pub mod datatable_behavior;
#[cfg(feature = "hydrate")]
pub mod dialog_behavior;
#[cfg(feature = "hydrate")]
pub mod drawer_behavior;
#[cfg(feature = "hydrate")]
pub mod dropdown_menu_behavior;
#[cfg(feature = "hydrate")]
pub mod hover_card_behavior;
#[cfg(feature = "hydrate")]
pub mod icon_button_behavior;
#[cfg(feature = "hydrate")]
pub mod icon_toggle_behavior;
#[cfg(feature = "hydrate")]
pub mod list_item_behavior;
#[cfg(feature = "hydrate")]
pub mod menubar_behavior;
#[cfg(feature = "hydrate")]
pub mod modal_behavior;
#[cfg(feature = "hydrate")]
pub mod navigation_menu_behavior;
#[cfg(feature = "hydrate")]
pub mod overlay_behavior;
#[cfg(feature = "hydrate")]
pub mod pagination_behavior;
#[cfg(feature = "hydrate")]
pub mod popover_behavior;
#[cfg(feature = "hydrate")]
pub mod scroll_area_behavior;
#[cfg(feature = "hydrate")]
pub mod select_behavior;
pub mod slider_behavior;
#[cfg(feature = "hydrate")]
pub mod sheet_behavior;
#[cfg(feature = "hydrate")]
pub mod sidebar_behavior;
#[cfg(feature = "hydrate")]
pub mod simple_overlay_behavior;
#[cfg(feature = "hydrate")]
pub mod switch_behavior;
#[cfg(feature = "hydrate")]
pub mod theme_toggle_behavior;
#[cfg(feature = "hydrate")]
pub mod toggle_behavior;
#[cfg(feature = "hydrate")]
pub mod tooltip_behavior;
#[cfg(feature = "hydrate")]
pub mod tree_behavior;

#[cfg(feature = "hydrate")]
pub use behavior_registry::*;

#[cfg(feature = "hydrate")]
pub use auto_init::init_canonrs_behaviors;
