// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const AVATAR_API: ComponentApi = ComponentApi {
    id: "avatar",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "size", kind: PropType::Enum(&["xs", "sm", "md", "lg", "xl"]), required: false, default: Some("md"), description: "" },
        PropDef { name: "shape", kind: PropType::Enum(&["circle", "square", "rounded"]), required: false, default: Some("circle"), description: "" },
        PropDef { name: "status", kind: PropType::Enum(&["online", "offline", "busy", "away"]), required: false, default: None, description: "" },
        PropDef { name: "animated", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "badge", kind: PropType::Number, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const AVATARIMAGE_API: ComponentApi = ComponentApi {
    id: "avatar-image",
    props: &[
        PropDef { name: "src", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "alt", kind: PropType::String, required: true, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const AVATARFALLBACK_API: ComponentApi = ComponentApi {
    id: "avatar-fallback",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

