// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const AVATAR_API: ComponentApi = ComponentApi {
    id: "avatar",
    description: "User avatar image",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "size", kind: PropType::Enum(&["xs", "sm", "md", "lg", "xl"]), required: false, default: Some("md"), description: "Size variant of the component" },
        PropDef { name: "shape", kind: PropType::Enum(&["circle", "square", "rounded"]), required: false, default: Some("circle"), description: "Prop value" },
        PropDef { name: "status", kind: PropType::Enum(&["online", "offline", "busy", "away"]), required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const AVATARIMAGE_API: ComponentApi = ComponentApi {
    id: "avatar-image",
    description: "User avatar image",
    props: &[
        PropDef { name: "src", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "alt", kind: PropType::String, required: true, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const AVATARFALLBACK_API: ComponentApi = ComponentApi {
    id: "avatar-fallback",
    description: "User avatar image",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

