// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COMMAND_API: ComponentApi = ComponentApi {
    id: "command",
    description: "Command palette",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "placeholder", kind: PropType::String, required: false, default: Some("Search..."), description: "Placeholder text" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const COMMANDITEM_API: ComponentApi = ComponentApi {
    id: "command-item",
    description: "Command palette",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: false, default: None, description: "Current value" },
        PropDef { name: "group", kind: PropType::String, required: false, default: None, description: "Prop value" },
    ],
};

