// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORMBLOCK_API: ComponentApi = ComponentApi {
    id: "form-block",
    props: &[
        PropDef { name: "layout", kind: PropType::String, required: false, default: Some("vertical"), description: "" },
        PropDef { name: "fields", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "actions", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "_style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

