// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SEPARATOR_API: ComponentApi = ComponentApi {
    id: "separator",
    props: &[
        PropDef { name: "orientation", kind: PropType::String, required: false, default: Some("horizontal"), description: "" },
        PropDef { name: "decorative", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "id", kind: PropType::String, required: false, default: None, description: "" },
    ],
};

