// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PROGRESS_API: ComponentApi = ComponentApi {
    id: "progress",
    props: &[
        PropDef { name: "value", kind: PropType::Number, required: false, default: Some("0.0"), description: "" },
        PropDef { name: "state", kind: PropType::Enum(&["default", "indeterminate", "loading"]), required: false, default: Some("default"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

