// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const PROGRESS_API: ComponentApi = ComponentApi {
    id: "progress",
    description: "Progress bar indicator",
    props: &[
        PropDef { name: "value", kind: PropType::Number, required: false, default: Some("0.0"), description: "Current value" },
        PropDef { name: "state", kind: PropType::String, required: false, default: Some("default"), description: "Loading or visibility state" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

