// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const WIZARDLAYOUT_API: ComponentApi = ComponentApi {
    id: "wizard-layout",
    description: "Step-by-step wizard layout with header, stepper, content and footer",
    props: &[
        PropDef { name: "header", kind: PropType::Children, required: false, default: None, description: "Header region slot" },
        PropDef { name: "stepper", kind: PropType::Children, required: false, default: None, description: "Stepper region slot" },
        PropDef { name: "content", kind: PropType::Children, required: false, default: None, description: "Content region slot" },
        PropDef { name: "footer", kind: PropType::Children, required: false, default: None, description: "Footer region slot" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

