// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const FORM_API: ComponentApi = ComponentApi {
    id: "form",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "action", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "method", kind: PropType::String, required: false, default: Some("post"), description: "" },
        PropDef { name: "enctype", kind: PropType::String, required: false, default: Some("url-encoded"), description: "" },
        PropDef { name: "validation", kind: PropType::String, required: false, default: Some("idle"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "novalidate", kind: PropType::Bool, required: false, default: Some("true"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMSECTION_API: ComponentApi = ComponentApi {
    id: "form-section",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMACTIONS_API: ComponentApi = ComponentApi {
    id: "form-actions",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMFIELD_API: ComponentApi = ComponentApi {
    id: "form-field",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "validation", kind: PropType::String, required: false, default: Some("idle"), description: "" },
        PropDef { name: "disabled", kind: PropType::String, required: false, default: Some("enabled"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMLABEL_API: ComponentApi = ComponentApi {
    id: "form-label",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "html_for", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "required", kind: PropType::Bool, required: false, default: Some("false"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMERROR_API: ComponentApi = ComponentApi {
    id: "form-error",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const FORMHINT_API: ComponentApi = ComponentApi {
    id: "form-hint",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

