// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ANIMATE_API: ComponentApi = ComponentApi {
    id: "animate",
    description: "Animation wrapper component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "animation", kind: PropType::String, required: false, default: Some("fade-in"), description: "Prop value" },
        PropDef { name: "easing", kind: PropType::String, required: false, default: Some("ease-in-out"), description: "Prop value" },
        PropDef { name: "duration", kind: PropType::String, required: false, default: Some("300ms"), description: "Prop value" },
        PropDef { name: "delay", kind: PropType::String, required: false, default: Some(""), description: "Prop value" },
        PropDef { name: "stagger", kind: PropType::Number, required: false, default: None, description: "Prop value" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

