// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const ANIMATE_API: ComponentApi = ComponentApi {
    id: "animate",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "animation", kind: PropType::String, required: false, default: Some("fade-in"), description: "" },
        PropDef { name: "easing", kind: PropType::String, required: false, default: Some("ease-in-out"), description: "" },
        PropDef { name: "duration", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "delay", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

