// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SPLITVIEWLAYOUT_API: ComponentApi = ComponentApi {
    id: "split-view-layout",
    props: &[
        PropDef { name: "ratio", kind: PropType::String, required: false, default: Some("equal"), description: "" },
        PropDef { name: "left", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "right", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

