// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

// imports: use canonrs::primitives::{SplitRatio}; 

pub const SPLITVIEWLAYOUT_API: ComponentApi = ComponentApi {
    id: "split-view-layout",
    description: "Two-panel split layout with configurable ratio for side-by-side content",
    props: &[
        PropDef { name: "ratio", kind: PropType::String, required: false, default: Some("equal"), description: "Split view ratio between panels" },
        PropDef { name: "left", kind: PropType::Children, required: false, default: None, description: "Left panel slot" },
        PropDef { name: "right", kind: PropType::Children, required: false, default: None, description: "Right panel slot" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

