// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const COMMANDPANELBLOCK_API: ComponentApi = ComponentApi {
    id: "command-panel-block",
    props: &[
        PropDef { name: "search", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "results", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "footer", kind: PropType::String, required: false, default: None, description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
        PropDef { name: "style", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

