// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const SECTIONBLOCK_API: ComponentApi = ComponentApi {
    id: "section-block",
    description: "Generic content section block with header, body and footer regions",
    props: &[
        PropDef { name: "header", kind: PropType::Children, required: false, default: None, description: "Header region slot" },
        PropDef { name: "body", kind: PropType::Children, required: false, default: None, description: "Body region slot" },
        PropDef { name: "footer", kind: PropType::Children, required: false, default: None, description: "Footer region slot" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

