use std::path::Path;

fn main() {
    let generated = Path::new("styles/.generated/primitives.css");

    if !generated.exists() {
        println!("cargo:warning=CSS not generated by CanonRS CLI.");
        panic!(
            "\n❌ CanonRS requires CSS generation via CLI.\n\
             Run one of:\n\
               canonrs dev\n\
               canonrs build\n"
        );
    }

    println!("cargo:rerun-if-changed=styles/.generated/");
    println!("cargo:rerun-if-changed=styles/");
}
