// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_boundary.rs + builder.yaml
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const TOOLBAR_API: ComponentApi = ComponentApi {
    id: "toolbar",
    description: "Action toolbar component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "aria_label", kind: PropType::String, required: false, default: Some("Toolbar"), description: "Accessible label for screen readers" },
        PropDef { name: "orientation", kind: PropType::Enum(&["horizontal", "vertical"]), required: false, default: Some("horizontal"), description: "Horizontal or vertical orientation" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "Additional CSS class names" },
    ],
};

pub const TOOLBARITEM_API: ComponentApi = ComponentApi {
    id: "toolbar-item",
    description: "Action toolbar component",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "value", kind: PropType::String, required: false, default: Some(""), description: "Current value" },
        PropDef { name: "disabled", kind: PropType::Bool, required: false, default: Some("false"), description: "Whether the component is disabled" },
    ],
};

pub const TOOLBARSEPARATOR_API: ComponentApi = ComponentApi {
    id: "toolbar-separator",
    description: "Action toolbar component",
    props: &[
    ],
};

