// AUTO-GENERATED by build.rs — do not edit manually.
// Source: *_ui.rs
use crate::catalog_types::{ComponentApi, PropDef, PropType};

pub const STAT_API: ComponentApi = ComponentApi {
    id: "stat",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "size", kind: PropType::Enum(&["sm", "md", "lg"]), required: false, default: Some("md"), description: "" },
        PropDef { name: "align", kind: PropType::Enum(&["start", "center", "end"]), required: false, default: Some("start"), description: "" },
        PropDef { name: "trend", kind: PropType::Enum(&["increase", "decrease", "neutral"]), required: false, default: None, description: "" },
        PropDef { name: "loading", kind: PropType::String, required: false, default: Some("idle"), description: "" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATHEADER_API: ComponentApi = ComponentApi {
    id: "stat-header",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATBODY_API: ComponentApi = ComponentApi {
    id: "stat-body",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATVALUE_API: ComponentApi = ComponentApi {
    id: "stat-value",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATLABEL_API: ComponentApi = ComponentApi {
    id: "stat-label",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATDELTA_API: ComponentApi = ComponentApi {
    id: "stat-delta",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

pub const STATICON_API: ComponentApi = ComponentApi {
    id: "stat-icon",
    props: &[
        PropDef { name: "children", kind: PropType::Children, required: true, default: None, description: "Child elements" },
        PropDef { name: "class", kind: PropType::String, required: false, default: Some(""), description: "" },
    ],
};

